using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Qhta.TextUtils
{
  public enum UnicodeBlock
  {
    Unknown,
    BasicLatin,
    Latin1Supplement,
    LatinExtendedA,
    LatinExtendedB,
    IPAExtensions,
    SpacingModifierLetters,
    CombiningDiacriticalMarks,
    GreekAndCoptic,
    Cyrillic,
    CyrillicSupplement,
    Armenian,
    Hebrew,
    Arabic,
    Syriac,
    ArabicSupplement,
    Thaana,
    NKo,
    Samaritan,
    Mandaic,
    SyriacSupplement,
    ArabicExtendedA,
    Devanagari,
    Bengali,
    Gurmukhi,
    Gujarati,
    Oriya,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhala,
    Thai,
    Lao,
    Tibetan,
    Myanmar,
    Georgian,
    HangulJamo,
    Ethiopic,
    EthiopicSupplement,
    Cherokee,
    UnifiedCanadianAboriginalSyllabics,
    Ogham,
    Runic,
    Tagalog,
    Hanunoo,
    Buhid,
    Tagbanwa,
    Khmer,
    Mongolian,
    UnifiedCanadianAboriginalSyllabicsExtended,
    Limbu,
    TaiLe,
    NewTaiLue,
    KhmerSymbols,
    Buginese,
    TaiTham,
    CombiningDiacriticalMarksExtended,
    Balinese,
    Sundanese,
    Batak,
    Lepcha,
    OlChiki,
    CyrillicExtendedC,
    GeorgianExtended,
    SundaneseSupplement,
    VedicExtensions,
    PhoneticExtensions,
    PhoneticExtensionsSupplement,
    CombiningDiacriticalMarksSupplement,
    LatinExtendedAdditional,
    GreekExtended,
    GeneralPunctuation,
    SuperscriptsAndSubscripts,
    CurrencySymbols,
    CombiningDiacriticalMarksforSymbols,
    LetterlikeSymbols,
    NumberForms,
    Arrows,
    MathematicalOperators,
    MiscellaneousTechnical,
    ControlPictures,
    OpticalCharacterRecognition,
    EnclosedAlphanumerics,
    BoxDrawing,
    BlockElements,
    GeometricShapes,
    MiscellaneousSymbols,
    Dingbats,
    MiscellaneousMathematicalSymbolsA,
    SupplementalArrowsA,
    BraillePatterns,
    SupplementalArrowsB,
    MiscellaneousMathematicalSymbolsB,
    SupplementalMathematicalOperators,
    MiscellaneousSymbolsAndArrows,
    Glagolitic,
    LatinExtendedC,
    Coptic,
    GeorgianSupplement,
    Tifinagh,
    EthiopicExtended,
    CyrillicExtendedA,
    SupplementalPunctuation,
    CJKRadicalsSupplement,
    KangxiRadicals,
    IdeographicDescriptionCharacters,
    CJKSymbolsAndPunctuation,
    Hiragana,
    Katakana,
    Bopomofo,
    HangulCompatibilityJamo,
    Kanbun,
    BopomofoExtended,
    CJKStrokes,
    KatakanaPhoneticExtensions,
    EnclosedCJKLettersAndMonths,
    CJKCompatibility,
    CJKUnifiedIdeographsExtensionA,
    YijingHexagramSymbols,
    CJKUnifiedIdeographs,
    YiSyllables,
    YiRadicals,
    Lisu,
    Vai,
    CyrillicExtendedB,
    Bamum,
    ModifierToneLetters,
    LatinExtendedD,
    SylotiNagri,
    CommonIndicNumberForms,
    Phagspa,
    Saurashtra,
    DevanagariExtended,
    KayahLi,
    Rejang,
    HangulJamoExtendedA,
    Javanese,
    MyanmarExtendedB,
    Cham,
    MyanmarExtendedA,
    TaiViet,
    MeeteiMayekExtensions,
    EthiopicExtendedA,
    LatinExtendedE,
    CherokeeSupplement,
    MeeteiMayek,
    HangulSyllables,
    HangulJamoExtendedB,
    HighSurrogates,
    HighPrivateUseSurrogates,
    LowSurrogates,
    PrivateUseArea,
    CJKCompatibilityIdeographs,
    AlphabeticPresentationForms,
    ArabicPresentationFormsA,
    VariationSelectors,
    VerticalForms,
    CombiningHalfMarks,
    CJKCompatibilityForms,
    SmallFormVariants,
    ArabicPresentationFormsB,
    HalfwidthAndFullwidthForms,
    Specials,
    LinearBSyllabary,
    LinearBIdeograms,
    AegeanNumbers,
    AncientGreekNumbers,
    AncientSymbols,
    PhaistosDisc,
    Lycian,
    Carian,
    CopticEpactNumbers,
    OldItalic,
    Gothic,
    OldPermic,
    Ugaritic,
    OldPersian,
    Deseret,
    Shavian,
    Osmanya,
    Osage,
    Elbasan,
    CaucasianAlbanian,
    LinearA,
    CypriotSyllabary,
    ImperialAramaic,
    Palmyrene,
    Nabataean,
    Hatran,
    Phoenician,
    Lydian,
    MeroiticHieroglyphs,
    MeroiticCursive,
    Kharoshthi,
    OldSouthArabian,
    OldNorthArabian,
    Manichaean,
    Avestan,
    InscriptionalParthian,
    InscriptionalPahlavi,
    PsalterPahlavi,
    OldTurkic,
    OldHungarian,
    HanifiRohingya,
    RumiNumeralSymbols,
    Yezidi,
    OldSogdian,
    Sogdian,
    Chorasmian,
    Elymaic,
    Brahmi,
    Kaithi,
    SoraSompeng,
    Chakma,
    Mahajani,
    Sharada,
    SinhalaArchaicNumbers,
    Khojki,
    Multani,
    Khudawadi,
    Grantha,
    Newa,
    Tirhuta,
    Siddham,
    Modi,
    MongolianSupplement,
    Takri,
    Ahom,
    Dogra,
    WarangCiti,
    DivesAkuru,
    Nandinagari,
    ZanabazarSquare,
    Soyombo,
    PauCinHau,
    Bhaiksuki,
    Marchen,
    MasaramGondi,
    GunjalaGondi,
    Makasar,
    LisuSupplement,
    TamilSupplement,
    Cuneiform,
    CuneiformNumbersAndPunctuation,
    EarlyDynasticCuneiform,
    EgyptianHieroglyphs,
    EgyptianHieroglyphFormatControls,
    AnatolianHieroglyphs,
    BamumSupplement,
    Mro,
    BassaVah,
    PahawhHmong,
    Medefaidrin,
    Miao,
    IdeographicSymbolsAndPunctuation,
    Tangut,
    TangutComponents,
    KhitanSmallScript,
    TangutSupplement,
    KanaSupplement,
    KanaExtendedA,
    SmallKanaExtension,
    Nushu,
    Duployan,
    ShorthandFormatControls,
    ByzantineMusicalSymbols,
    MusicalSymbols,
    AncientGreekMusicalNotation,
    MayanNumerals,
    TaiXuanJingSymbols,
    CountingRodNumerals,
    MathematicalAlphanumericSymbols,
    SuttonSignWriting,
    GlagoliticSupplement,
    NyiakengPuachueHmong,
    Wancho,
    MendeKikakui,
    Adlam,
    IndicSiyaqNumbers,
    OttomanSiyaqNumbers,
    ArabicMathematicalAlphabeticSymbols,
    MahjongTiles,
    DominoTiles,
    PlayingCards,
    EnclosedAlphanumericSupplement,
    EnclosedIdeographicSupplement,
    MiscellaneousSymbolsAndPictographs,
    Emoticons,
    OrnamentalDingbats,
    TransportAndMapSymbols,
    AlchemicalSymbols,
    GeometricShapesExtended,
    SupplementalArrowsC,
    SupplementalSymbolsAndPictographs,
    ChessSymbols,
    SymbolsAndPictographsExtendedA,
    SymbolsforLegacyComputing,
    CJKUnifiedIdeographsExtensionB,
    CJKUnifiedIdeographsExtensionC,
    CJKUnifiedIdeographsExtensionD,
    CJKUnifiedIdeographsExtensionE,
    CJKUnifiedIdeographsExtensionF,
    CJKCompatibilityIdeographsSupplement,
    CJKUnifiedIdeographsExtensionG,
    Tags,
    VariationSelectorsSupplement,
    SupplementaryPrivateUseAreaA,
    SupplementaryPrivateUseAreaB,
  }

  public class UnicodeBlockDef
  {
    public uint From;
    public uint To;
    public string Name;
  }

  public class UnicodeBlockSpan
  {
    public UnicodeBlock Block;
    public string Text;
  }

  public static class UnicodeUtils
  {

    public static UnicodeBlockSpan[] SplitToScripts(this string str)
    {
      var spans = new List<UnicodeBlockSpan>();
      UnicodeBlock lastBlock = 0;
      StringBuilder sb = new StringBuilder();
      string val;
      for (int i = 0; i < str.Length; i += Char.IsSurrogatePair(str, i) ? 2 : 1)
      {
        int code = (int)Char.ConvertToUtf32(str, i);
        var unicodeBlock = GetUnicodeBlock(code);
        if (unicodeBlock != lastBlock)
        {
          val = sb.ToString();
          if (!String.IsNullOrEmpty(val))
          {
            var span = new UnicodeBlockSpan { Block = lastBlock, Text = val };
            spans.Add(span);
            sb.Clear();
          }
        }
        var s = Char.ConvertFromUtf32(code);
        sb.Append(s);
      }
      val = sb.ToString();
      if (!String.IsNullOrEmpty(val))
      {
        var span = new UnicodeBlockSpan { Block = lastBlock, Text = val };
        spans.Add(span);
      }
      return spans.ToArray();
    }

    public static UnicodeBlock GetUnicodeBlock(char ch)
    {
      int code = (int)ch;
      return GetUnicodeBlock(code);
    }

    public static UnicodeBlock GetUnicodeBlock(int code)
    {
      return UnicodeBlockDefinitions.FirstOrDefault(item => item.Value.From <= code && item.Value.To >= code).Key;
    }




    public static Dictionary<UnicodeBlock, UnicodeBlockDef> UnicodeBlockDefinitions = new Dictionary<UnicodeBlock, UnicodeBlockDef>
    {
      { UnicodeBlock.BasicLatin, new UnicodeBlockDef{ From=0x0000, To=0x007F, Name="Basic Latin"} },
      { UnicodeBlock.Latin1Supplement, new UnicodeBlockDef{ From=0x0080, To=0x00FF, Name="Latin-1 Supplement"} },
      { UnicodeBlock.LatinExtendedA, new UnicodeBlockDef{ From=0x0100, To=0x017F, Name="Latin Extended-A"} },
      { UnicodeBlock.LatinExtendedB, new UnicodeBlockDef{ From=0x0180, To=0x024F, Name="Latin Extended-B"} },
      { UnicodeBlock.IPAExtensions, new UnicodeBlockDef{ From=0x0250, To=0x02AF, Name="IPA Extensions"} },
      { UnicodeBlock.SpacingModifierLetters, new UnicodeBlockDef{ From=0x02B0, To=0x02FF, Name="Spacing Modifier Letters"} },
      { UnicodeBlock.CombiningDiacriticalMarks, new UnicodeBlockDef{ From=0x0300, To=0x036F, Name="Combining Diacritical Marks"} },
      { UnicodeBlock.GreekAndCoptic, new UnicodeBlockDef{ From=0x0370, To=0x03FF, Name="Greek and Coptic"} },
      { UnicodeBlock.Cyrillic, new UnicodeBlockDef{ From=0x0400, To=0x04FF, Name="Cyrillic"} },
      { UnicodeBlock.CyrillicSupplement, new UnicodeBlockDef{ From=0x0500, To=0x052F, Name="Cyrillic Supplement"} },
      { UnicodeBlock.Armenian, new UnicodeBlockDef{ From=0x0530, To=0x058F, Name="Armenian"} },
      { UnicodeBlock.Hebrew, new UnicodeBlockDef{ From=0x0590, To=0x05FF, Name="Hebrew"} },
      { UnicodeBlock.Arabic, new UnicodeBlockDef{ From=0x0600, To=0x06FF, Name="Arabic"} },
      { UnicodeBlock.Syriac, new UnicodeBlockDef{ From=0x0700, To=0x074F, Name="Syriac"} },
      { UnicodeBlock.ArabicSupplement, new UnicodeBlockDef{ From=0x0750, To=0x077F, Name="Arabic Supplement"} },
      { UnicodeBlock.Thaana, new UnicodeBlockDef{ From=0x0780, To=0x07BF, Name="Thaana"} },
      { UnicodeBlock.NKo, new UnicodeBlockDef{ From=0x07C0, To=0x07FF, Name="NKo"} },
      { UnicodeBlock.Samaritan, new UnicodeBlockDef{ From=0x0800, To=0x083F, Name="Samaritan"} },
      { UnicodeBlock.Mandaic, new UnicodeBlockDef{ From=0x0840, To=0x085F, Name="Mandaic"} },
      { UnicodeBlock.SyriacSupplement, new UnicodeBlockDef{ From=0x0860, To=0x086F, Name="Syriac Supplement"} },
      { UnicodeBlock.ArabicExtendedA, new UnicodeBlockDef{ From=0x08A0, To=0x08FF, Name="Arabic Extended-A"} },
      { UnicodeBlock.Devanagari, new UnicodeBlockDef{ From=0x0900, To=0x097F, Name="Devanagari"} },
      { UnicodeBlock.Bengali, new UnicodeBlockDef{ From=0x0980, To=0x09FF, Name="Bengali"} },
      { UnicodeBlock.Gurmukhi, new UnicodeBlockDef{ From=0x0A00, To=0x0A7F, Name="Gurmukhi"} },
      { UnicodeBlock.Gujarati, new UnicodeBlockDef{ From=0x0A80, To=0x0AFF, Name="Gujarati"} },
      { UnicodeBlock.Oriya, new UnicodeBlockDef{ From=0x0B00, To=0x0B7F, Name="Oriya"} },
      { UnicodeBlock.Tamil, new UnicodeBlockDef{ From=0x0B80, To=0x0BFF, Name="Tamil"} },
      { UnicodeBlock.Telugu, new UnicodeBlockDef{ From=0x0C00, To=0x0C7F, Name="Telugu"} },
      { UnicodeBlock.Kannada, new UnicodeBlockDef{ From=0x0C80, To=0x0CFF, Name="Kannada"} },
      { UnicodeBlock.Malayalam, new UnicodeBlockDef{ From=0x0D00, To=0x0D7F, Name="Malayalam"} },
      { UnicodeBlock.Sinhala, new UnicodeBlockDef{ From=0x0D80, To=0x0DFF, Name="Sinhala"} },
      { UnicodeBlock.Thai, new UnicodeBlockDef{ From=0x0E00, To=0x0E7F, Name="Thai"} },
      { UnicodeBlock.Lao, new UnicodeBlockDef{ From=0x0E80, To=0x0EFF, Name="Lao"} },
      { UnicodeBlock.Tibetan, new UnicodeBlockDef{ From=0x0F00, To=0x0FFF, Name="Tibetan"} },
      { UnicodeBlock.Myanmar, new UnicodeBlockDef{ From=0x1000, To=0x109F, Name="Myanmar"} },
      { UnicodeBlock.Georgian, new UnicodeBlockDef{ From=0x10A0, To=0x10FF, Name="Georgian"} },
      { UnicodeBlock.HangulJamo, new UnicodeBlockDef{ From=0x1100, To=0x11FF, Name="Hangul Jamo"} },
      { UnicodeBlock.Ethiopic, new UnicodeBlockDef{ From=0x1200, To=0x137F, Name="Ethiopic"} },
      { UnicodeBlock.EthiopicSupplement, new UnicodeBlockDef{ From=0x1380, To=0x139F, Name="Ethiopic Supplement"} },
      { UnicodeBlock.Cherokee, new UnicodeBlockDef{ From=0x13A0, To=0x13FF, Name="Cherokee"} },
      { UnicodeBlock.UnifiedCanadianAboriginalSyllabics, new UnicodeBlockDef{ From=0x1400, To=0x167F, Name="Unified Canadian Aboriginal Syllabics"} },
      { UnicodeBlock.Ogham, new UnicodeBlockDef{ From=0x1680, To=0x169F, Name="Ogham"} },
      { UnicodeBlock.Runic, new UnicodeBlockDef{ From=0x16A0, To=0x16FF, Name="Runic"} },
      { UnicodeBlock.Tagalog, new UnicodeBlockDef{ From=0x1700, To=0x171F, Name="Tagalog"} },
      { UnicodeBlock.Hanunoo, new UnicodeBlockDef{ From=0x1720, To=0x173F, Name="Hanunoo"} },
      { UnicodeBlock.Buhid, new UnicodeBlockDef{ From=0x1740, To=0x175F, Name="Buhid"} },
      { UnicodeBlock.Tagbanwa, new UnicodeBlockDef{ From=0x1760, To=0x177F, Name="Tagbanwa"} },
      { UnicodeBlock.Khmer, new UnicodeBlockDef{ From=0x1780, To=0x17FF, Name="Khmer"} },
      { UnicodeBlock.Mongolian, new UnicodeBlockDef{ From=0x1800, To=0x18AF, Name="Mongolian"} },
      { UnicodeBlock.UnifiedCanadianAboriginalSyllabicsExtended, new UnicodeBlockDef{ From=0x18B0, To=0x18FF, Name="Unified Canadian Aboriginal Syllabics Extended"} },
      { UnicodeBlock.Limbu, new UnicodeBlockDef{ From=0x1900, To=0x194F, Name="Limbu"} },
      { UnicodeBlock.TaiLe, new UnicodeBlockDef{ From=0x1950, To=0x197F, Name="Tai Le"} },
      { UnicodeBlock.NewTaiLue, new UnicodeBlockDef{ From=0x1980, To=0x19DF, Name="New Tai Lue"} },
      { UnicodeBlock.KhmerSymbols, new UnicodeBlockDef{ From=0x19E0, To=0x19FF, Name="Khmer Symbols"} },
      { UnicodeBlock.Buginese, new UnicodeBlockDef{ From=0x1A00, To=0x1A1F, Name="Buginese"} },
      { UnicodeBlock.TaiTham, new UnicodeBlockDef{ From=0x1A20, To=0x1AAF, Name="Tai Tham"} },
      { UnicodeBlock.CombiningDiacriticalMarksExtended, new UnicodeBlockDef{ From=0x1AB0, To=0x1AFF, Name="Combining Diacritical Marks Extended"} },
      { UnicodeBlock.Balinese, new UnicodeBlockDef{ From=0x1B00, To=0x1B7F, Name="Balinese"} },
      { UnicodeBlock.Sundanese, new UnicodeBlockDef{ From=0x1B80, To=0x1BBF, Name="Sundanese"} },
      { UnicodeBlock.Batak, new UnicodeBlockDef{ From=0x1BC0, To=0x1BFF, Name="Batak"} },
      { UnicodeBlock.Lepcha, new UnicodeBlockDef{ From=0x1C00, To=0x1C4F, Name="Lepcha"} },
      { UnicodeBlock.OlChiki, new UnicodeBlockDef{ From=0x1C50, To=0x1C7F, Name="Ol Chiki"} },
      { UnicodeBlock.CyrillicExtendedC, new UnicodeBlockDef{ From=0x1C80, To=0x1C8F, Name="Cyrillic Extended-C"} },
      { UnicodeBlock.GeorgianExtended, new UnicodeBlockDef{ From=0x1C90, To=0x1CBF, Name="Georgian Extended"} },
      { UnicodeBlock.SundaneseSupplement, new UnicodeBlockDef{ From=0x1CC0, To=0x1CCF, Name="Sundanese Supplement"} },
      { UnicodeBlock.VedicExtensions, new UnicodeBlockDef{ From=0x1CD0, To=0x1CFF, Name="Vedic Extensions"} },
      { UnicodeBlock.PhoneticExtensions, new UnicodeBlockDef{ From=0x1D00, To=0x1D7F, Name="Phonetic Extensions"} },
      { UnicodeBlock.PhoneticExtensionsSupplement, new UnicodeBlockDef{ From=0x1D80, To=0x1DBF, Name="Phonetic Extensions Supplement"} },
      { UnicodeBlock.CombiningDiacriticalMarksSupplement, new UnicodeBlockDef{ From=0x1DC0, To=0x1DFF, Name="Combining Diacritical Marks Supplement"} },
      { UnicodeBlock.LatinExtendedAdditional, new UnicodeBlockDef{ From=0x1E00, To=0x1EFF, Name="Latin Extended Additional"} },
      { UnicodeBlock.GreekExtended, new UnicodeBlockDef{ From=0x1F00, To=0x1FFF, Name="Greek Extended"} },
      { UnicodeBlock.GeneralPunctuation, new UnicodeBlockDef{ From=0x2000, To=0x206F, Name="General Punctuation"} },
      { UnicodeBlock.SuperscriptsAndSubscripts, new UnicodeBlockDef{ From=0x2070, To=0x209F, Name="Superscripts and Subscripts"} },
      { UnicodeBlock.CurrencySymbols, new UnicodeBlockDef{ From=0x20A0, To=0x20CF, Name="Currency Symbols"} },
      { UnicodeBlock.CombiningDiacriticalMarksforSymbols, new UnicodeBlockDef{ From=0x20D0, To=0x20FF, Name="Combining Diacritical Marks for Symbols"} },
      { UnicodeBlock.LetterlikeSymbols, new UnicodeBlockDef{ From=0x2100, To=0x214F, Name="Letterlike Symbols"} },
      { UnicodeBlock.NumberForms, new UnicodeBlockDef{ From=0x2150, To=0x218F, Name="Number Forms"} },
      { UnicodeBlock.Arrows, new UnicodeBlockDef{ From=0x2190, To=0x21FF, Name="Arrows"} },
      { UnicodeBlock.MathematicalOperators, new UnicodeBlockDef{ From=0x2200, To=0x22FF, Name="Mathematical Operators"} },
      { UnicodeBlock.MiscellaneousTechnical, new UnicodeBlockDef{ From=0x2300, To=0x23FF, Name="Miscellaneous Technical"} },
      { UnicodeBlock.ControlPictures, new UnicodeBlockDef{ From=0x2400, To=0x243F, Name="Control Pictures"} },
      { UnicodeBlock.OpticalCharacterRecognition, new UnicodeBlockDef{ From=0x2440, To=0x245F, Name="Optical Character Recognition"} },
      { UnicodeBlock.EnclosedAlphanumerics, new UnicodeBlockDef{ From=0x2460, To=0x24FF, Name="Enclosed Alphanumerics"} },
      { UnicodeBlock.BoxDrawing, new UnicodeBlockDef{ From=0x2500, To=0x257F, Name="Box Drawing"} },
      { UnicodeBlock.BlockElements, new UnicodeBlockDef{ From=0x2580, To=0x259F, Name="Block Elements"} },
      { UnicodeBlock.GeometricShapes, new UnicodeBlockDef{ From=0x25A0, To=0x25FF, Name="Geometric Shapes"} },
      { UnicodeBlock.MiscellaneousSymbols, new UnicodeBlockDef{ From=0x2600, To=0x26FF, Name="Miscellaneous Symbols"} },
      { UnicodeBlock.Dingbats, new UnicodeBlockDef{ From=0x2700, To=0x27BF, Name="Dingbats"} },
      { UnicodeBlock.MiscellaneousMathematicalSymbolsA, new UnicodeBlockDef{ From=0x27C0, To=0x27EF, Name="Miscellaneous Mathematical Symbols-A"} },
      { UnicodeBlock.SupplementalArrowsA, new UnicodeBlockDef{ From=0x27F0, To=0x27FF, Name="Supplemental Arrows-A"} },
      { UnicodeBlock.BraillePatterns, new UnicodeBlockDef{ From=0x2800, To=0x28FF, Name="Braille Patterns"} },
      { UnicodeBlock.SupplementalArrowsB, new UnicodeBlockDef{ From=0x2900, To=0x297F, Name="Supplemental Arrows-B"} },
      { UnicodeBlock.MiscellaneousMathematicalSymbolsB, new UnicodeBlockDef{ From=0x2980, To=0x29FF, Name="Miscellaneous Mathematical Symbols-B"} },
      { UnicodeBlock.SupplementalMathematicalOperators, new UnicodeBlockDef{ From=0x2A00, To=0x2AFF, Name="Supplemental Mathematical Operators"} },
      { UnicodeBlock.MiscellaneousSymbolsAndArrows, new UnicodeBlockDef{ From=0x2B00, To=0x2BFF, Name="Miscellaneous Symbols and Arrows"} },
      { UnicodeBlock.Glagolitic, new UnicodeBlockDef{ From=0x2C00, To=0x2C5F, Name="Glagolitic"} },
      { UnicodeBlock.LatinExtendedC, new UnicodeBlockDef{ From=0x2C60, To=0x2C7F, Name="Latin Extended-C"} },
      { UnicodeBlock.Coptic, new UnicodeBlockDef{ From=0x2C80, To=0x2CFF, Name="Coptic"} },
      { UnicodeBlock.GeorgianSupplement, new UnicodeBlockDef{ From=0x2D00, To=0x2D2F, Name="Georgian Supplement"} },
      { UnicodeBlock.Tifinagh, new UnicodeBlockDef{ From=0x2D30, To=0x2D7F, Name="Tifinagh"} },
      { UnicodeBlock.EthiopicExtended, new UnicodeBlockDef{ From=0x2D80, To=0x2DDF, Name="Ethiopic Extended"} },
      { UnicodeBlock.CyrillicExtendedA, new UnicodeBlockDef{ From=0x2DE0, To=0x2DFF, Name="Cyrillic Extended-A"} },
      { UnicodeBlock.SupplementalPunctuation, new UnicodeBlockDef{ From=0x2E00, To=0x2E7F, Name="Supplemental Punctuation"} },
      { UnicodeBlock.CJKRadicalsSupplement, new UnicodeBlockDef{ From=0x2E80, To=0x2EFF, Name="CJK Radicals Supplement"} },
      { UnicodeBlock.KangxiRadicals, new UnicodeBlockDef{ From=0x2F00, To=0x2FDF, Name="Kangxi Radicals"} },
      { UnicodeBlock.IdeographicDescriptionCharacters, new UnicodeBlockDef{ From=0x2FF0, To=0x2FFF, Name="Ideographic Description Characters"} },
      { UnicodeBlock.CJKSymbolsAndPunctuation, new UnicodeBlockDef{ From=0x3000, To=0x303F, Name="CJK Symbols and Punctuation"} },
      { UnicodeBlock.Hiragana, new UnicodeBlockDef{ From=0x3040, To=0x309F, Name="Hiragana"} },
      { UnicodeBlock.Katakana, new UnicodeBlockDef{ From=0x30A0, To=0x30FF, Name="Katakana"} },
      { UnicodeBlock.Bopomofo, new UnicodeBlockDef{ From=0x3100, To=0x312F, Name="Bopomofo"} },
      { UnicodeBlock.HangulCompatibilityJamo, new UnicodeBlockDef{ From=0x3130, To=0x318F, Name="Hangul Compatibility Jamo"} },
      { UnicodeBlock.Kanbun, new UnicodeBlockDef{ From=0x3190, To=0x319F, Name="Kanbun"} },
      { UnicodeBlock.BopomofoExtended, new UnicodeBlockDef{ From=0x31A0, To=0x31BF, Name="Bopomofo Extended"} },
      { UnicodeBlock.CJKStrokes, new UnicodeBlockDef{ From=0x31C0, To=0x31EF, Name="CJK Strokes"} },
      { UnicodeBlock.KatakanaPhoneticExtensions, new UnicodeBlockDef{ From=0x31F0, To=0x31FF, Name="Katakana Phonetic Extensions"} },
      { UnicodeBlock.EnclosedCJKLettersAndMonths, new UnicodeBlockDef{ From=0x3200, To=0x32FF, Name="Enclosed CJK Letters and Months"} },
      { UnicodeBlock.CJKCompatibility, new UnicodeBlockDef{ From=0x3300, To=0x33FF, Name="CJK Compatibility"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionA, new UnicodeBlockDef{ From=0x3400, To=0x4DBF, Name="CJK Unified Ideographs Extension A"} },
      { UnicodeBlock.YijingHexagramSymbols, new UnicodeBlockDef{ From=0x4DC0, To=0x4DFF, Name="Yijing Hexagram Symbols"} },
      { UnicodeBlock.CJKUnifiedIdeographs, new UnicodeBlockDef{ From=0x4E00, To=0x9FFF, Name="CJK Unified Ideographs"} },
      { UnicodeBlock.YiSyllables, new UnicodeBlockDef{ From=0xA000, To=0xA48F, Name="Yi Syllables"} },
      { UnicodeBlock.YiRadicals, new UnicodeBlockDef{ From=0xA490, To=0xA4CF, Name="Yi Radicals"} },
      { UnicodeBlock.Lisu, new UnicodeBlockDef{ From=0xA4D0, To=0xA4FF, Name="Lisu"} },
      { UnicodeBlock.Vai, new UnicodeBlockDef{ From=0xA500, To=0xA63F, Name="Vai"} },
      { UnicodeBlock.CyrillicExtendedB, new UnicodeBlockDef{ From=0xA640, To=0xA69F, Name="Cyrillic Extended-B"} },
      { UnicodeBlock.Bamum, new UnicodeBlockDef{ From=0xA6A0, To=0xA6FF, Name="Bamum"} },
      { UnicodeBlock.ModifierToneLetters, new UnicodeBlockDef{ From=0xA700, To=0xA71F, Name="Modifier Tone Letters"} },
      { UnicodeBlock.LatinExtendedD, new UnicodeBlockDef{ From=0xA720, To=0xA7FF, Name="Latin Extended-D"} },
      { UnicodeBlock.SylotiNagri, new UnicodeBlockDef{ From=0xA800, To=0xA82F, Name="Syloti Nagri"} },
      { UnicodeBlock.CommonIndicNumberForms, new UnicodeBlockDef{ From=0xA830, To=0xA83F, Name="Common Indic Number Forms"} },
      { UnicodeBlock.Phagspa, new UnicodeBlockDef{ From=0xA840, To=0xA87F, Name="Phags-pa"} },
      { UnicodeBlock.Saurashtra, new UnicodeBlockDef{ From=0xA880, To=0xA8DF, Name="Saurashtra"} },
      { UnicodeBlock.DevanagariExtended, new UnicodeBlockDef{ From=0xA8E0, To=0xA8FF, Name="Devanagari Extended"} },
      { UnicodeBlock.KayahLi, new UnicodeBlockDef{ From=0xA900, To=0xA92F, Name="Kayah Li"} },
      { UnicodeBlock.Rejang, new UnicodeBlockDef{ From=0xA930, To=0xA95F, Name="Rejang"} },
      { UnicodeBlock.HangulJamoExtendedA, new UnicodeBlockDef{ From=0xA960, To=0xA97F, Name="Hangul Jamo Extended-A"} },
      { UnicodeBlock.Javanese, new UnicodeBlockDef{ From=0xA980, To=0xA9DF, Name="Javanese"} },
      { UnicodeBlock.MyanmarExtendedB, new UnicodeBlockDef{ From=0xA9E0, To=0xA9FF, Name="Myanmar Extended-B"} },
      { UnicodeBlock.Cham, new UnicodeBlockDef{ From=0xAA00, To=0xAA5F, Name="Cham"} },
      { UnicodeBlock.MyanmarExtendedA, new UnicodeBlockDef{ From=0xAA60, To=0xAA7F, Name="Myanmar Extended-A"} },
      { UnicodeBlock.TaiViet, new UnicodeBlockDef{ From=0xAA80, To=0xAADF, Name="Tai Viet"} },
      { UnicodeBlock.MeeteiMayekExtensions, new UnicodeBlockDef{ From=0xAAE0, To=0xAAFF, Name="Meetei Mayek Extensions"} },
      { UnicodeBlock.EthiopicExtendedA, new UnicodeBlockDef{ From=0xAB00, To=0xAB2F, Name="Ethiopic Extended-A"} },
      { UnicodeBlock.LatinExtendedE, new UnicodeBlockDef{ From=0xAB30, To=0xAB6F, Name="Latin Extended-E"} },
      { UnicodeBlock.CherokeeSupplement, new UnicodeBlockDef{ From=0xAB70, To=0xABBF, Name="Cherokee Supplement"} },
      { UnicodeBlock.MeeteiMayek, new UnicodeBlockDef{ From=0xABC0, To=0xABFF, Name="Meetei Mayek"} },
      { UnicodeBlock.HangulSyllables, new UnicodeBlockDef{ From=0xAC00, To=0xD7AF, Name="Hangul Syllables"} },
      { UnicodeBlock.HangulJamoExtendedB, new UnicodeBlockDef{ From=0xD7B0, To=0xD7FF, Name="Hangul Jamo Extended-B"} },
      { UnicodeBlock.HighSurrogates, new UnicodeBlockDef{ From=0xD800, To=0xDB7F, Name="High Surrogates"} },
      { UnicodeBlock.HighPrivateUseSurrogates, new UnicodeBlockDef{ From=0xDB80, To=0xDBFF, Name="High Private Use Surrogates"} },
      { UnicodeBlock.LowSurrogates, new UnicodeBlockDef{ From=0xDC00, To=0xDFFF, Name="Low Surrogates"} },
      { UnicodeBlock.PrivateUseArea, new UnicodeBlockDef{ From=0xE000, To=0xF8FF, Name="Private Use Area"} },
      { UnicodeBlock.CJKCompatibilityIdeographs, new UnicodeBlockDef{ From=0xF900, To=0xFAFF, Name="CJK Compatibility Ideographs"} },
      { UnicodeBlock.AlphabeticPresentationForms, new UnicodeBlockDef{ From=0xFB00, To=0xFB4F, Name="Alphabetic Presentation Forms"} },
      { UnicodeBlock.ArabicPresentationFormsA, new UnicodeBlockDef{ From=0xFB50, To=0xFDFF, Name="Arabic Presentation Forms-A"} },
      { UnicodeBlock.VariationSelectors, new UnicodeBlockDef{ From=0xFE00, To=0xFE0F, Name="Variation Selectors"} },
      { UnicodeBlock.VerticalForms, new UnicodeBlockDef{ From=0xFE10, To=0xFE1F, Name="Vertical Forms"} },
      { UnicodeBlock.CombiningHalfMarks, new UnicodeBlockDef{ From=0xFE20, To=0xFE2F, Name="Combining Half Marks"} },
      { UnicodeBlock.CJKCompatibilityForms, new UnicodeBlockDef{ From=0xFE30, To=0xFE4F, Name="CJK Compatibility Forms"} },
      { UnicodeBlock.SmallFormVariants, new UnicodeBlockDef{ From=0xFE50, To=0xFE6F, Name="Small Form Variants"} },
      { UnicodeBlock.ArabicPresentationFormsB, new UnicodeBlockDef{ From=0xFE70, To=0xFEFF, Name="Arabic Presentation Forms-B"} },
      { UnicodeBlock.HalfwidthAndFullwidthForms, new UnicodeBlockDef{ From=0xFF00, To=0xFFEF, Name="Halfwidth and Fullwidth Forms"} },
      { UnicodeBlock.Specials, new UnicodeBlockDef{ From=0xFFF0, To=0xFFFF, Name="Specials"} },
      { UnicodeBlock.LinearBSyllabary, new UnicodeBlockDef{ From=0x10000, To=0x1007F, Name="Linear B Syllabary"} },
      { UnicodeBlock.LinearBIdeograms, new UnicodeBlockDef{ From=0x10080, To=0x100FF, Name="Linear B Ideograms"} },
      { UnicodeBlock.AegeanNumbers, new UnicodeBlockDef{ From=0x10100, To=0x1013F, Name="Aegean Numbers"} },
      { UnicodeBlock.AncientGreekNumbers, new UnicodeBlockDef{ From=0x10140, To=0x1018F, Name="Ancient Greek Numbers"} },
      { UnicodeBlock.AncientSymbols, new UnicodeBlockDef{ From=0x10190, To=0x101CF, Name="Ancient Symbols"} },
      { UnicodeBlock.PhaistosDisc, new UnicodeBlockDef{ From=0x101D0, To=0x101FF, Name="Phaistos Disc"} },
      { UnicodeBlock.Lycian, new UnicodeBlockDef{ From=0x10280, To=0x1029F, Name="Lycian"} },
      { UnicodeBlock.Carian, new UnicodeBlockDef{ From=0x102A0, To=0x102DF, Name="Carian"} },
      { UnicodeBlock.CopticEpactNumbers, new UnicodeBlockDef{ From=0x102E0, To=0x102FF, Name="Coptic Epact Numbers"} },
      { UnicodeBlock.OldItalic, new UnicodeBlockDef{ From=0x10300, To=0x1032F, Name="Old Italic"} },
      { UnicodeBlock.Gothic, new UnicodeBlockDef{ From=0x10330, To=0x1034F, Name="Gothic"} },
      { UnicodeBlock.OldPermic, new UnicodeBlockDef{ From=0x10350, To=0x1037F, Name="Old Permic"} },
      { UnicodeBlock.Ugaritic, new UnicodeBlockDef{ From=0x10380, To=0x1039F, Name="Ugaritic"} },
      { UnicodeBlock.OldPersian, new UnicodeBlockDef{ From=0x103A0, To=0x103DF, Name="Old Persian"} },
      { UnicodeBlock.Deseret, new UnicodeBlockDef{ From=0x10400, To=0x1044F, Name="Deseret"} },
      { UnicodeBlock.Shavian, new UnicodeBlockDef{ From=0x10450, To=0x1047F, Name="Shavian"} },
      { UnicodeBlock.Osmanya, new UnicodeBlockDef{ From=0x10480, To=0x104AF, Name="Osmanya"} },
      { UnicodeBlock.Osage, new UnicodeBlockDef{ From=0x104B0, To=0x104FF, Name="Osage"} },
      { UnicodeBlock.Elbasan, new UnicodeBlockDef{ From=0x10500, To=0x1052F, Name="Elbasan"} },
      { UnicodeBlock.CaucasianAlbanian, new UnicodeBlockDef{ From=0x10530, To=0x1056F, Name="Caucasian Albanian"} },
      { UnicodeBlock.LinearA, new UnicodeBlockDef{ From=0x10600, To=0x1077F, Name="Linear A"} },
      { UnicodeBlock.CypriotSyllabary, new UnicodeBlockDef{ From=0x10800, To=0x1083F, Name="Cypriot Syllabary"} },
      { UnicodeBlock.ImperialAramaic, new UnicodeBlockDef{ From=0x10840, To=0x1085F, Name="Imperial Aramaic"} },
      { UnicodeBlock.Palmyrene, new UnicodeBlockDef{ From=0x10860, To=0x1087F, Name="Palmyrene"} },
      { UnicodeBlock.Nabataean, new UnicodeBlockDef{ From=0x10880, To=0x108AF, Name="Nabataean"} },
      { UnicodeBlock.Hatran, new UnicodeBlockDef{ From=0x108E0, To=0x108FF, Name="Hatran"} },
      { UnicodeBlock.Phoenician, new UnicodeBlockDef{ From=0x10900, To=0x1091F, Name="Phoenician"} },
      { UnicodeBlock.Lydian, new UnicodeBlockDef{ From=0x10920, To=0x1093F, Name="Lydian"} },
      { UnicodeBlock.MeroiticHieroglyphs, new UnicodeBlockDef{ From=0x10980, To=0x1099F, Name="Meroitic Hieroglyphs"} },
      { UnicodeBlock.MeroiticCursive, new UnicodeBlockDef{ From=0x109A0, To=0x109FF, Name="Meroitic Cursive"} },
      { UnicodeBlock.Kharoshthi, new UnicodeBlockDef{ From=0x10A00, To=0x10A5F, Name="Kharoshthi"} },
      { UnicodeBlock.OldSouthArabian, new UnicodeBlockDef{ From=0x10A60, To=0x10A7F, Name="Old South Arabian"} },
      { UnicodeBlock.OldNorthArabian, new UnicodeBlockDef{ From=0x10A80, To=0x10A9F, Name="Old North Arabian"} },
      { UnicodeBlock.Manichaean, new UnicodeBlockDef{ From=0x10AC0, To=0x10AFF, Name="Manichaean"} },
      { UnicodeBlock.Avestan, new UnicodeBlockDef{ From=0x10B00, To=0x10B3F, Name="Avestan"} },
      { UnicodeBlock.InscriptionalParthian, new UnicodeBlockDef{ From=0x10B40, To=0x10B5F, Name="Inscriptional Parthian"} },
      { UnicodeBlock.InscriptionalPahlavi, new UnicodeBlockDef{ From=0x10B60, To=0x10B7F, Name="Inscriptional Pahlavi"} },
      { UnicodeBlock.PsalterPahlavi, new UnicodeBlockDef{ From=0x10B80, To=0x10BAF, Name="Psalter Pahlavi"} },
      { UnicodeBlock.OldTurkic, new UnicodeBlockDef{ From=0x10C00, To=0x10C4F, Name="Old Turkic"} },
      { UnicodeBlock.OldHungarian, new UnicodeBlockDef{ From=0x10C80, To=0x10CFF, Name="Old Hungarian"} },
      { UnicodeBlock.HanifiRohingya, new UnicodeBlockDef{ From=0x10D00, To=0x10D3F, Name="Hanifi Rohingya"} },
      { UnicodeBlock.RumiNumeralSymbols, new UnicodeBlockDef{ From=0x10E60, To=0x10E7F, Name="Rumi Numeral Symbols"} },
      { UnicodeBlock.Yezidi, new UnicodeBlockDef{ From=0x10E80, To=0x10EBF, Name="Yezidi"} },
      { UnicodeBlock.OldSogdian, new UnicodeBlockDef{ From=0x10F00, To=0x10F2F, Name="Old Sogdian"} },
      { UnicodeBlock.Sogdian, new UnicodeBlockDef{ From=0x10F30, To=0x10F6F, Name="Sogdian"} },
      { UnicodeBlock.Chorasmian, new UnicodeBlockDef{ From=0x10FB0, To=0x10FDF, Name="Chorasmian"} },
      { UnicodeBlock.Elymaic, new UnicodeBlockDef{ From=0x10FE0, To=0x10FFF, Name="Elymaic"} },
      { UnicodeBlock.Brahmi, new UnicodeBlockDef{ From=0x11000, To=0x1107F, Name="Brahmi"} },
      { UnicodeBlock.Kaithi, new UnicodeBlockDef{ From=0x11080, To=0x110CF, Name="Kaithi"} },
      { UnicodeBlock.SoraSompeng, new UnicodeBlockDef{ From=0x110D0, To=0x110FF, Name="Sora Sompeng"} },
      { UnicodeBlock.Chakma, new UnicodeBlockDef{ From=0x11100, To=0x1114F, Name="Chakma"} },
      { UnicodeBlock.Mahajani, new UnicodeBlockDef{ From=0x11150, To=0x1117F, Name="Mahajani"} },
      { UnicodeBlock.Sharada, new UnicodeBlockDef{ From=0x11180, To=0x111DF, Name="Sharada"} },
      { UnicodeBlock.SinhalaArchaicNumbers, new UnicodeBlockDef{ From=0x111E0, To=0x111FF, Name="Sinhala Archaic Numbers"} },
      { UnicodeBlock.Khojki, new UnicodeBlockDef{ From=0x11200, To=0x1124F, Name="Khojki"} },
      { UnicodeBlock.Multani, new UnicodeBlockDef{ From=0x11280, To=0x112AF, Name="Multani"} },
      { UnicodeBlock.Khudawadi, new UnicodeBlockDef{ From=0x112B0, To=0x112FF, Name="Khudawadi"} },
      { UnicodeBlock.Grantha, new UnicodeBlockDef{ From=0x11300, To=0x1137F, Name="Grantha"} },
      { UnicodeBlock.Newa, new UnicodeBlockDef{ From=0x11400, To=0x1147F, Name="Newa"} },
      { UnicodeBlock.Tirhuta, new UnicodeBlockDef{ From=0x11480, To=0x114DF, Name="Tirhuta"} },
      { UnicodeBlock.Siddham, new UnicodeBlockDef{ From=0x11580, To=0x115FF, Name="Siddham"} },
      { UnicodeBlock.Modi, new UnicodeBlockDef{ From=0x11600, To=0x1165F, Name="Modi"} },
      { UnicodeBlock.MongolianSupplement, new UnicodeBlockDef{ From=0x11660, To=0x1167F, Name="Mongolian Supplement"} },
      { UnicodeBlock.Takri, new UnicodeBlockDef{ From=0x11680, To=0x116CF, Name="Takri"} },
      { UnicodeBlock.Ahom, new UnicodeBlockDef{ From=0x11700, To=0x1173F, Name="Ahom"} },
      { UnicodeBlock.Dogra, new UnicodeBlockDef{ From=0x11800, To=0x1184F, Name="Dogra"} },
      { UnicodeBlock.WarangCiti, new UnicodeBlockDef{ From=0x118A0, To=0x118FF, Name="Warang Citi"} },
      { UnicodeBlock.DivesAkuru, new UnicodeBlockDef{ From=0x11900, To=0x1195F, Name="Dives Akuru"} },
      { UnicodeBlock.Nandinagari, new UnicodeBlockDef{ From=0x119A0, To=0x119FF, Name="Nandinagari"} },
      { UnicodeBlock.ZanabazarSquare, new UnicodeBlockDef{ From=0x11A00, To=0x11A4F, Name="Zanabazar Square"} },
      { UnicodeBlock.Soyombo, new UnicodeBlockDef{ From=0x11A50, To=0x11AAF, Name="Soyombo"} },
      { UnicodeBlock.PauCinHau, new UnicodeBlockDef{ From=0x11AC0, To=0x11AFF, Name="Pau Cin Hau"} },
      { UnicodeBlock.Bhaiksuki, new UnicodeBlockDef{ From=0x11C00, To=0x11C6F, Name="Bhaiksuki"} },
      { UnicodeBlock.Marchen, new UnicodeBlockDef{ From=0x11C70, To=0x11CBF, Name="Marchen"} },
      { UnicodeBlock.MasaramGondi, new UnicodeBlockDef{ From=0x11D00, To=0x11D5F, Name="Masaram Gondi"} },
      { UnicodeBlock.GunjalaGondi, new UnicodeBlockDef{ From=0x11D60, To=0x11DAF, Name="Gunjala Gondi"} },
      { UnicodeBlock.Makasar, new UnicodeBlockDef{ From=0x11EE0, To=0x11EFF, Name="Makasar"} },
      { UnicodeBlock.LisuSupplement, new UnicodeBlockDef{ From=0x11FB0, To=0x11FBF, Name="Lisu Supplement"} },
      { UnicodeBlock.TamilSupplement, new UnicodeBlockDef{ From=0x11FC0, To=0x11FFF, Name="Tamil Supplement"} },
      { UnicodeBlock.Cuneiform, new UnicodeBlockDef{ From=0x12000, To=0x123FF, Name="Cuneiform"} },
      { UnicodeBlock.CuneiformNumbersAndPunctuation, new UnicodeBlockDef{ From=0x12400, To=0x1247F, Name="Cuneiform Numbers and Punctuation"} },
      { UnicodeBlock.EarlyDynasticCuneiform, new UnicodeBlockDef{ From=0x12480, To=0x1254F, Name="Early Dynastic Cuneiform"} },
      { UnicodeBlock.EgyptianHieroglyphs, new UnicodeBlockDef{ From=0x13000, To=0x1342F, Name="Egyptian Hieroglyphs"} },
      { UnicodeBlock.EgyptianHieroglyphFormatControls, new UnicodeBlockDef{ From=0x13430, To=0x1343F, Name="Egyptian Hieroglyph Format Controls"} },
      { UnicodeBlock.AnatolianHieroglyphs, new UnicodeBlockDef{ From=0x14400, To=0x1467F, Name="Anatolian Hieroglyphs"} },
      { UnicodeBlock.BamumSupplement, new UnicodeBlockDef{ From=0x16800, To=0x16A3F, Name="Bamum Supplement"} },
      { UnicodeBlock.Mro, new UnicodeBlockDef{ From=0x16A40, To=0x16A6F, Name="Mro"} },
      { UnicodeBlock.BassaVah, new UnicodeBlockDef{ From=0x16AD0, To=0x16AFF, Name="Bassa Vah"} },
      { UnicodeBlock.PahawhHmong, new UnicodeBlockDef{ From=0x16B00, To=0x16B8F, Name="Pahawh Hmong"} },
      { UnicodeBlock.Medefaidrin, new UnicodeBlockDef{ From=0x16E40, To=0x16E9F, Name="Medefaidrin"} },
      { UnicodeBlock.Miao, new UnicodeBlockDef{ From=0x16F00, To=0x16F9F, Name="Miao"} },
      { UnicodeBlock.IdeographicSymbolsAndPunctuation, new UnicodeBlockDef{ From=0x16FE0, To=0x16FFF, Name="Ideographic Symbols and Punctuation"} },
      { UnicodeBlock.Tangut, new UnicodeBlockDef{ From=0x17000, To=0x187FF, Name="Tangut"} },
      { UnicodeBlock.TangutComponents, new UnicodeBlockDef{ From=0x18800, To=0x18AFF, Name="Tangut Components"} },
      { UnicodeBlock.KhitanSmallScript, new UnicodeBlockDef{ From=0x18B00, To=0x18CFF, Name="Khitan Small Script"} },
      { UnicodeBlock.TangutSupplement, new UnicodeBlockDef{ From=0x18D00, To=0x18D8F, Name="Tangut Supplement"} },
      { UnicodeBlock.KanaSupplement, new UnicodeBlockDef{ From=0x1B000, To=0x1B0FF, Name="Kana Supplement"} },
      { UnicodeBlock.KanaExtendedA, new UnicodeBlockDef{ From=0x1B100, To=0x1B12F, Name="Kana Extended-A"} },
      { UnicodeBlock.SmallKanaExtension, new UnicodeBlockDef{ From=0x1B130, To=0x1B16F, Name="Small Kana Extension"} },
      { UnicodeBlock.Nushu, new UnicodeBlockDef{ From=0x1B170, To=0x1B2FF, Name="Nushu"} },
      { UnicodeBlock.Duployan, new UnicodeBlockDef{ From=0x1BC00, To=0x1BC9F, Name="Duployan"} },
      { UnicodeBlock.ShorthandFormatControls, new UnicodeBlockDef{ From=0x1BCA0, To=0x1BCAF, Name="Shorthand Format Controls"} },
      { UnicodeBlock.ByzantineMusicalSymbols, new UnicodeBlockDef{ From=0x1D000, To=0x1D0FF, Name="Byzantine Musical Symbols"} },
      { UnicodeBlock.MusicalSymbols, new UnicodeBlockDef{ From=0x1D100, To=0x1D1FF, Name="Musical Symbols"} },
      { UnicodeBlock.AncientGreekMusicalNotation, new UnicodeBlockDef{ From=0x1D200, To=0x1D24F, Name="Ancient Greek Musical Notation"} },
      { UnicodeBlock.MayanNumerals, new UnicodeBlockDef{ From=0x1D2E0, To=0x1D2FF, Name="Mayan Numerals"} },
      { UnicodeBlock.TaiXuanJingSymbols, new UnicodeBlockDef{ From=0x1D300, To=0x1D35F, Name="Tai Xuan Jing Symbols"} },
      { UnicodeBlock.CountingRodNumerals, new UnicodeBlockDef{ From=0x1D360, To=0x1D37F, Name="Counting Rod Numerals"} },
      { UnicodeBlock.MathematicalAlphanumericSymbols, new UnicodeBlockDef{ From=0x1D400, To=0x1D7FF, Name="Mathematical Alphanumeric Symbols"} },
      { UnicodeBlock.SuttonSignWriting, new UnicodeBlockDef{ From=0x1D800, To=0x1DAAF, Name="Sutton SignWriting"} },
      { UnicodeBlock.GlagoliticSupplement, new UnicodeBlockDef{ From=0x1E000, To=0x1E02F, Name="Glagolitic Supplement"} },
      { UnicodeBlock.NyiakengPuachueHmong, new UnicodeBlockDef{ From=0x1E100, To=0x1E14F, Name="Nyiakeng Puachue Hmong"} },
      { UnicodeBlock.Wancho, new UnicodeBlockDef{ From=0x1E2C0, To=0x1E2FF, Name="Wancho"} },
      { UnicodeBlock.MendeKikakui, new UnicodeBlockDef{ From=0x1E800, To=0x1E8DF, Name="Mende Kikakui"} },
      { UnicodeBlock.Adlam, new UnicodeBlockDef{ From=0x1E900, To=0x1E95F, Name="Adlam"} },
      { UnicodeBlock.IndicSiyaqNumbers, new UnicodeBlockDef{ From=0x1EC70, To=0x1ECBF, Name="Indic Siyaq Numbers"} },
      { UnicodeBlock.OttomanSiyaqNumbers, new UnicodeBlockDef{ From=0x1ED00, To=0x1ED4F, Name="Ottoman Siyaq Numbers"} },
      { UnicodeBlock.ArabicMathematicalAlphabeticSymbols, new UnicodeBlockDef{ From=0x1EE00, To=0x1EEFF, Name="Arabic Mathematical Alphabetic Symbols"} },
      { UnicodeBlock.MahjongTiles, new UnicodeBlockDef{ From=0x1F000, To=0x1F02F, Name="Mahjong Tiles"} },
      { UnicodeBlock.DominoTiles, new UnicodeBlockDef{ From=0x1F030, To=0x1F09F, Name="Domino Tiles"} },
      { UnicodeBlock.PlayingCards, new UnicodeBlockDef{ From=0x1F0A0, To=0x1F0FF, Name="Playing Cards"} },
      { UnicodeBlock.EnclosedAlphanumericSupplement, new UnicodeBlockDef{ From=0x1F100, To=0x1F1FF, Name="Enclosed Alphanumeric Supplement"} },
      { UnicodeBlock.EnclosedIdeographicSupplement, new UnicodeBlockDef{ From=0x1F200, To=0x1F2FF, Name="Enclosed Ideographic Supplement"} },
      { UnicodeBlock.MiscellaneousSymbolsAndPictographs, new UnicodeBlockDef{ From=0x1F300, To=0x1F5FF, Name="Miscellaneous Symbols and Pictographs"} },
      { UnicodeBlock.Emoticons, new UnicodeBlockDef{ From=0x1F600, To=0x1F64F, Name="Emoticons"} },
      { UnicodeBlock.OrnamentalDingbats, new UnicodeBlockDef{ From=0x1F650, To=0x1F67F, Name="Ornamental Dingbats"} },
      { UnicodeBlock.TransportAndMapSymbols, new UnicodeBlockDef{ From=0x1F680, To=0x1F6FF, Name="Transport and Map Symbols"} },
      { UnicodeBlock.AlchemicalSymbols, new UnicodeBlockDef{ From=0x1F700, To=0x1F77F, Name="Alchemical Symbols"} },
      { UnicodeBlock.GeometricShapesExtended, new UnicodeBlockDef{ From=0x1F780, To=0x1F7FF, Name="Geometric Shapes Extended"} },
      { UnicodeBlock.SupplementalArrowsC, new UnicodeBlockDef{ From=0x1F800, To=0x1F8FF, Name="Supplemental Arrows-C"} },
      { UnicodeBlock.SupplementalSymbolsAndPictographs, new UnicodeBlockDef{ From=0x1F900, To=0x1F9FF, Name="Supplemental Symbols and Pictographs"} },
      { UnicodeBlock.ChessSymbols, new UnicodeBlockDef{ From=0x1FA00, To=0x1FA6F, Name="Chess Symbols"} },
      { UnicodeBlock.SymbolsAndPictographsExtendedA, new UnicodeBlockDef{ From=0x1FA70, To=0x1FAFF, Name="Symbols and Pictographs Extended-A"} },
      { UnicodeBlock.SymbolsforLegacyComputing, new UnicodeBlockDef{ From=0x1FB00, To=0x1FBFF, Name="Symbols for Legacy Computing"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionB, new UnicodeBlockDef{ From=0x20000, To=0x2A6DF, Name="CJK Unified Ideographs Extension B"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionC, new UnicodeBlockDef{ From=0x2A700, To=0x2B73F, Name="CJK Unified Ideographs Extension C"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionD, new UnicodeBlockDef{ From=0x2B740, To=0x2B81F, Name="CJK Unified Ideographs Extension D"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionE, new UnicodeBlockDef{ From=0x2B820, To=0x2CEAF, Name="CJK Unified Ideographs Extension E"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionF, new UnicodeBlockDef{ From=0x2CEB0, To=0x2EBEF, Name="CJK Unified Ideographs Extension F"} },
      { UnicodeBlock.CJKCompatibilityIdeographsSupplement, new UnicodeBlockDef{ From=0x2F800, To=0x2FA1F, Name="CJK Compatibility Ideographs Supplement"} },
      { UnicodeBlock.CJKUnifiedIdeographsExtensionG, new UnicodeBlockDef{ From=0x30000, To=0x3134F, Name="CJK Unified Ideographs Extension G"} },
      { UnicodeBlock.Tags, new UnicodeBlockDef{ From=0xE0000, To=0xE007F, Name="Tags"} },
      { UnicodeBlock.VariationSelectorsSupplement, new UnicodeBlockDef{ From=0xE0100, To=0xE01EF, Name="Variation Selectors Supplement"} },
      { UnicodeBlock.SupplementaryPrivateUseAreaA, new UnicodeBlockDef{ From=0xF0000, To=0xFFFFF, Name="Supplementary Private Use Area-A"} },
      { UnicodeBlock.SupplementaryPrivateUseAreaB, new UnicodeBlockDef{ From=0x100000, To=0x10FFFF, Name="Supplementary Private Use Area-B"} },
    };

  }

}
