//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.UnicodeBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.UnicodeBuild.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbr.
        /// </summary>
        public static string Abbr {
            get {
                return ResourceManager.GetString("Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctg.
        /// </summary>
        public static string Ctg {
            get {
                return ResourceManager.GetString("Ctg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key phrase.
        /// </summary>
        public static string KeyPhrase {
            get {
                return ResourceManager.GetString("KeyPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Writing System.
        /// </summary>
        public static string NewWritingSystem {
            get {
                return ResourceManager.GetString("NewWritingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Blocks.
        /// </summary>
        public static string UcdBlocks {
            get {
                return ResourceManager.GetString("UcdBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Ranges.
        /// </summary>
        public static string UcdRanges {
            get {
                return ResourceManager.GetString("UcdRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is used.
        /// </summary>
        public static string WritingSystemIsUsed {
            get {
                return ResourceManager.GetString("WritingSystemIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the writing system is a parent for some other systems or is referenced in Unicode Blocks or Unicode Ranges..
        /// </summary>
        public static string WritingSystemIsUsedTooltip {
            get {
                return ResourceManager.GetString("WritingSystemIsUsedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string WritingSystemKind {
            get {
                return ResourceManager.GetString("WritingSystemKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of writing system determines the nature of the characters in that system..
        /// </summary>
        public static string WritingSystemKindTooltip {
            get {
                return ResourceManager.GetString("WritingSystemKindTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WritingSystemName {
            get {
                return ResourceManager.GetString("WritingSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system name is a unique name starting with a letter and optionally containing letters, digits and spaces..
        /// </summary>
        public static string WritingSystemNameTooltip {
            get {
                return ResourceManager.GetString("WritingSystemNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent system.
        /// </summary>
        public static string WritingSystemParent {
            get {
                return ResourceManager.GetString("WritingSystemParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system parent is used to organize systems in a hierarchy..
        /// </summary>
        public static string WritingSystemParentTooltip {
            get {
                return ResourceManager.GetString("WritingSystemParentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Systems.
        /// </summary>
        public static string WritingSystems {
            get {
                return ResourceManager.GetString("WritingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WritingSystemType {
            get {
                return ResourceManager.GetString("WritingSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of writing system determines the primary purpose of the system..
        /// </summary>
        public static string WritingSystemTypeTooltip {
            get {
                return ResourceManager.GetString("WritingSystemTypeTooltip", resourceCulture);
            }
        }
    }
}
