//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.UnicodeBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.UnicodeBuild.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system {0} has not unique category key..
        /// </summary>
        public static string AmbiguousWritingSystemCategory {
            get {
                return ResourceManager.GetString("AmbiguousWritingSystemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system {0} has not unique (category, phrase) key..
        /// </summary>
        public static string AmbiguousWritingSystemCategoryOrPhrase {
            get {
                return ResourceManager.GetString("AmbiguousWritingSystemCategoryOrPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system {0} has not unique phrase key..
        /// </summary>
        public static string AmbiguousWritingSystemPhrase {
            get {
                return ResourceManager.GetString("AmbiguousWritingSystemPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply block mapping.
        /// </summary>
        public static string ApplyBlockMapping {
            get {
                return ResourceManager.GetString("ApplyBlockMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to apply block mapping from block ranges? (All current &quot;block&quot; fields w be updated.).
        /// </summary>
        public static string ApplyBlockMappingConfirm {
            get {
                return ResourceManager.GetString("ApplyBlockMappingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply code point mapping to Unicode blocks by checking block ranges..
        /// </summary>
        public static string ApplyBlockMappingTooltip {
            get {
                return ResourceManager.GetString("ApplyBlockMappingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply char names generation.
        /// </summary>
        public static string ApplyCharNamesGeneration {
            get {
                return ResourceManager.GetString("ApplyCharNamesGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char names generation completed. {0} code points named..
        /// </summary>
        public static string ApplyCharNamesGenerationCompleted {
            get {
                return ResourceManager.GetString("ApplyCharNamesGenerationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to generate char names for {0} code points? (Existing names will not be overwritten.).
        /// </summary>
        public static string ApplyCharNamesGenerationConfirm {
            get {
                return ResourceManager.GetString("ApplyCharNamesGenerationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply code point char names generation based on writing systems mapping..
        /// </summary>
        public static string ApplyCharNamesGenerationTooltip {
            get {
                return ResourceManager.GetString("ApplyCharNamesGenerationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply writing systems mapping.
        /// </summary>
        public static string ApplyWritingSystemsMappingFromFile {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsMappingFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply code point mapping to scripts from a text file. The first column in a line should contain the character code or code range, the second column should contain the name of the script. The columns should be separated by tabs. The &apos;#&apos; character is treated as the first character of a comment that extends to the end of the line..
        /// </summary>
        public static string ApplyWritingSystemsMappingFromFileTooltip {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsMappingFromFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply writing system recognition.
        /// </summary>
        public static string ApplyWritingSystemsRecognition {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try selecting specific columns to recognize writing systems of certain types..
        /// </summary>
        public static string ApplyWritingSystemsRecognitionAdvice {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsRecognitionAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system recognition completed. {0} code points mapped..
        /// </summary>
        public static string ApplyWritingSystemsRecognitionCompleted {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsRecognitionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to recognize writing systems for {0} code points? (Existing mapping will not be overwritten.).
        /// </summary>
        public static string ApplyWritingSystemsRecognitionConfirm {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsRecognitionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply code point mapping to writing systems based on category and key phrase..
        /// </summary>
        public static string ApplyWritingSystemsRecognitionTooltip {
            get {
                return ResourceManager.GetString("ApplyWritingSystemsRecognitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete writing system as it is used in other entities..
        /// </summary>
        public static string CannotDeleteWritingSystem {
            get {
                return ResourceManager.GetString("CannotDeleteWritingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code point {0} category is empty..
        /// </summary>
        public static string CodePointCategoryIsNull {
            get {
                return ResourceManager.GetString("CodePointCategoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code point {0} description is empty..
        /// </summary>
        public static string CodePointDescriptionIsNull {
            get {
                return ResourceManager.GetString("CodePointDescriptionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Points.
        /// </summary>
        public static string CodePoints {
            get {
                return ResourceManager.GetString("CodePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Unicode, a code point is a unique numerical value assigned to each character within the Unicode standard. These code points range from U+0000 to U+10FFFF, forming the Unicode codespace..
        /// </summary>
        public static string CodePointsTooltip {
            get {
                return ResourceManager.GetString("CodePointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv|Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string CsvFilesFilter {
            get {
                return ResourceManager.GetString("CsvFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty cells only.
        /// </summary>
        public static string EmptyCellsOnly {
            get {
                return ResourceManager.GetString("EmptyCellsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value must be greater than or equal to start value..
        /// </summary>
        public static string EndValueMustBeGreater {
            get {
                return ResourceManager.GetString("EndValueMustBeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in line{0}.
        /// </summary>
        public static string ErrorInLine {
            get {
                return ResourceManager.GetString("ErrorInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorOcurred {
            get {
                return ResourceManager.GetString("ErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill column.
        /// </summary>
        public static string FillColumn {
            get {
                return ResourceManager.GetString("FillColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill column {0}.
        /// </summary>
        public static string FillColumnTitle {
            get {
                return ResourceManager.GetString("FillColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill column with selected value.
        /// </summary>
        public static string FillColumnTooltip {
            get {
                return ResourceManager.GetString("FillColumnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all occurrences.
        /// </summary>
        public static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find first occurrence.
        /// </summary>
        public static string FindFirst {
            get {
                return ResourceManager.GetString("FindFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next occurrence.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find value.
        /// </summary>
        public static string FindValue {
            get {
                return ResourceManager.GetString("FindValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &quot;{0}&quot;.
        /// </summary>
        public static string FindValueTitle {
            get {
                return ResourceManager.GetString("FindValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code point format: {0}. Hexadecimal value expected..
        /// </summary>
        public static string InvalidCodePointFormat {
            get {
                return ResourceManager.GetString("InvalidCodePointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code range format: {0}. Two hexadecimal value expected separated with two dots. A single value is allowed..
        /// </summary>
        public static string InvalidCodeRangeFormat {
            get {
                return ResourceManager.GetString("InvalidCodeRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category &apos;{0}&apos; in writing system {1}..
        /// </summary>
        public static string InvalidWritingSystemCategory {
            get {
                return ResourceManager.GetString("InvalidWritingSystemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known numerals file.
        /// </summary>
        public static string KnownNumeralsFile {
            get {
                return ResourceManager.GetString("KnownNumeralsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with known numerals.
        /// </summary>
        public static string KnownNumeralsFileSelection {
            get {
                return ResourceManager.GetString("KnownNumeralsFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with known numerals contains two-column mapping. First column contains words or multiword phrases. Second column contains their values..
        /// </summary>
        public static string KnownNumeralsFileTooltip {
            get {
                return ResourceManager.GetString("KnownNumeralsFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known phrases file.
        /// </summary>
        public static string KnownPhrasesFile {
            get {
                return ResourceManager.GetString("KnownPhrasesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with known phrases.
        /// </summary>
        public static string KnownPhrasesFileSelection {
            get {
                return ResourceManager.GetString("KnownPhrasesFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with abbreviated words contains two-column mapping. First column contains words or multiword phrases. Second column contains their abbreviations. Third column contains tags for special phrases treatment..
        /// </summary>
        public static string KnownPhrasesFileTooltip {
            get {
                return ResourceManager.GetString("KnownPhrasesFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark unused writing system.
        /// </summary>
        public static string MarkUnusedWritingSystems {
            get {
                return ResourceManager.GetString("MarkUnusedWritingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select writing systems that are not used by any Unicode block or code point and has no children..
        /// </summary>
        public static string MarkUnusedWritingSystemsTooltip {
            get {
                return ResourceManager.GetString("MarkUnusedWritingSystemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name generator options.
        /// </summary>
        public static string NameGenOptions {
            get {
                return ResourceManager.GetString("NameGenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Writing System.
        /// </summary>
        public static string NewWritingSystem {
            get {
                return ResourceManager.GetString("NewWritingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code points selected..
        /// </summary>
        public static string NoCodePointsSelected {
            get {
                return ResourceManager.GetString("NoCodePointsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric words are converted to numbers..
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite non-empty cells.
        /// </summary>
        public static string OverwriteNonEmptyCells {
            get {
                return ResourceManager.GetString("OverwriteNonEmptyCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined names file.
        /// </summary>
        public static string PredefinedNamesFile {
            get {
                return ResourceManager.GetString("PredefinedNamesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with predefined names.
        /// </summary>
        public static string PredefinedNamesFileSelection {
            get {
                return ResourceManager.GetString("PredefinedNamesFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with predefined names contains two-column mapping. First column contains code points in hexadecimal form. Second column contains their predefined names (without &apos;\&apos;)..
        /// </summary>
        public static string PredefinedNamesFileTooltip {
            get {
                return ResourceManager.GetString("PredefinedNamesFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable words file.
        /// </summary>
        public static string RemovableWordsFile {
            get {
                return ResourceManager.GetString("RemovableWordsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with removable words.
        /// </summary>
        public static string RemovableWordsFileSelection {
            get {
                return ResourceManager.GetString("RemovableWordsFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with removable words contains two-column mapping. First column contains words or multiword phrases. Second column contains their numeric weights. Weight 0 means that a word is always removed. 1 that word is removed if it does is not a part of other known phrase..
        /// </summary>
        public static string RemovableWordsFileTooltip {
            get {
                return ResourceManager.GetString("RemovableWordsFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data (Ctrl-S).
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text.
        /// </summary>
        public static string SearchedText {
            get {
                return ResourceManager.GetString("SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select value.
        /// </summary>
        public static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string TextFilesFilter {
            get {
                return ResourceManager.GetString("TextFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long value.
        /// </summary>
        public static string TooLongValue {
            get {
                return ResourceManager.GetString("TooLongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Blocks.
        /// </summary>
        public static string UcdBlocks {
            get {
                return ResourceManager.GetString("UcdBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unicode block is one of contiguous ranges of numeric character codes (code points) of the Unicode character set that are defined by the Unicode Consortium for administrative and documentation purposes.
        ///One Unicode blocks can contain one or many Unicode ranges, which can be shown under each block..
        /// </summary>
        public static string UcdBlocksTooltip {
            get {
                return ResourceManager.GetString("UcdBlocksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode ranges.
        /// </summary>
        public static string UcdRanges {
            get {
                return ResourceManager.GetString("UcdRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unicode range is a contiguous range of numeric character codes (code points) of the Unicode character set that have the specific rules of use and translation. These rules are specified by writing systems.
        ///One Unicode range can contain one or many Unicode code points. 
        ///The &quot;Unicode Ranges&quot; tab contains a full list of ranges..
        /// </summary>
        public static string UcdRangesTooltip {
            get {
                return ResourceManager.GetString("UcdRangesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved data changes. Do you want to save them in the data base?.
        /// </summary>
        public static string UnsavedDataChanges {
            get {
                return ResourceManager.GetString("UnsavedDataChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating field {0}.
        /// </summary>
        public static string UpdatingField {
            get {
                return ResourceManager.GetString("UpdatingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing System {0} not found.
        /// </summary>
        public static string WritingSystemNotFound {
            get {
                return ResourceManager.GetString("WritingSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Systems.
        /// </summary>
        public static string WritingSystems {
            get {
                return ResourceManager.GetString("WritingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system comprises a set of symbols, called a script, as well as the rules by which the script represents a particular language..
        /// </summary>
        public static string WritingSystemsTooltip {
            get {
                return ResourceManager.GetString("WritingSystemsTooltip", resourceCulture);
            }
        }
    }
}
