//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.UnicodeBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UcdCategoryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UcdCategoryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.UnicodeBuild.Resources.UcdCategoryStrings", typeof(UcdCategoryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Control.
        /// </summary>
        internal static string Cc {
            get {
                return ResourceManager.GetString("Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Formating.
        /// </summary>
        internal static string Cf {
            get {
                return ResourceManager.GetString("Cf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Not assigned.
        /// </summary>
        internal static string Cn {
            get {
                return ResourceManager.GetString("Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Private Use.
        /// </summary>
        internal static string Co {
            get {
                return ResourceManager.GetString("Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Surrogate.
        /// </summary>
        internal static string Cs {
            get {
                return ResourceManager.GetString("Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Lowercase.
        /// </summary>
        internal static string Ll {
            get {
                return ResourceManager.GetString("Ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Modifier.
        /// </summary>
        internal static string Lm {
            get {
                return ResourceManager.GetString("Lm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Other.
        /// </summary>
        internal static string Lo {
            get {
                return ResourceManager.GetString("Lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Titlecase.
        /// </summary>
        internal static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Uppercase.
        /// </summary>
        internal static string Lu {
            get {
                return ResourceManager.GetString("Lu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Spacing Combining.
        /// </summary>
        internal static string Mc {
            get {
                return ResourceManager.GetString("Mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Enclosing.
        /// </summary>
        internal static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Non-spacing.
        /// </summary>
        internal static string Mn {
            get {
                return ResourceManager.GetString("Mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Decimal digit.
        /// </summary>
        internal static string Nd {
            get {
                return ResourceManager.GetString("Nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Letterlike.
        /// </summary>
        internal static string Nl {
            get {
                return ResourceManager.GetString("Nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Other.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Connector.
        /// </summary>
        internal static string Pc {
            get {
                return ResourceManager.GetString("Pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Dash.
        /// </summary>
        internal static string Pd {
            get {
                return ResourceManager.GetString("Pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Close.
        /// </summary>
        internal static string Pe {
            get {
                return ResourceManager.GetString("Pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Quote Close.
        /// </summary>
        internal static string Pf {
            get {
                return ResourceManager.GetString("Pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Quote Open.
        /// </summary>
        internal static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Other.
        /// </summary>
        internal static string Po {
            get {
                return ResourceManager.GetString("Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Open.
        /// </summary>
        internal static string Ps {
            get {
                return ResourceManager.GetString("Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Currency.
        /// </summary>
        internal static string Sc {
            get {
                return ResourceManager.GetString("Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Modifier.
        /// </summary>
        internal static string Sk {
            get {
                return ResourceManager.GetString("Sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Math.
        /// </summary>
        internal static string Sm {
            get {
                return ResourceManager.GetString("Sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Other.
        /// </summary>
        internal static string So {
            get {
                return ResourceManager.GetString("So", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Line.
        /// </summary>
        internal static string Zl {
            get {
                return ResourceManager.GetString("Zl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Paragraph.
        /// </summary>
        internal static string Zp {
            get {
                return ResourceManager.GetString("Zp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Space.
        /// </summary>
        internal static string Zs {
            get {
                return ResourceManager.GetString("Zs", resourceCulture);
            }
        }
    }
}
