//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.UnicodeBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UcdCodePointStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UcdCodePointStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.UnicodeBuild.Resources.UcdCodePointStrings", typeof(UcdCodePointStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area is a Unicode block that define only first and last code points..
        /// </summary>
        public static string AreaTooltip {
            get {
                return ResourceManager.GetString("AreaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artefact.
        /// </summary>
        public static string Artefact {
            get {
                return ResourceManager.GetString("Artefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artefact of human culture, from which this code point originates..
        /// </summary>
        public static string ArtefactTooltip {
            get {
                return ResourceManager.GetString("ArtefactTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code point is a hexadecimal integer from 4 to 6 digits..
        /// </summary>
        public static string CPTooltip {
            get {
                return ResourceManager.GetString("CPTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctg.
        /// </summary>
        public static string Ctg {
            get {
                return ResourceManager.GetString("Ctg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode category to which this code point is assigned..
        /// </summary>
        public static string CtgTooltip {
            get {
                return ResourceManager.GetString("CtgTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description as provided by Unicode database..
        /// </summary>
        public static string DescriptionTooltip {
            get {
                return ResourceManager.GetString("DescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph.
        /// </summary>
        public static string Glyph {
            get {
                return ResourceManager.GetString("Glyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview of character font face..
        /// </summary>
        public static string GlyphTooltip {
            get {
                return ResourceManager.GetString("GlyphTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language which uses this code point..
        /// </summary>
        public static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char name used in serialization..
        /// </summary>
        public static string NameTooltip {
            get {
                return ResourceManager.GetString("NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name without writing system.
        /// </summary>
        public static string NameWithoutWS {
            get {
                return ResourceManager.GetString("NameWithoutWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description name without keyphrase of recognized writing system..
        /// </summary>
        public static string NameWithoutWSTooltip {
            get {
                return ResourceManager.GetString("NameWithoutWSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation.
        /// </summary>
        public static string Notation {
            get {
                return ResourceManager.GetString("Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation in which this code point is defined..
        /// </summary>
        public static string NotationTooltip {
            get {
                return ResourceManager.GetString("NotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script which uses this code point..
        /// </summary>
        public static string ScriptTooltip {
            get {
                return ResourceManager.GetString("ScriptTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset.
        /// </summary>
        public static string Subset {
            get {
                return ResourceManager.GetString("Subset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset, to which this code point can be classified..
        /// </summary>
        public static string SubsetTooltip {
            get {
                return ResourceManager.GetString("SubsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol set.
        /// </summary>
        public static string SymbolSet {
            get {
                return ResourceManager.GetString("SymbolSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol set to which this code point belongs..
        /// </summary>
        public static string SymbolSetTooltip {
            get {
                return ResourceManager.GetString("SymbolSetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Block.
        /// </summary>
        public static string UcdBlock {
            get {
                return ResourceManager.GetString("UcdBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode block which contains this code point..
        /// </summary>
        public static string UcdBlockTooltip {
            get {
                return ResourceManager.GetString("UcdBlockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Range.
        /// </summary>
        public static string UcdRange {
            get {
                return ResourceManager.GetString("UcdRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode range which contains this code point..
        /// </summary>
        public static string UcdRangeTooltip {
            get {
                return ResourceManager.GetString("UcdRangeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing System.
        /// </summary>
        public static string WritingSystem {
            get {
                return ResourceManager.GetString("WritingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system to which this code point belongs. You can choose script, notation, a group of scripts or notations, or area here..
        /// </summary>
        public static string WritingSystemTooltip {
            get {
                return ResourceManager.GetString("WritingSystemTooltip", resourceCulture);
            }
        }
    }
}
