//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.UnicodeBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WritingSystemKind {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WritingSystemKind() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.UnicodeBuild.Resources.WritingSystemKind", typeof(WritingSystemKind).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abjad.
        /// </summary>
        public static string Abjad {
            get {
                return ResourceManager.GetString("Abjad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system in which only consonants are represented, leaving the vowel sounds to be inferred by the reader..
        /// </summary>
        public static string AbjadTooltip {
            get {
                return ResourceManager.GetString("AbjadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abugida.
        /// </summary>
        public static string Abugida {
            get {
                return ResourceManager.GetString("Abugida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A segmental writing system in which consonant–vowel sequences are written as units; each unit is based on a consonant letter, and vowel notation is secondary, similar to a diacritical mark..
        /// </summary>
        public static string AbugidaTooltip {
            get {
                return ResourceManager.GetString("AbugidaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        public static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard set of letters written to represent particular sounds in a spoken language..
        /// </summary>
        public static string AlphabetTooltip {
            get {
                return ResourceManager.GetString("AlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructed.
        /// </summary>
        public static string Constructed {
            get {
                return ResourceManager.GetString("Constructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language whose phonology, grammar, orthography, and vocabulary, instead of having developed naturally, are consciously devised for some purpose..
        /// </summary>
        public static string ConstructedTooltip {
            get {
                return ResourceManager.GetString("ConstructedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of characters that control the flow of text,.
        /// </summary>
        public static string ControlTooltip {
            get {
                return ResourceManager.GetString("ControlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuneiform.
        /// </summary>
        public static string Cuneiform {
            get {
                return ResourceManager.GetString("Cuneiform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logo-syllabic writing system that was used to write several languages of the Ancient Near East, named for the characteristic wedge-shaped impressions which form their signs..
        /// </summary>
        public static string CuneiformTooltip {
            get {
                return ResourceManager.GetString("CuneiformTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of characters encoding other characters..
        /// </summary>
        public static string EncodingTooltip {
            get {
                return ResourceManager.GetString("EncodingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of characters with a special presentation form..
        /// </summary>
        public static string FormTooltip {
            get {
                return ResourceManager.GetString("FormTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphical.
        /// </summary>
        public static string Graphical {
            get {
                return ResourceManager.GetString("Graphical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of graphical shapes for individual use or used to construct drawings..
        /// </summary>
        public static string GraphicalTooltip {
            get {
                return ResourceManager.GetString("GraphicalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hieroglyphic.
        /// </summary>
        public static string Hieroglyphic {
            get {
                return ResourceManager.GetString("Hieroglyphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ancient writing system that combines ideographic, logographic, syllabic and alphabetic elements..
        /// </summary>
        public static string HieroglyphicTooltip {
            get {
                return ResourceManager.GetString("HieroglyphicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideographic.
        /// </summary>
        public static string Ideographic {
            get {
                return ResourceManager.GetString("Ideographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system consisting of symbols that represents ideas or concepts independent of any particular language..
        /// </summary>
        public static string IdeographicTooltip {
            get {
                return ResourceManager.GetString("IdeographicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        public static string Invisible {
            get {
                return ResourceManager.GetString("Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of code points that have no visible presentations..
        /// </summary>
        public static string InvisibleTooltip {
            get {
                return ResourceManager.GetString("InvisibleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logographic.
        /// </summary>
        public static string Logographic {
            get {
                return ResourceManager.GetString("Logographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of written characters that represent semantic components of a language, such as words or morphemes..
        /// </summary>
        public static string LogographicTooltip {
            get {
                return ResourceManager.GetString("LogographicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed logographic, syllabary and phonetic writing system..
        /// </summary>
        public static string MixedTooltip {
            get {
                return ResourceManager.GetString("MixedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        public static string Musical {
            get {
                return ResourceManager.GetString("Musical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system used to visually represent music..
        /// </summary>
        public static string MusicalTooltip {
            get {
                return ResourceManager.GetString("MusicalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical.
        /// </summary>
        public static string Numerical {
            get {
                return ResourceManager.GetString("Numerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system for expressing numbers; that is, a mathematical notation for representing numbers of a given set, using digits or other symbols in a consistent manner..
        /// </summary>
        public static string NumericalTooltip {
            get {
                return ResourceManager.GetString("NumericalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic.
        /// </summary>
        public static string Phonetic {
            get {
                return ResourceManager.GetString("Phonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of symbols used in phonetic notation..
        /// </summary>
        public static string PhoneticTooltip {
            get {
                return ResourceManager.GetString("PhoneticTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictographic.
        /// </summary>
        public static string Pictographic {
            get {
                return ResourceManager.GetString("Pictographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of graphical symbols that convey meaning through its visual resemblance to physical objects..
        /// </summary>
        public static string PictographicTooltip {
            get {
                return ResourceManager.GetString("PictographicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-syllabary.
        /// </summary>
        public static string SemiSyllabary {
            get {
                return ResourceManager.GetString("SemiSyllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system that behaves partly as an alphabet and partly as a syllabary..
        /// </summary>
        public static string SemiSyllabaryTooltip {
            get {
                return ResourceManager.GetString("SemiSyllabaryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stenography.
        /// </summary>
        public static string Stenography {
            get {
                return ResourceManager.GetString("Stenography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abbreviated symbolic writing method that increases speed and brevity of writing as compared to longhand, a more common method of writing a language..
        /// </summary>
        public static string StenographyTooltip {
            get {
                return ResourceManager.GetString("StenographyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllabary.
        /// </summary>
        public static string Syllabary {
            get {
                return ResourceManager.GetString("Syllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of written symbols that represent the syllables or (more frequently) morae which make up words..
        /// </summary>
        public static string SyllabaryTooltip {
            get {
                return ResourceManager.GetString("SyllabaryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic.
        /// </summary>
        public static string Symbolic {
            get {
                return ResourceManager.GetString("Symbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of symbols from a certain domain..
        /// </summary>
        public static string SymbolicTooltip {
            get {
                return ResourceManager.GetString("SymbolicTooltip", resourceCulture);
            }
        }
    }
}
