using Word = Microsoft.Office.Interop.Word;

namespace Qhta.WordInteropOpenXmlConverter;
public static class LangConverter
{
  public static string LanguageIdToBcp47Tag(Word.WdLanguageID wdLanguageID)
  {
    // Map WdLanguageID to BCP 47 tag (simplified example)
    string bcp47Tag = wdLanguageID switch
    {
      Word.WdLanguageID.wdAfrikaans => "af-ZA",
      Word.WdLanguageID.wdAlbanian => "sq-AL",
      Word.WdLanguageID.wdAmharic => "am-ET",
      Word.WdLanguageID.wdArabic => "ar-SA",
      Word.WdLanguageID.wdArabicAlgeria => "ar-DZ",
      Word.WdLanguageID.wdArabicBahrain => "ar-BH",
      Word.WdLanguageID.wdArabicEgypt => "ar-EG",
      Word.WdLanguageID.wdArabicIraq => "ar-IQ",
      Word.WdLanguageID.wdArabicJordan => "ar-JO",
      Word.WdLanguageID.wdArabicKuwait => "ar-KW",
      Word.WdLanguageID.wdArabicLebanon => "ar-LB",
      Word.WdLanguageID.wdArabicLibya => "ar-LY",
      Word.WdLanguageID.wdArabicMorocco => "ar-MO",
      Word.WdLanguageID.wdArabicOman => "ar-OM",
      Word.WdLanguageID.wdArabicQatar => "ar-QA",
      Word.WdLanguageID.wdArabicSyria => "ar-SY",
      Word.WdLanguageID.wdArabicTunisia => "ar-TN",
      Word.WdLanguageID.wdArabicUAE => "ar-AE",
      Word.WdLanguageID.wdArabicYemen => "ar-YE",
      Word.WdLanguageID.wdArmenian => "hy-AM",
      Word.WdLanguageID.wdAssamese => "as-IN",
      Word.WdLanguageID.wdAzeriCyrillic => "az-Cyrl-AZ",
      Word.WdLanguageID.wdAzeriLatin => "az-Latn-AZ",

      Word.WdLanguageID.wdBasque => "eu-ES",
      Word.WdLanguageID.wdBelgianDutch => "nl-BE",
      Word.WdLanguageID.wdBelgianFrench => "fr-BE",
      Word.WdLanguageID.wdBengali => "bn-BN",
      Word.WdLanguageID.wdBulgarian => "bg-BG",
      Word.WdLanguageID.wdBurmese => "my-MM",
      Word.WdLanguageID.wdByelorussian => "be-BY",

      Word.WdLanguageID.wdCatalan => "ca-ES",
      Word.WdLanguageID.wdCherokee => "chr-US",
      Word.WdLanguageID.wdChineseHongKongSAR => "zh-HK",
      Word.WdLanguageID.wdChineseMacaoSAR => "zh-MO",
      Word.WdLanguageID.wdSimplifiedChinese => "zh-CN",
      Word.WdLanguageID.wdChineseSingapore => "zh-SG",

      Word.WdLanguageID.wdCroatian => "hr-HR",

      Word.WdLanguageID.wdCzech => "cs-CZ",
      Word.WdLanguageID.wdDanish => "da-DK",
      Word.WdLanguageID.wdDivehi => "dv-MV",

      Word.WdLanguageID.wdDutch => "nl-NL",
      Word.WdLanguageID.wdEdo => "bin-NG",
      Word.WdLanguageID.wdEnglishAUS => "en-AU",
      Word.WdLanguageID.wdEnglishBelize => "en-BZ",
      Word.WdLanguageID.wdEnglishCanadian => "en-CA",
      Word.WdLanguageID.wdEnglishCaribbean => "en-029",

      Word.WdLanguageID.wdEnglishIndonesia => "en-ID",
      Word.WdLanguageID.wdEnglishIreland => "en-IE",
      Word.WdLanguageID.wdEnglishJamaica => "en-JM",

      Word.WdLanguageID.wdEnglishNewZealand => "en-NZ",
      Word.WdLanguageID.wdEnglishPhilippines => "en-PH",

      Word.WdLanguageID.wdEnglishSouthAfrica => "en-ZA",
      Word.WdLanguageID.wdEnglishTrinidadTobago => "en-TT",
      Word.WdLanguageID.wdEnglishUK => "en-GB",
      Word.WdLanguageID.wdEnglishUS => "en-US",
      Word.WdLanguageID.wdEnglishZimbabwe => "en-ZW",
      Word.WdLanguageID.wdEstonian => "et-EE",
      Word.WdLanguageID.wdFaeroese => "fo-FO",
      Word.WdLanguageID.wdFilipino => "fil-PH",
      Word.WdLanguageID.wdFinnish => "fi-FI",

      Word.WdLanguageID.wdFrenchCameroon => "fr-CM",
      Word.WdLanguageID.wdFrenchCanadian => "fr-CA",
      Word.WdLanguageID.wdFrenchCotedIvoire => "fr-CI",
      Word.WdLanguageID.wdFrenchCongoDRC => "fr-CG",
      Word.WdLanguageID.wdFrench => "fr-FR",
      Word.WdLanguageID.wdFrenchHaiti => "fr-HT",
      Word.WdLanguageID.wdFrenchLuxembourg => "fr-LU",
      Word.WdLanguageID.wdFrenchMali => "fr-ML",
      Word.WdLanguageID.wdFrenchMonaco => "fr-MC",
      Word.WdLanguageID.wdFrenchMorocco => "fr-MA",

      Word.WdLanguageID.wdFrenchReunion => "fr-RE",
      Word.WdLanguageID.wdFrenchSenegal => "fr-SN",
      Word.WdLanguageID.wdSwissFrench => "fr-CH",
      Word.WdLanguageID.wdFrenchWestIndies => "fr-029",
      Word.WdLanguageID.wdFrisianNetherlands => "fy-NL",
      Word.WdLanguageID.wdFulfulde => "fuv-NG",
      Word.WdLanguageID.wdMacedonianFYROM => "mk-MK",
      Word.WdLanguageID.wdGaelicIreland => "ga-IE",
      Word.WdLanguageID.wdGaelicScotland => "gd-GB",
      Word.WdLanguageID.wdGalician => "gl-ES",
      Word.WdLanguageID.wdGeorgian => "ka-GE",
      Word.WdLanguageID.wdGerman => "de-DE",
      Word.WdLanguageID.wdGermanAustria => "de-AT",
      Word.WdLanguageID.wdGermanLiechtenstein => "de-LI",
      Word.WdLanguageID.wdGermanLuxembourg => "de-LU",
      Word.WdLanguageID.wdSwissGerman => "de-CH",
      Word.WdLanguageID.wdGreek => "el-GR",
      Word.WdLanguageID.wdGuarani => "gn-PY",
      Word.WdLanguageID.wdGujarati => "gu-IN",
      Word.WdLanguageID.wdHausa => "ha-Latn-NG",
      Word.WdLanguageID.wdHawaiian => "haw-US",
      Word.WdLanguageID.wdHebrew => "he-IL",
      Word.WdLanguageID.wdHindi => "hi-IN",
      Word.WdLanguageID.wdHungarian => "hu-HU",
      Word.WdLanguageID.wdIbibio => "ibb-NG",
      Word.WdLanguageID.wdIcelandic => "is-IS",
      Word.WdLanguageID.wdIgbo => "ig-NG",
      Word.WdLanguageID.wdIndonesian => "id-ID",
      Word.WdLanguageID.wdInuktitut => "iu-Cans-CA",
      Word.WdLanguageID.wdItalian => "it-IT",
      Word.WdLanguageID.wdSwissItalian => "it-CH",
      Word.WdLanguageID.wdJapanese => "ja-JP",
      Word.WdLanguageID.wdKannada => "kn-IN",
      Word.WdLanguageID.wdKanuri => "kr-NG",
      Word.WdLanguageID.wdKashmiri => "ks-Arab-IN",

      Word.WdLanguageID.wdKazakh => "kk-KZ",
      Word.WdLanguageID.wdKhmer => "km-KH",
      Word.WdLanguageID.wdKirghiz => "kok-IN",
      Word.WdLanguageID.wdKonkani => "ko-KR",
      Word.WdLanguageID.wdKorean => "ky-KG",
      Word.WdLanguageID.wdLao => "lo-LA",
      Word.WdLanguageID.wdLatin => "la",
      Word.WdLanguageID.wdLatvian => "lv-LV",
      Word.WdLanguageID.wdLithuanian => "lt-LT",

      Word.WdLanguageID.wdMalayalam => "ms-BN",
      Word.WdLanguageID.wdMalayBruneiDarussalam => "ms-MY",
      Word.WdLanguageID.wdMalaysian => "ml-IN",
      Word.WdLanguageID.wdMaltese => "mt-MT",
      Word.WdLanguageID.wdManipuri => "mni",

      Word.WdLanguageID.wdMarathi => "mr-IN",
      Word.WdLanguageID.wdMexicanSpanish => "es-MX",

      Word.WdLanguageID.wdMongolian => "mn-Mong-CN",
      Word.WdLanguageID.wdNepali => "ne-NP",

      Word.WdLanguageID.wdNorwegianBokmol => "nb-NO",
      Word.WdLanguageID.wdNorwegianNynorsk => "nn-NO",
      Word.WdLanguageID.wdOriya => "or-IN",
      Word.WdLanguageID.wdOromo => "gaz-ET",

      Word.WdLanguageID.wdPashto => "ps-AF",
      Word.WdLanguageID.wdPersian => "fa-IR",
      Word.WdLanguageID.wdPolish => "pl-PL",
      Word.WdLanguageID.wdPortugueseBrazil => "pt-BR",
      Word.WdLanguageID.wdPortuguese => "pt-PT",
      Word.WdLanguageID.wdPunjabi => "pa-IN",

      Word.WdLanguageID.wdRhaetoRomanic => "rm-CH",
      Word.WdLanguageID.wdRomanian => "ro-RO",
      Word.WdLanguageID.wdRomanianMoldova => "ro-MD",
      Word.WdLanguageID.wdRussian => "ru-RU",
      Word.WdLanguageID.wdRussianMoldova => "ru-MD",
      Word.WdLanguageID.wdSamiLappish => "se-NO",
      Word.WdLanguageID.wdSanskrit => "sa-IN",

      Word.WdLanguageID.wdSerbianCyrillic => "sr-Cyrl-CS+C44",
      Word.WdLanguageID.wdSerbianLatin => "sr-Latn-CS",
      Word.WdLanguageID.wdSindhi => "sd-IN",
      Word.WdLanguageID.wdSindhiPakistan => "sd-PK",
      Word.WdLanguageID.wdSinhalese => "si-LK",
      Word.WdLanguageID.wdSlovak => "sk-SK",
      Word.WdLanguageID.wdSlovenian => "sl-SI",
      Word.WdLanguageID.wdSomali => "so-SO",
      Word.WdLanguageID.wdSorbian => "wen-DE",
      Word.WdLanguageID.wdSpanish => "es-ES",
      Word.WdLanguageID.wdSpanishArgentina => "es-AR",
      Word.WdLanguageID.wdSpanishBolivia => "es-BO",
      Word.WdLanguageID.wdSpanishChile => "es-CL",
      Word.WdLanguageID.wdSpanishColombia => "es-CO",
      Word.WdLanguageID.wdSpanishCostaRica => "es-CR",
      Word.WdLanguageID.wdSpanishDominicanRepublic => "es-DO",
      Word.WdLanguageID.wdSpanishEcuador => "es-EC",
      Word.WdLanguageID.wdSpanishElSalvador => "es-SV",
      Word.WdLanguageID.wdSpanishGuatemala => "es-GT",
      Word.WdLanguageID.wdSpanishHonduras => "es-HN",
      Word.WdLanguageID.wdSpanishModernSort => "es-ES",

      Word.WdLanguageID.wdSpanishNicaragua => "es-NI",
      Word.WdLanguageID.wdSpanishPanama => "es-PA",
      Word.WdLanguageID.wdSpanishParaguay => "es-PY",
      Word.WdLanguageID.wdSpanishPeru => "es-PE",
      Word.WdLanguageID.wdSpanishPuertoRico => "es-PR",

      Word.WdLanguageID.wdSpanishUruguay => "es-UY",
      Word.WdLanguageID.wdSpanishVenezuela => "es-VE",
      Word.WdLanguageID.wdSutu => "st-ZA",
      Word.WdLanguageID.wdSwahili => "sw-KE",
      Word.WdLanguageID.wdSwedish => "sv-SE",
      Word.WdLanguageID.wdSwedishFinland => "sv-FI",
      Word.WdLanguageID.wdSyriac => "syr-SY",
      Word.WdLanguageID.wdTajik => "tg-Cyrl-TJ",
      Word.WdLanguageID.wdTamazight => "tmz",
      Word.WdLanguageID.wdTamazightLatin => "tzm-Latn-DZ",
      Word.WdLanguageID.wdTamil => "ta-IN",
      Word.WdLanguageID.wdTatar => "tt-RU",
      Word.WdLanguageID.wdTelugu => "te-IN",
      Word.WdLanguageID.wdThai => "th-TH",
      Word.WdLanguageID.wdTibetan => "bo-BT",

      Word.WdLanguageID.wdTigrignaEritrea => "ti-ET",
      Word.WdLanguageID.wdTigrignaEthiopic => "ti-ER",
      Word.WdLanguageID.wdTraditionalChinese => "zh-Hant",
      Word.WdLanguageID.wdTsonga => "ts-ZA",
      Word.WdLanguageID.wdTswana => "tn-ZA",
      Word.WdLanguageID.wdTurkish => "tr-TR",
      Word.WdLanguageID.wdTurkmen => "tk-TM",

      Word.WdLanguageID.wdUkrainian => "uk-UA",
      Word.WdLanguageID.wdUrdu => "ur-IN",

      Word.WdLanguageID.wdUzbekCyrillic => "uz-Cyrl-UZ",
      Word.WdLanguageID.wdUzbekLatin => "uz-Latn-UZ",
      Word.WdLanguageID.wdVenda => "ven-ZA",
      Word.WdLanguageID.wdVietnamese => "vi-VN",
      Word.WdLanguageID.wdWelsh => "cy-GB",
      Word.WdLanguageID.wdXhosa => "xh-ZA",
      Word.WdLanguageID.wdYi => "ii-CN",
      Word.WdLanguageID.wdYiddish => "yi",
      Word.WdLanguageID.wdYoruba => "yo-NG",
      Word.WdLanguageID.wdZulu => "zu-ZA",

      _ => "en-US", // Default or fallback language

    };
    return bcp47Tag;
  }
}
