using static Microsoft.Office.Interop.Word.WdLanguageID;

using Word = Microsoft.Office.Interop.Word;

namespace Qhta.WordInteropOpenXmlConverter;
public static class LanguageConverter
{
  public static string LanguageIdToBcp47Tag(Word.WdLanguageID wdLanguageID)
  {
    // Map WdLanguageID to BCP 47 tag (simplified example)
    string bcp47Tag = wdLanguageID switch
    {
      wdAfrikaans => "af-ZA",
      wdAlbanian => "sq-AL",
      wdAmharic => "am-ET",
      wdArabic => "ar-SA",
      wdArabicAlgeria => "ar-DZ",
      wdArabicBahrain => "ar-BH",
      wdArabicEgypt => "ar-EG",
      wdArabicIraq => "ar-IQ",
      wdArabicJordan => "ar-JO",
      wdArabicKuwait => "ar-KW",
      wdArabicLebanon => "ar-LB",
      wdArabicLibya => "ar-LY",
      wdArabicMorocco => "ar-MO",
      wdArabicOman => "ar-OM",
      wdArabicQatar => "ar-QA",
      wdArabicSyria => "ar-SY",
      wdArabicTunisia => "ar-TN",
      wdArabicUAE => "ar-AE",
      wdArabicYemen => "ar-YE",
      wdArmenian => "hy-AM",
      wdAssamese => "as-IN",
      wdAzeriCyrillic => "az-Cyrl-AZ",
      wdAzeriLatin => "az-Latn-AZ",

      wdBasque => "eu-ES",
      wdBelgianDutch => "nl-BE",
      wdBelgianFrench => "fr-BE",
      wdBengali => "bn-BN",
      wdBulgarian => "bg-BG",
      wdBurmese => "my-MM",
      wdByelorussian => "be-BY",

      wdCatalan => "ca-ES",
      wdCherokee => "chr-US",
      wdChineseHongKongSAR => "zh-HK",
      wdChineseMacaoSAR => "zh-MO",
      wdSimplifiedChinese => "zh-CN",
      wdChineseSingapore => "zh-SG",

      wdCroatian => "hr-HR",

      wdCzech => "cs-CZ",
      wdDanish => "da-DK",
      wdDivehi => "dv-MV",

      wdDutch => "nl-NL",
      wdEdo => "bin-NG",
      wdEnglishAUS => "en-AU",
      wdEnglishBelize => "en-BZ",
      wdEnglishCanadian => "en-CA",
      wdEnglishCaribbean => "en-029",

      wdEnglishIndonesia => "en-ID",
      wdEnglishIreland => "en-IE",
      wdEnglishJamaica => "en-JM",

      wdEnglishNewZealand => "en-NZ",
      wdEnglishPhilippines => "en-PH",

      wdEnglishSouthAfrica => "en-ZA",
      wdEnglishTrinidadTobago => "en-TT",
      wdEnglishUK => "en-GB",
      wdEnglishUS => "en-US",
      wdEnglishZimbabwe => "en-ZW",
      wdEstonian => "et-EE",
      wdFaeroese => "fo-FO",
      wdFilipino => "fil-PH",
      wdFinnish => "fi-FI",

      wdFrenchCameroon => "fr-CM",
      wdFrenchCanadian => "fr-CA",
      wdFrenchCotedIvoire => "fr-CI",
      wdFrenchCongoDRC => "fr-CG",
      wdFrench => "fr-FR",
      wdFrenchHaiti => "fr-HT",
      wdFrenchLuxembourg => "fr-LU",
      wdFrenchMali => "fr-ML",
      wdFrenchMonaco => "fr-MC",
      wdFrenchMorocco => "fr-MA",

      wdFrenchReunion => "fr-RE",
      wdFrenchSenegal => "fr-SN",
      wdSwissFrench => "fr-CH",
      wdFrenchWestIndies => "fr-029",
      wdFrisianNetherlands => "fy-NL",
      wdFulfulde => "fuv-NG",
      wdMacedonianFYROM => "mk-MK",
      wdGaelicIreland => "ga-IE",
      wdGaelicScotland => "gd-GB",
      wdGalician => "gl-ES",
      wdGeorgian => "ka-GE",
      wdGerman => "de-DE",
      wdGermanAustria => "de-AT",
      wdGermanLiechtenstein => "de-LI",
      wdGermanLuxembourg => "de-LU",
      wdSwissGerman => "de-CH",
      wdGreek => "el-GR",
      wdGuarani => "gn-PY",
      wdGujarati => "gu-IN",
      wdHausa => "ha-Latn-NG",
      wdHawaiian => "haw-US",
      wdHebrew => "he-IL",
      wdHindi => "hi-IN",
      wdHungarian => "hu-HU",
      wdIbibio => "ibb-NG",
      wdIcelandic => "is-IS",
      wdIgbo => "ig-NG",
      wdIndonesian => "id-ID",
      wdInuktitut => "iu-Cans-CA",
      wdItalian => "it-IT",
      wdSwissItalian => "it-CH",
      wdJapanese => "ja-JP",
      wdKannada => "kn-IN",
      wdKanuri => "kr-NG",
      wdKashmiri => "ks-Arab-IN",

      wdKazakh => "kk-KZ",
      wdKhmer => "km-KH",
      wdKirghiz => "kok-IN",
      wdKonkani => "ko-KR",
      wdKorean => "ky-KG",
      wdLao => "lo-LA",
      wdLatin => "la",
      wdLatvian => "lv-LV",
      wdLithuanian => "lt-LT",

      wdMalayalam => "ms-BN",
      wdMalayBruneiDarussalam => "ms-MY",
      wdMalaysian => "ml-IN",
      wdMaltese => "mt-MT",
      wdManipuri => "mni",

      wdMarathi => "mr-IN",
      wdMexicanSpanish => "es-MX",

      wdMongolian => "mn-Mong-CN",
      wdNepali => "ne-NP",

      wdNorwegianBokmol => "nb-NO",
      wdNorwegianNynorsk => "nn-NO",
      wdOriya => "or-IN",
      wdOromo => "gaz-ET",

      wdPashto => "ps-AF",
      wdPersian => "fa-IR",
      wdPolish => "pl-PL",
      wdPortugueseBrazil => "pt-BR",
      wdPortuguese => "pt-PT",
      wdPunjabi => "pa-IN",

      wdRhaetoRomanic => "rm-CH",
      wdRomanian => "ro-RO",
      wdRomanianMoldova => "ro-MD",
      wdRussian => "ru-RU",
      wdRussianMoldova => "ru-MD",
      wdSamiLappish => "se-NO",
      wdSanskrit => "sa-IN",

      wdSerbianCyrillic => "sr-Cyrl-CS+C44",
      wdSerbianLatin => "sr-Latn-CS",
      wdSindhi => "sd-IN",
      wdSindhiPakistan => "sd-PK",
      wdSinhalese => "si-LK",
      wdSlovak => "sk-SK",
      wdSlovenian => "sl-SI",
      wdSomali => "so-SO",
      wdSorbian => "wen-DE",
      wdSpanish => "es-ES",
      wdSpanishArgentina => "es-AR",
      wdSpanishBolivia => "es-BO",
      wdSpanishChile => "es-CL",
      wdSpanishColombia => "es-CO",
      wdSpanishCostaRica => "es-CR",
      wdSpanishDominicanRepublic => "es-DO",
      wdSpanishEcuador => "es-EC",
      wdSpanishElSalvador => "es-SV",
      wdSpanishGuatemala => "es-GT",
      wdSpanishHonduras => "es-HN",
      wdSpanishModernSort => "es-ES",

      wdSpanishNicaragua => "es-NI",
      wdSpanishPanama => "es-PA",
      wdSpanishParaguay => "es-PY",
      wdSpanishPeru => "es-PE",
      wdSpanishPuertoRico => "es-PR",

      wdSpanishUruguay => "es-UY",
      wdSpanishVenezuela => "es-VE",
      wdSutu => "st-ZA",
      wdSwahili => "sw-KE",
      wdSwedish => "sv-SE",
      wdSwedishFinland => "sv-FI",
      wdSyriac => "syr-SY",
      wdTajik => "tg-Cyrl-TJ",
      wdTamazight => "tmz",
      wdTamazightLatin => "tzm-Latn-DZ",
      wdTamil => "ta-IN",
      wdTatar => "tt-RU",
      wdTelugu => "te-IN",
      wdThai => "th-TH",
      wdTibetan => "bo-BT",

      wdTigrignaEritrea => "ti-ET",
      wdTigrignaEthiopic => "ti-ER",
      wdTraditionalChinese => "zh-Hant",
      wdTsonga => "ts-ZA",
      wdTswana => "tn-ZA",
      wdTurkish => "tr-TR",
      wdTurkmen => "tk-TM",

      wdUkrainian => "uk-UA",
      wdUrdu => "ur-IN",

      wdUzbekCyrillic => "uz-Cyrl-UZ",
      wdUzbekLatin => "uz-Latn-UZ",
      wdVenda => "ven-ZA",
      wdVietnamese => "vi-VN",
      wdWelsh => "cy-GB",
      wdXhosa => "xh-ZA",
      wdYi => "ii-CN",
      wdYiddish => "yi",
      wdYoruba => "yo-NG",
      wdZulu => "zu-ZA",

      _ => "en-US", // Default or fallback language

    };
    return bcp47Tag;
  }
}
