//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.WordInteropOpenXmlConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.WordInteropOpenXmlConverter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body CS.
        /// </summary>
        public static string Body_CS {
            get {
                return ResourceManager.GetString("Body CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body EA.
        /// </summary>
        public static string Body_EA {
            get {
                return ResourceManager.GetString("Body EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet list.
        /// </summary>
        public static string BulletList {
            get {
                return ResourceManager.GetString("BulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings.
        /// </summary>
        public static string Headings {
            get {
                return ResourceManager.GetString("Headings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings CS.
        /// </summary>
        public static string Headings_CS {
            get {
                return ResourceManager.GetString("Headings CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings EA.
        /// </summary>
        public static string Headings_EA {
            get {
                return ResourceManager.GetString("Headings EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering list.
        /// </summary>
        public static string NumberingList {
            get {
                return ResourceManager.GetString("NumberingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline numbering list.
        /// </summary>
        public static string OutlineNumberingList {
            get {
                return ResourceManager.GetString("OutlineNumberingList", resourceCulture);
            }
        }
    }
}
