#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Office.Interop.Word;
using Qhta.TextUtils;

using Word = Microsoft.Office.Interop.Word;

namespace Qhta.WordInteropOpenXmlConverter
{
  public class StyleTools
  {
    public static Dictionary<WdBuiltinStyle, MyBuiltinStyle> WdBuiltinStyleMyBuiltInStyles = new()
    {
      { WdBuiltinStyle.wdStyleNormal, MyBuiltinStyle.Normal },
      { WdBuiltinStyle.wdStyleHeading1, MyBuiltinStyle.Heading1 },
      { WdBuiltinStyle.wdStyleHeading2, MyBuiltinStyle.Heading2 },
      { WdBuiltinStyle.wdStyleHeading3, MyBuiltinStyle.Heading3 },
      { WdBuiltinStyle.wdStyleHeading4, MyBuiltinStyle.Heading4 },
      { WdBuiltinStyle.wdStyleHeading5, MyBuiltinStyle.Heading5 },
      { WdBuiltinStyle.wdStyleHeading6, MyBuiltinStyle.Heading6 },
      { WdBuiltinStyle.wdStyleHeading7, MyBuiltinStyle.Heading7 },
      { WdBuiltinStyle.wdStyleHeading8, MyBuiltinStyle.Heading8 },
      { WdBuiltinStyle.wdStyleHeading9, MyBuiltinStyle.Heading9 },
      { WdBuiltinStyle.wdStyleIndex1, MyBuiltinStyle.Index1 },
      { WdBuiltinStyle.wdStyleIndex2, MyBuiltinStyle.Index2 },
      { WdBuiltinStyle.wdStyleIndex3, MyBuiltinStyle.Index3 },
      { WdBuiltinStyle.wdStyleIndex4, MyBuiltinStyle.Index4 },
      { WdBuiltinStyle.wdStyleIndex5, MyBuiltinStyle.Index5 },
      { WdBuiltinStyle.wdStyleIndex6, MyBuiltinStyle.Index6 },
      { WdBuiltinStyle.wdStyleIndex7, MyBuiltinStyle.Index7 },
      { WdBuiltinStyle.wdStyleIndex8, MyBuiltinStyle.Index8 },
      { WdBuiltinStyle.wdStyleIndex9, MyBuiltinStyle.Index9 },
      { WdBuiltinStyle.wdStyleTOC1, MyBuiltinStyle.Toc1 },
      { WdBuiltinStyle.wdStyleTOC2, MyBuiltinStyle.Toc2 },
      { WdBuiltinStyle.wdStyleTOC3, MyBuiltinStyle.Toc3 },
      { WdBuiltinStyle.wdStyleTOC4, MyBuiltinStyle.Toc4 },
      { WdBuiltinStyle.wdStyleTOC5, MyBuiltinStyle.Toc5 },
      { WdBuiltinStyle.wdStyleTOC6, MyBuiltinStyle.Toc6 },
      { WdBuiltinStyle.wdStyleTOC7, MyBuiltinStyle.Toc7 },
      { WdBuiltinStyle.wdStyleTOC8, MyBuiltinStyle.Toc8 },
      { WdBuiltinStyle.wdStyleTOC9, MyBuiltinStyle.Toc9 },
      { WdBuiltinStyle.wdStyleNormalIndent, MyBuiltinStyle.NormalIndent },
      { WdBuiltinStyle.wdStyleFootnoteText, MyBuiltinStyle.FootnoteText },
      { WdBuiltinStyle.wdStyleCommentText, MyBuiltinStyle.AnnotationText },
      { WdBuiltinStyle.wdStyleHeader, MyBuiltinStyle.Header },
      { WdBuiltinStyle.wdStyleFooter, MyBuiltinStyle.Footer },
      { WdBuiltinStyle.wdStyleIndexHeading, MyBuiltinStyle.IndexHeading },
      { WdBuiltinStyle.wdStyleCaption, MyBuiltinStyle.Caption },
      { WdBuiltinStyle.wdStyleTableOfFigures, MyBuiltinStyle.TableOfFigures },
      { WdBuiltinStyle.wdStyleEnvelopeAddress, MyBuiltinStyle.EnvelopeAddress },
      { WdBuiltinStyle.wdStyleEnvelopeReturn, MyBuiltinStyle.EnvelopeReturn },
      { WdBuiltinStyle.wdStyleFootnoteReference, MyBuiltinStyle.FootnoteReference },
      { WdBuiltinStyle.wdStyleCommentReference, MyBuiltinStyle.AnnotationReference },
      { WdBuiltinStyle.wdStyleLineNumber, MyBuiltinStyle.LineNumber },
      { WdBuiltinStyle.wdStylePageNumber, MyBuiltinStyle.PageNumber },
      { WdBuiltinStyle.wdStyleEndnoteReference, MyBuiltinStyle.EndnoteReference },
      { WdBuiltinStyle.wdStyleEndnoteText, MyBuiltinStyle.EndnoteText },
      { WdBuiltinStyle.wdStyleTableOfAuthorities, MyBuiltinStyle.TableOfAuthorities },
      { WdBuiltinStyle.wdStyleMacroText, MyBuiltinStyle.Macro },
      { WdBuiltinStyle.wdStyleTOAHeading, MyBuiltinStyle.ToaHeading },
      { WdBuiltinStyle.wdStyleList, MyBuiltinStyle.List },
      { WdBuiltinStyle.wdStyleListBullet, MyBuiltinStyle.ListBullet },
      { WdBuiltinStyle.wdStyleListNumber, MyBuiltinStyle.ListNumber },
      { WdBuiltinStyle.wdStyleList2, MyBuiltinStyle.List2 },
      { WdBuiltinStyle.wdStyleList3, MyBuiltinStyle.List3 },
      { WdBuiltinStyle.wdStyleList4, MyBuiltinStyle.List4 },
      { WdBuiltinStyle.wdStyleList5, MyBuiltinStyle.List5 },
      { WdBuiltinStyle.wdStyleListBullet2, MyBuiltinStyle.ListBullet2 },
      { WdBuiltinStyle.wdStyleListBullet3, MyBuiltinStyle.ListBullet3 },
      { WdBuiltinStyle.wdStyleListBullet4, MyBuiltinStyle.ListBullet4 },
      { WdBuiltinStyle.wdStyleListBullet5, MyBuiltinStyle.ListBullet5 },
      { WdBuiltinStyle.wdStyleListNumber2, MyBuiltinStyle.ListNumber2 },
      { WdBuiltinStyle.wdStyleListNumber3, MyBuiltinStyle.ListNumber3 },
      { WdBuiltinStyle.wdStyleListNumber4, MyBuiltinStyle.ListNumber4 },
      { WdBuiltinStyle.wdStyleListNumber5, MyBuiltinStyle.ListNumber5 },
      { WdBuiltinStyle.wdStyleTitle, MyBuiltinStyle.Title },
      { WdBuiltinStyle.wdStyleClosing, MyBuiltinStyle.Closing },
      { WdBuiltinStyle.wdStyleSignature, MyBuiltinStyle.Signature },
      { WdBuiltinStyle.wdStyleDefaultParagraphFont, MyBuiltinStyle.DefaultParagraphFont },
      { WdBuiltinStyle.wdStyleBodyText, MyBuiltinStyle.BodyText },
      { WdBuiltinStyle.wdStyleBodyTextIndent, MyBuiltinStyle.BodyTextIndent },
      { WdBuiltinStyle.wdStyleListContinue, MyBuiltinStyle.ListContinue },
      { WdBuiltinStyle.wdStyleListContinue2, MyBuiltinStyle.ListContinue2 },
      { WdBuiltinStyle.wdStyleListContinue3, MyBuiltinStyle.ListContinue3 },
      { WdBuiltinStyle.wdStyleListContinue4, MyBuiltinStyle.ListContinue4 },
      { WdBuiltinStyle.wdStyleListContinue5, MyBuiltinStyle.ListContinue5 },
      { WdBuiltinStyle.wdStyleMessageHeader, MyBuiltinStyle.MessageHeader },
      { WdBuiltinStyle.wdStyleSubtitle, MyBuiltinStyle.Subtitle },
      { WdBuiltinStyle.wdStyleSalutation, MyBuiltinStyle.Salutation },
      { WdBuiltinStyle.wdStyleDate, MyBuiltinStyle.Date },
      { WdBuiltinStyle.wdStyleBodyTextFirstIndent, MyBuiltinStyle.BodyTextFirstIndent },
      { WdBuiltinStyle.wdStyleBodyTextFirstIndent2, MyBuiltinStyle.BodyTextFirstIndent2 },
      { WdBuiltinStyle.wdStyleNoteHeading, MyBuiltinStyle.NoteHeading },
      { WdBuiltinStyle.wdStyleBodyText2, MyBuiltinStyle.BodyText2 },
      { WdBuiltinStyle.wdStyleBodyText3, MyBuiltinStyle.BodyText3 },
      { WdBuiltinStyle.wdStyleBodyTextIndent2, MyBuiltinStyle.BodyTextIndent2 },
      { WdBuiltinStyle.wdStyleBodyTextIndent3, MyBuiltinStyle.BodyTextIndent3 },
      { WdBuiltinStyle.wdStyleBlockQuotation, MyBuiltinStyle.BlockText },
      { WdBuiltinStyle.wdStyleHyperlink, MyBuiltinStyle.Hyperlink },
      { WdBuiltinStyle.wdStyleHyperlinkFollowed, MyBuiltinStyle.FollowedHyperlink },
      { WdBuiltinStyle.wdStyleStrong, MyBuiltinStyle.Strong },
      { WdBuiltinStyle.wdStyleEmphasis, MyBuiltinStyle.Emphasis },
      { WdBuiltinStyle.wdStyleNavPane, MyBuiltinStyle.DocumentMap },
      { WdBuiltinStyle.wdStylePlainText, MyBuiltinStyle.PlainText },
      { WdBuiltinStyle.wdStyleHtmlNormal, MyBuiltinStyle.HtmlNormal },
      { WdBuiltinStyle.wdStyleHtmlAcronym, MyBuiltinStyle.HtmlAcronym },
      { WdBuiltinStyle.wdStyleHtmlAddress, MyBuiltinStyle.HtmlAddress },
      { WdBuiltinStyle.wdStyleHtmlCite, MyBuiltinStyle.HtmlCite },
      { WdBuiltinStyle.wdStyleHtmlCode, MyBuiltinStyle.HtmlCode },
      { WdBuiltinStyle.wdStyleHtmlDfn, MyBuiltinStyle.HtmlDefinition },
      { WdBuiltinStyle.wdStyleHtmlKbd, MyBuiltinStyle.HtmlKeyboard },
      { WdBuiltinStyle.wdStyleHtmlPre, MyBuiltinStyle.HtmlPreformatted },
      { WdBuiltinStyle.wdStyleHtmlSamp, MyBuiltinStyle.HtmlSample },
      { WdBuiltinStyle.wdStyleHtmlTt, MyBuiltinStyle.HtmlTypewriter },
      { WdBuiltinStyle.wdStyleHtmlVar, MyBuiltinStyle.HtmlVariable },
      { WdBuiltinStyle.wdStyleNormalTable, MyBuiltinStyle.NormalTable },
      { WdBuiltinStyle.wdStyleNormalObject, MyBuiltinStyle.NoSpacing },
      { WdBuiltinStyle.wdStyleTableLightShading, MyBuiltinStyle.LightShading },
      { WdBuiltinStyle.wdStyleTableLightList, MyBuiltinStyle.LightList },
      { WdBuiltinStyle.wdStyleTableLightGrid, MyBuiltinStyle.LightGrid },
      { WdBuiltinStyle.wdStyleTableMediumShading1, MyBuiltinStyle.MediumShading1 },
      { WdBuiltinStyle.wdStyleTableMediumShading2, MyBuiltinStyle.MediumShading2 },
      { WdBuiltinStyle.wdStyleTableMediumList1, MyBuiltinStyle.MediumList1 },
      { WdBuiltinStyle.wdStyleTableMediumList2, MyBuiltinStyle.MediumList2 },
      { WdBuiltinStyle.wdStyleTableMediumGrid1, MyBuiltinStyle.MediumGrid1 },
      { WdBuiltinStyle.wdStyleTableMediumGrid2, MyBuiltinStyle.MediumGrid2 },
      { WdBuiltinStyle.wdStyleTableMediumGrid3, MyBuiltinStyle.MediumGrid3 },
      { WdBuiltinStyle.wdStyleTableDarkList, MyBuiltinStyle.DarkList },
      { WdBuiltinStyle.wdStyleTableColorfulShading, MyBuiltinStyle.ColorfulShading },
      { WdBuiltinStyle.wdStyleTableColorfulList, MyBuiltinStyle.ColorfulList },
      { WdBuiltinStyle.wdStyleTableColorfulGrid, MyBuiltinStyle.ColorfulGrid },
      { WdBuiltinStyle.wdStyleTableLightShadingAccent1, MyBuiltinStyle.LightShadingAccent1 },
      { WdBuiltinStyle.wdStyleTableLightListAccent1, MyBuiltinStyle.LightListAccent1 },
      { WdBuiltinStyle.wdStyleTableLightGridAccent1, MyBuiltinStyle.LightGridAccent1 },
      { WdBuiltinStyle.wdStyleTableMediumShading1Accent1, MyBuiltinStyle.MediumShading1Accent1 },
      { WdBuiltinStyle.wdStyleTableMediumShading2Accent1, MyBuiltinStyle.MediumShading2Accent1 },
      { WdBuiltinStyle.wdStyleTableMediumList1Accent1, MyBuiltinStyle.MediumList1Accent1 },
      { WdBuiltinStyle.wdStyleListParagraph, MyBuiltinStyle.Revision },
      { WdBuiltinStyle.wdStyleQuote, MyBuiltinStyle.ListParagraph },
      { WdBuiltinStyle.wdStyleIntenseQuote, MyBuiltinStyle.Quote },
      { WdBuiltinStyle.wdStyleSubtleEmphasis, MyBuiltinStyle.SubtleEmphasis },
      { WdBuiltinStyle.wdStyleIntenseEmphasis, MyBuiltinStyle.IntenseEmphasis },
      { WdBuiltinStyle.wdStyleSubtleReference, MyBuiltinStyle.SubtleReference },
      { WdBuiltinStyle.wdStyleIntenseReference, MyBuiltinStyle.IntenseReference },
      { WdBuiltinStyle.wdStyleBookTitle, MyBuiltinStyle.BookTitle },
      { WdBuiltinStyle.wdStyleBibliography, MyBuiltinStyle.Bibliography },
      { WdBuiltinStyle.wdStyleTocHeading, MyBuiltinStyle.TocHeading },
    };


    public static Dictionary<MyBuiltinStyle, WdBuiltinStyle> MyBuiltInStyleWdBuiltinStyles = new()
    {
      { MyBuiltinStyle.Normal, WdBuiltinStyle.wdStyleNormal },
      { MyBuiltinStyle.Heading1, WdBuiltinStyle.wdStyleHeading1 },
      { MyBuiltinStyle.Heading2, WdBuiltinStyle.wdStyleHeading2 },
      { MyBuiltinStyle.Heading3, WdBuiltinStyle.wdStyleHeading3 },
      { MyBuiltinStyle.Heading4, WdBuiltinStyle.wdStyleHeading4 },
      { MyBuiltinStyle.Heading5, WdBuiltinStyle.wdStyleHeading5 },
      { MyBuiltinStyle.Heading6, WdBuiltinStyle.wdStyleHeading6 },
      { MyBuiltinStyle.Heading7, WdBuiltinStyle.wdStyleHeading7 },
      { MyBuiltinStyle.Heading8, WdBuiltinStyle.wdStyleHeading8 },
      { MyBuiltinStyle.Heading9, WdBuiltinStyle.wdStyleHeading9 },
      { MyBuiltinStyle.Index1, WdBuiltinStyle.wdStyleIndex1 },
      { MyBuiltinStyle.Index2, WdBuiltinStyle.wdStyleIndex2 },
      { MyBuiltinStyle.Index3, WdBuiltinStyle.wdStyleIndex3 },
      { MyBuiltinStyle.Index4, WdBuiltinStyle.wdStyleIndex4 },
      { MyBuiltinStyle.Index5, WdBuiltinStyle.wdStyleIndex5 },
      { MyBuiltinStyle.Index6, WdBuiltinStyle.wdStyleIndex6 },
      { MyBuiltinStyle.Index7, WdBuiltinStyle.wdStyleIndex7 },
      { MyBuiltinStyle.Index8, WdBuiltinStyle.wdStyleIndex8 },
      { MyBuiltinStyle.Index9, WdBuiltinStyle.wdStyleIndex9 },
      { MyBuiltinStyle.Toc1, WdBuiltinStyle.wdStyleTOC1 },
      { MyBuiltinStyle.Toc2, WdBuiltinStyle.wdStyleTOC2 },
      { MyBuiltinStyle.Toc3, WdBuiltinStyle.wdStyleTOC3 },
      { MyBuiltinStyle.Toc4, WdBuiltinStyle.wdStyleTOC4 },
      { MyBuiltinStyle.Toc5, WdBuiltinStyle.wdStyleTOC5 },
      { MyBuiltinStyle.Toc6, WdBuiltinStyle.wdStyleTOC6 },
      { MyBuiltinStyle.Toc7, WdBuiltinStyle.wdStyleTOC7 },
      { MyBuiltinStyle.Toc8, WdBuiltinStyle.wdStyleTOC8 },
      { MyBuiltinStyle.Toc9, WdBuiltinStyle.wdStyleTOC9 },
      { MyBuiltinStyle.NormalIndent, WdBuiltinStyle.wdStyleNormalIndent },
      { MyBuiltinStyle.FootnoteText, WdBuiltinStyle.wdStyleFootnoteText },
      { MyBuiltinStyle.AnnotationText, WdBuiltinStyle.wdStyleCommentText },
      { MyBuiltinStyle.Header, WdBuiltinStyle.wdStyleHeader },
      { MyBuiltinStyle.Footer, WdBuiltinStyle.wdStyleFooter },
      { MyBuiltinStyle.IndexHeading, WdBuiltinStyle.wdStyleIndexHeading },
      { MyBuiltinStyle.Caption, WdBuiltinStyle.wdStyleCaption },
      { MyBuiltinStyle.TableOfFigures, WdBuiltinStyle.wdStyleTableOfFigures },
      { MyBuiltinStyle.EnvelopeAddress, WdBuiltinStyle.wdStyleEnvelopeAddress },
      { MyBuiltinStyle.EnvelopeReturn, WdBuiltinStyle.wdStyleEnvelopeReturn },
      { MyBuiltinStyle.FootnoteReference, WdBuiltinStyle.wdStyleFootnoteReference },
      { MyBuiltinStyle.AnnotationReference, WdBuiltinStyle.wdStyleCommentReference },
      { MyBuiltinStyle.LineNumber, WdBuiltinStyle.wdStyleLineNumber },
      { MyBuiltinStyle.PageNumber, WdBuiltinStyle.wdStylePageNumber },
      { MyBuiltinStyle.EndnoteReference, WdBuiltinStyle.wdStyleEndnoteReference },
      { MyBuiltinStyle.EndnoteText, WdBuiltinStyle.wdStyleEndnoteText },
      { MyBuiltinStyle.TableOfAuthorities, WdBuiltinStyle.wdStyleTableOfAuthorities },
      { MyBuiltinStyle.Macro, WdBuiltinStyle.wdStyleMacroText },
      { MyBuiltinStyle.ToaHeading, WdBuiltinStyle.wdStyleTOAHeading },
      { MyBuiltinStyle.List, WdBuiltinStyle.wdStyleList },
      { MyBuiltinStyle.ListBullet, WdBuiltinStyle.wdStyleListBullet },
      { MyBuiltinStyle.ListNumber, WdBuiltinStyle.wdStyleListNumber },
      { MyBuiltinStyle.List2, WdBuiltinStyle.wdStyleList2 },
      { MyBuiltinStyle.List3, WdBuiltinStyle.wdStyleList3 },
      { MyBuiltinStyle.List4, WdBuiltinStyle.wdStyleList4 },
      { MyBuiltinStyle.List5, WdBuiltinStyle.wdStyleList5 },
      { MyBuiltinStyle.ListBullet2, WdBuiltinStyle.wdStyleListBullet2 },
      { MyBuiltinStyle.ListBullet3, WdBuiltinStyle.wdStyleListBullet3 },
      { MyBuiltinStyle.ListBullet4, WdBuiltinStyle.wdStyleListBullet4 },
      { MyBuiltinStyle.ListBullet5, WdBuiltinStyle.wdStyleListBullet5 },
      { MyBuiltinStyle.ListNumber2, WdBuiltinStyle.wdStyleListNumber2 },
      { MyBuiltinStyle.ListNumber3, WdBuiltinStyle.wdStyleListNumber3 },
      { MyBuiltinStyle.ListNumber4, WdBuiltinStyle.wdStyleListNumber4 },
      { MyBuiltinStyle.ListNumber5, WdBuiltinStyle.wdStyleListNumber5 },
      { MyBuiltinStyle.Title, WdBuiltinStyle.wdStyleTitle },
      { MyBuiltinStyle.Closing, WdBuiltinStyle.wdStyleClosing },
      { MyBuiltinStyle.Signature, WdBuiltinStyle.wdStyleSignature },
      { MyBuiltinStyle.DefaultParagraphFont, WdBuiltinStyle.wdStyleDefaultParagraphFont },
      { MyBuiltinStyle.BodyText, WdBuiltinStyle.wdStyleBodyText },
      { MyBuiltinStyle.BodyTextIndent, WdBuiltinStyle.wdStyleBodyTextIndent },
      { MyBuiltinStyle.ListContinue, WdBuiltinStyle.wdStyleListContinue },
      { MyBuiltinStyle.ListContinue2, WdBuiltinStyle.wdStyleListContinue2 },
      { MyBuiltinStyle.ListContinue3, WdBuiltinStyle.wdStyleListContinue3 },
      { MyBuiltinStyle.ListContinue4, WdBuiltinStyle.wdStyleListContinue4 },
      { MyBuiltinStyle.ListContinue5, WdBuiltinStyle.wdStyleListContinue5 },
      { MyBuiltinStyle.MessageHeader, WdBuiltinStyle.wdStyleMessageHeader },
      { MyBuiltinStyle.Subtitle, WdBuiltinStyle.wdStyleSubtitle },
      { MyBuiltinStyle.Salutation, WdBuiltinStyle.wdStyleSalutation },
      { MyBuiltinStyle.Date, WdBuiltinStyle.wdStyleDate },
      { MyBuiltinStyle.BodyTextFirstIndent, WdBuiltinStyle.wdStyleBodyTextFirstIndent },
      { MyBuiltinStyle.BodyTextFirstIndent2, WdBuiltinStyle.wdStyleBodyTextFirstIndent2 },
      { MyBuiltinStyle.NoteHeading, WdBuiltinStyle.wdStyleNoteHeading },
      { MyBuiltinStyle.BodyText2, WdBuiltinStyle.wdStyleBodyText2 },
      { MyBuiltinStyle.BodyText3, WdBuiltinStyle.wdStyleBodyText3 },
      { MyBuiltinStyle.BodyTextIndent2, WdBuiltinStyle.wdStyleBodyTextIndent2 },
      { MyBuiltinStyle.BodyTextIndent3, WdBuiltinStyle.wdStyleBodyTextIndent3 },
      { MyBuiltinStyle.BlockText, WdBuiltinStyle.wdStyleBlockQuotation },
      { MyBuiltinStyle.Hyperlink, WdBuiltinStyle.wdStyleHyperlink },
      { MyBuiltinStyle.FollowedHyperlink, WdBuiltinStyle.wdStyleHyperlinkFollowed },
      { MyBuiltinStyle.Strong, WdBuiltinStyle.wdStyleStrong },
      { MyBuiltinStyle.Emphasis, WdBuiltinStyle.wdStyleEmphasis },
      { MyBuiltinStyle.DocumentMap, WdBuiltinStyle.wdStyleNavPane },
      { MyBuiltinStyle.PlainText, WdBuiltinStyle.wdStylePlainText },
      { MyBuiltinStyle.EMailSignature, 0 },
      { MyBuiltinStyle.HTMLTopOfForm, 0 },
      { MyBuiltinStyle.HTMLBottomOfForm, 0 },
      { MyBuiltinStyle.HtmlNormal, WdBuiltinStyle.wdStyleHtmlNormal },
      { MyBuiltinStyle.HtmlAcronym, WdBuiltinStyle.wdStyleHtmlAcronym },
      { MyBuiltinStyle.HtmlAddress, WdBuiltinStyle.wdStyleHtmlAddress },
      { MyBuiltinStyle.HtmlCite, WdBuiltinStyle.wdStyleHtmlCite },
      { MyBuiltinStyle.HtmlCode, WdBuiltinStyle.wdStyleHtmlCode },
      { MyBuiltinStyle.HtmlDefinition, WdBuiltinStyle.wdStyleHtmlDfn },
      { MyBuiltinStyle.HtmlKeyboard, WdBuiltinStyle.wdStyleHtmlKbd },
      { MyBuiltinStyle.HtmlPreformatted, WdBuiltinStyle.wdStyleHtmlPre },
      { MyBuiltinStyle.HtmlSample, WdBuiltinStyle.wdStyleHtmlSamp },
      { MyBuiltinStyle.HtmlTypewriter, WdBuiltinStyle.wdStyleHtmlTt },
      { MyBuiltinStyle.HtmlVariable, WdBuiltinStyle.wdStyleHtmlVar },
      { MyBuiltinStyle.NormalTable, WdBuiltinStyle.wdStyleNormalTable },
      { MyBuiltinStyle.AnnotationSubject, 0 },
      { MyBuiltinStyle.NoList, 0 },
      { MyBuiltinStyle.OutlineList1, 0 },
      { MyBuiltinStyle.OutlineList2, 0 },
      { MyBuiltinStyle.OutlineList3, 0 },
      { MyBuiltinStyle.TableSimple1, 0 },
      { MyBuiltinStyle.TableSimple2, 0 },
      { MyBuiltinStyle.TableSimple3, 0 },
      { MyBuiltinStyle.TableClassic1, 0 },
      { MyBuiltinStyle.TableClassic2, 0 },
      { MyBuiltinStyle.TableClassic3, 0 },
      { MyBuiltinStyle.TableClassic4, 0 },
      { MyBuiltinStyle.TableColorful1, 0 },
      { MyBuiltinStyle.TableColorful2, 0 },
      { MyBuiltinStyle.TableColorful3, 0 },
      { MyBuiltinStyle.TableColumns1, 0 },
      { MyBuiltinStyle.TableColumns2, 0 },
      { MyBuiltinStyle.TableColumns3, 0 },
      { MyBuiltinStyle.TableColumns4, 0 },
      { MyBuiltinStyle.TableColumns5, 0 },
      { MyBuiltinStyle.TableGrid1, 0 },
      { MyBuiltinStyle.TableGrid2, 0 },
      { MyBuiltinStyle.TableGrid3, 0 },
      { MyBuiltinStyle.TableGrid4, 0 },
      { MyBuiltinStyle.TableGrid5, 0 },
      { MyBuiltinStyle.TableGrid6, 0 },
      { MyBuiltinStyle.TableGrid7, 0 },
      { MyBuiltinStyle.TableGrid8, 0 },
      { MyBuiltinStyle.TableList1, 0 },
      { MyBuiltinStyle.TableList2, 0 },
      { MyBuiltinStyle.TableList3, 0 },
      { MyBuiltinStyle.TableList4, 0 },
      { MyBuiltinStyle.TableList5, 0 },
      { MyBuiltinStyle.TableList6, 0 },
      { MyBuiltinStyle.TableList7, 0 },
      { MyBuiltinStyle.TableList8, 0 },
      { MyBuiltinStyle.Table3DEffects1, 0 },
      { MyBuiltinStyle.Table3DEffects2, 0 },
      { MyBuiltinStyle.Table3DEffects3, 0 },
      { MyBuiltinStyle.TableContemporary, 0 },
      { MyBuiltinStyle.TableElegant, 0 },
      { MyBuiltinStyle.TableProfessional, 0 },
      { MyBuiltinStyle.TableSubtle1, 0 },
      { MyBuiltinStyle.TableSubtle2, 0 },
      { MyBuiltinStyle.TableWeb1, 0 },
      { MyBuiltinStyle.TableWeb2, 0 },
      { MyBuiltinStyle.TableWeb3, 0 },
      { MyBuiltinStyle.BalloonText, 0 },
      { MyBuiltinStyle.TableGrid, 0 },
      { MyBuiltinStyle.TableTheme, 0 },
      { MyBuiltinStyle.PlaceholderText, 0 },
      { MyBuiltinStyle.NoSpacing, WdBuiltinStyle.wdStyleNormalObject },
      { MyBuiltinStyle.LightShading, WdBuiltinStyle.wdStyleTableLightShading },
      { MyBuiltinStyle.LightList, WdBuiltinStyle.wdStyleTableLightList },
      { MyBuiltinStyle.LightGrid, WdBuiltinStyle.wdStyleTableLightGrid },
      { MyBuiltinStyle.MediumShading1, WdBuiltinStyle.wdStyleTableMediumShading1 },
      { MyBuiltinStyle.MediumShading2, WdBuiltinStyle.wdStyleTableMediumShading2 },
      { MyBuiltinStyle.MediumList1, WdBuiltinStyle.wdStyleTableMediumList1 },
      { MyBuiltinStyle.MediumList2, WdBuiltinStyle.wdStyleTableMediumList2 },
      { MyBuiltinStyle.MediumGrid1, WdBuiltinStyle.wdStyleTableMediumGrid1 },
      { MyBuiltinStyle.MediumGrid2, WdBuiltinStyle.wdStyleTableMediumGrid2 },
      { MyBuiltinStyle.MediumGrid3, WdBuiltinStyle.wdStyleTableMediumGrid3 },
      { MyBuiltinStyle.DarkList, WdBuiltinStyle.wdStyleTableDarkList },
      { MyBuiltinStyle.ColorfulShading, WdBuiltinStyle.wdStyleTableColorfulShading },
      { MyBuiltinStyle.ColorfulList, WdBuiltinStyle.wdStyleTableColorfulList },
      { MyBuiltinStyle.ColorfulGrid, WdBuiltinStyle.wdStyleTableColorfulGrid },
      { MyBuiltinStyle.LightShadingAccent1, WdBuiltinStyle.wdStyleTableLightShadingAccent1 },
      { MyBuiltinStyle.LightListAccent1, WdBuiltinStyle.wdStyleTableLightListAccent1 },
      { MyBuiltinStyle.LightGridAccent1, WdBuiltinStyle.wdStyleTableLightGridAccent1 },
      { MyBuiltinStyle.MediumShading1Accent1, WdBuiltinStyle.wdStyleTableMediumShading1Accent1 },
      { MyBuiltinStyle.MediumShading2Accent1, WdBuiltinStyle.wdStyleTableMediumShading2Accent1 },
      { MyBuiltinStyle.MediumList1Accent1, WdBuiltinStyle.wdStyleTableMediumList1Accent1 },
      { MyBuiltinStyle.Revision, WdBuiltinStyle.wdStyleListParagraph },
      { MyBuiltinStyle.ListParagraph, WdBuiltinStyle.wdStyleQuote },
      { MyBuiltinStyle.Quote, WdBuiltinStyle.wdStyleIntenseQuote },
      { MyBuiltinStyle.IntenseQuote, 0 },
      { MyBuiltinStyle.MediumList2Accent1, 0 },
      { MyBuiltinStyle.MediumGrid1Accent1, 0 },
      { MyBuiltinStyle.MediumGrid2Accent1, 0 },
      { MyBuiltinStyle.MediumGrid3Accent1, 0 },
      { MyBuiltinStyle.DarkListAccent1, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent1, 0 },
      { MyBuiltinStyle.ColorfulListAccent1, 0 },
      { MyBuiltinStyle.ColorfulGridAccent1, 0 },
      { MyBuiltinStyle.LightShadingAccent2, 0 },
      { MyBuiltinStyle.LightListAccent2, 0 },
      { MyBuiltinStyle.LightGridAccent2, 0 },
      { MyBuiltinStyle.MediumShading1Accent2, 0 },
      { MyBuiltinStyle.MediumShading2Accent2, 0 },
      { MyBuiltinStyle.MediumList1Accent2, 0 },
      { MyBuiltinStyle.MediumList2Accent2, 0 },
      { MyBuiltinStyle.MediumGrid1Accent2, 0 },
      { MyBuiltinStyle.MediumGrid2Accent2, 0 },
      { MyBuiltinStyle.MediumGrid3Accent2, 0 },
      { MyBuiltinStyle.DarkListAccent2, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent2, 0 },
      { MyBuiltinStyle.ColorfulListAccent2, 0 },
      { MyBuiltinStyle.ColorfulGridAccent2, 0 },
      { MyBuiltinStyle.LightShadingAccent3, 0 },
      { MyBuiltinStyle.LightListAccent3, 0 },
      { MyBuiltinStyle.LightGridAccent3, 0 },
      { MyBuiltinStyle.MediumShading1Accent3, 0 },
      { MyBuiltinStyle.MediumShading2Accent3, 0 },
      { MyBuiltinStyle.MediumList1Accent3, 0 },
      { MyBuiltinStyle.MediumList2Accent3, 0 },
      { MyBuiltinStyle.MediumGrid1Accent3, 0 },
      { MyBuiltinStyle.MediumGrid2Accent3, 0 },
      { MyBuiltinStyle.MediumGrid3Accent3, 0 },
      { MyBuiltinStyle.DarkListAccent3, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent3, 0 },
      { MyBuiltinStyle.ColorfulListAccent3, 0 },
      { MyBuiltinStyle.ColorfulGridAccent3, 0 },
      { MyBuiltinStyle.LightShadingAccent4, 0 },
      { MyBuiltinStyle.LightListAccent4, 0 },
      { MyBuiltinStyle.LightGridAccent4, 0 },
      { MyBuiltinStyle.MediumShading1Accent4, 0 },
      { MyBuiltinStyle.MediumShading2Accent4, 0 },
      { MyBuiltinStyle.MediumList1Accent4, 0 },
      { MyBuiltinStyle.MediumList2Accent4, 0 },
      { MyBuiltinStyle.MediumGrid1Accent4, 0 },
      { MyBuiltinStyle.MediumGrid2Accent4, 0 },
      { MyBuiltinStyle.MediumGrid3Accent4, 0 },
      { MyBuiltinStyle.DarkListAccent4, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent4, 0 },
      { MyBuiltinStyle.ColorfulListAccent4, 0 },
      { MyBuiltinStyle.ColorfulGridAccent4, 0 },
      { MyBuiltinStyle.LightShadingAccent5, 0 },
      { MyBuiltinStyle.LightListAccent5, 0 },
      { MyBuiltinStyle.LightGridAccent5, 0 },
      { MyBuiltinStyle.MediumShading1Accent5, 0 },
      { MyBuiltinStyle.MediumShading2Accent5, 0 },
      { MyBuiltinStyle.MediumList1Accent5, 0 },
      { MyBuiltinStyle.MediumList2Accent5, 0 },
      { MyBuiltinStyle.MediumGrid1Accent5, 0 },
      { MyBuiltinStyle.MediumGrid2Accent5, 0 },
      { MyBuiltinStyle.MediumGrid3Accent5, 0 },
      { MyBuiltinStyle.DarkListAccent5, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent5, 0 },
      { MyBuiltinStyle.ColorfulListAccent5, 0 },
      { MyBuiltinStyle.ColorfulGridAccent5, 0 },
      { MyBuiltinStyle.LightShadingAccent6, 0 },
      { MyBuiltinStyle.LightListAccent6, 0 },
      { MyBuiltinStyle.LightGridAccent6, 0 },
      { MyBuiltinStyle.MediumShading1Accent6, 0 },
      { MyBuiltinStyle.MediumShading2Accent6, 0 },
      { MyBuiltinStyle.MediumList1Accent6, 0 },
      { MyBuiltinStyle.MediumList2Accent6, 0 },
      { MyBuiltinStyle.MediumGrid1Accent6, 0 },
      { MyBuiltinStyle.MediumGrid2Accent6, 0 },
      { MyBuiltinStyle.MediumGrid3Accent6, 0 },
      { MyBuiltinStyle.DarkListAccent6, 0 },
      { MyBuiltinStyle.ColorfulShadingAccent6, 0 },
      { MyBuiltinStyle.ColorfulListAccent6, 0 },
      { MyBuiltinStyle.ColorfulGridAccent6, 0 },
      { MyBuiltinStyle.SubtleEmphasis, WdBuiltinStyle.wdStyleSubtleEmphasis },
      { MyBuiltinStyle.IntenseEmphasis, WdBuiltinStyle.wdStyleIntenseEmphasis },
      { MyBuiltinStyle.SubtleReference, WdBuiltinStyle.wdStyleSubtleReference },
      { MyBuiltinStyle.IntenseReference, WdBuiltinStyle.wdStyleIntenseReference },
      { MyBuiltinStyle.BookTitle, WdBuiltinStyle.wdStyleBookTitle },
      { MyBuiltinStyle.Bibliography, WdBuiltinStyle.wdStyleBibliography },
      { MyBuiltinStyle.TocHeading, WdBuiltinStyle.wdStyleTocHeading },
      { MyBuiltinStyle.PlainTable1, 0 },
      { MyBuiltinStyle.PlainTable2, 0 },
      { MyBuiltinStyle.PlainTable3, 0 },
      { MyBuiltinStyle.PlainTable4, 0 },
      { MyBuiltinStyle.PlainTable5, 0 },
      { MyBuiltinStyle.GridTableLight, 0 },
      { MyBuiltinStyle.GridTable1Light, 0 },
      { MyBuiltinStyle.GridTable2, 0 },
      { MyBuiltinStyle.GridTable3, 0 },
      { MyBuiltinStyle.GridTable4, 0 },
      { MyBuiltinStyle.GridTable5Dark, 0 },
      { MyBuiltinStyle.GridTable6Colorful, 0 },
      { MyBuiltinStyle.GridTable7Colorful, 0 },
      { MyBuiltinStyle.GridTable1LightAccent1, 0 },
      { MyBuiltinStyle.GridTable2Accent1, 0 },
      { MyBuiltinStyle.GridTable3Accent1, 0 },
      { MyBuiltinStyle.GridTable4Accent1, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent1, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent1, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent1, 0 },
      { MyBuiltinStyle.GridTable1LightAccent2, 0 },
      { MyBuiltinStyle.GridTable2Accent2, 0 },
      { MyBuiltinStyle.GridTable3Accent2, 0 },
      { MyBuiltinStyle.GridTable4Accent2, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent2, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent2, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent2, 0 },
      { MyBuiltinStyle.GridTable1LightAccent3, 0 },
      { MyBuiltinStyle.GridTable2Accent3, 0 },
      { MyBuiltinStyle.GridTable3Accent3, 0 },
      { MyBuiltinStyle.GridTable4Accent3, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent3, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent3, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent3, 0 },
      { MyBuiltinStyle.GridTable1LightAccent4, 0 },
      { MyBuiltinStyle.GridTable2Accent4, 0 },
      { MyBuiltinStyle.GridTable3Accent4, 0 },
      { MyBuiltinStyle.GridTable4Accent4, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent4, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent4, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent4, 0 },
      { MyBuiltinStyle.GridTable1LightAccent5, 0 },
      { MyBuiltinStyle.GridTable2Accent5, 0 },
      { MyBuiltinStyle.GridTable3Accent5, 0 },
      { MyBuiltinStyle.GridTable4Accent5, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent5, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent5, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent5, 0 },
      { MyBuiltinStyle.GridTable1LightAccent6, 0 },
      { MyBuiltinStyle.GridTable2Accent6, 0 },
      { MyBuiltinStyle.GridTable3Accent6, 0 },
      { MyBuiltinStyle.GridTable4Accent6, 0 },
      { MyBuiltinStyle.GridTable5DarkAccent6, 0 },
      { MyBuiltinStyle.GridTable6ColorfulAccent6, 0 },
      { MyBuiltinStyle.GridTable7ColorfulAccent6, 0 },
      { MyBuiltinStyle.ListTable1Light, 0 },
      { MyBuiltinStyle.ListTable2, 0 },
      { MyBuiltinStyle.ListTable3, 0 },
      { MyBuiltinStyle.ListTable4, 0 },
      { MyBuiltinStyle.ListTable5Dark, 0 },
      { MyBuiltinStyle.ListTable6Colorful, 0 },
      { MyBuiltinStyle.ListTable7Colorful, 0 },
      { MyBuiltinStyle.ListTable1LightAccent1, 0 },
      { MyBuiltinStyle.ListTable2Accent1, 0 },
      { MyBuiltinStyle.ListTable3Accent1, 0 },
      { MyBuiltinStyle.ListTable4Accent1, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent1, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent1, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent1, 0 },
      { MyBuiltinStyle.ListTable1LightAccent2, 0 },
      { MyBuiltinStyle.ListTable2Accent2, 0 },
      { MyBuiltinStyle.ListTable3Accent2, 0 },
      { MyBuiltinStyle.ListTable4Accent2, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent2, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent2, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent2, 0 },
      { MyBuiltinStyle.ListTable1LightAccent3, 0 },
      { MyBuiltinStyle.ListTable2Accent3, 0 },
      { MyBuiltinStyle.ListTable3Accent3, 0 },
      { MyBuiltinStyle.ListTable4Accent3, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent3, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent3, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent3, 0 },
      { MyBuiltinStyle.ListTable1LightAccent4, 0 },
      { MyBuiltinStyle.ListTable2Accent4, 0 },
      { MyBuiltinStyle.ListTable3Accent4, 0 },
      { MyBuiltinStyle.ListTable4Accent4, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent4, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent4, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent4, 0 },
      { MyBuiltinStyle.ListTable1LightAccent5, 0 },
      { MyBuiltinStyle.ListTable2Accent5, 0 },
      { MyBuiltinStyle.ListTable3Accent5, 0 },
      { MyBuiltinStyle.ListTable4Accent5, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent5, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent5, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent5, 0 },
      { MyBuiltinStyle.ListTable1LightAccent6, 0 },
      { MyBuiltinStyle.ListTable2Accent6, 0 },
      { MyBuiltinStyle.ListTable3Accent6, 0 },
      { MyBuiltinStyle.ListTable4Accent6, 0 },
      { MyBuiltinStyle.ListTable5DarkAccent6, 0 },
      { MyBuiltinStyle.ListTable6ColorfulAccent6, 0 },
      { MyBuiltinStyle.ListTable7ColorfulAccent6, 0 },
      { MyBuiltinStyle.Mention, 0 },
      { MyBuiltinStyle.SmartHyperlink, 0 },
      { MyBuiltinStyle.Hashtag, 0 },
      { MyBuiltinStyle.UnresolvedMention, 0 },
      { MyBuiltinStyle.SmartLink, 0 },
    };

    public Dictionary<string, MyBuiltinStyle> BuiltinNameMyBuiltinStyles = new()
    {
      { "Normal", MyBuiltinStyle.Normal },
      { "heading 1", MyBuiltinStyle.Heading1 },
      { "heading 2", MyBuiltinStyle.Heading2 },
      { "heading 3", MyBuiltinStyle.Heading3 },
      { "heading 4", MyBuiltinStyle.Heading4 },
      { "heading 5", MyBuiltinStyle.Heading5 },
      { "heading 6", MyBuiltinStyle.Heading6 },
      { "heading 7", MyBuiltinStyle.Heading7 },
      { "heading 8", MyBuiltinStyle.Heading8 },
      { "heading 9", MyBuiltinStyle.Heading9 },
      { "index 1", MyBuiltinStyle.Index1 },
      { "index 2", MyBuiltinStyle.Index2 },
      { "index 3", MyBuiltinStyle.Index3 },
      { "index 4", MyBuiltinStyle.Index4 },
      { "index 5", MyBuiltinStyle.Index5 },
      { "index 6", MyBuiltinStyle.Index6 },
      { "index 7", MyBuiltinStyle.Index7 },
      { "index 8", MyBuiltinStyle.Index8 },
      { "index 9", MyBuiltinStyle.Index9 },
      { "toc 1", MyBuiltinStyle.Toc1 },
      { "toc 2", MyBuiltinStyle.Toc2 },
      { "toc 3", MyBuiltinStyle.Toc3 },
      { "toc 4", MyBuiltinStyle.Toc4 },
      { "toc 5", MyBuiltinStyle.Toc5 },
      { "toc 6", MyBuiltinStyle.Toc6 },
      { "toc 7", MyBuiltinStyle.Toc7 },
      { "toc 8", MyBuiltinStyle.Toc8 },
      { "toc 9", MyBuiltinStyle.Toc9 },
      { "Normal Indent", MyBuiltinStyle.NormalIndent },
      { "footnote text", MyBuiltinStyle.FootnoteText },
      { "annotation text", MyBuiltinStyle.AnnotationText },
      { "header", MyBuiltinStyle.Header },
      { "footer", MyBuiltinStyle.Footer },
      { "index heading", MyBuiltinStyle.IndexHeading },
      { "caption", MyBuiltinStyle.Caption },
      { "table of figures", MyBuiltinStyle.TableOfFigures },
      { "envelope address", MyBuiltinStyle.EnvelopeAddress },
      { "envelope return", MyBuiltinStyle.EnvelopeReturn },
      { "footnote reference", MyBuiltinStyle.FootnoteReference },
      { "annotation reference", MyBuiltinStyle.AnnotationReference },
      { "line number", MyBuiltinStyle.LineNumber },
      { "page number", MyBuiltinStyle.PageNumber },
      { "endnote reference", MyBuiltinStyle.EndnoteReference },
      { "endnote text", MyBuiltinStyle.EndnoteText },
      { "table of authorities", MyBuiltinStyle.TableOfAuthorities },
      { "macro", MyBuiltinStyle.Macro },
      { "toa heading", MyBuiltinStyle.ToaHeading },
      { "List", MyBuiltinStyle.List },
      { "List Bullet", MyBuiltinStyle.ListBullet },
      { "List Number", MyBuiltinStyle.ListNumber },
      { "List 2", MyBuiltinStyle.List2 },
      { "List 3", MyBuiltinStyle.List3 },
      { "List 4", MyBuiltinStyle.List4 },
      { "List 5", MyBuiltinStyle.List5 },
      { "List Bullet 2", MyBuiltinStyle.ListBullet2 },
      { "List Bullet 3", MyBuiltinStyle.ListBullet3 },
      { "List Bullet 4", MyBuiltinStyle.ListBullet4 },
      { "List Bullet 5", MyBuiltinStyle.ListBullet5 },
      { "List Number 2", MyBuiltinStyle.ListNumber2 },
      { "List Number 3", MyBuiltinStyle.ListNumber3 },
      { "List Number 4", MyBuiltinStyle.ListNumber4 },
      { "List Number 5", MyBuiltinStyle.ListNumber5 },
      { "Title", MyBuiltinStyle.Title },
      { "Closing", MyBuiltinStyle.Closing },
      { "Signature", MyBuiltinStyle.Signature },
      { "Default Paragraph Font", MyBuiltinStyle.DefaultParagraphFont },
      { "Body Text", MyBuiltinStyle.BodyText },
      { "Body Text Indent", MyBuiltinStyle.BodyTextIndent },
      { "List Continue", MyBuiltinStyle.ListContinue },
      { "List Continue 2", MyBuiltinStyle.ListContinue2 },
      { "List Continue 3", MyBuiltinStyle.ListContinue3 },
      { "List Continue 4", MyBuiltinStyle.ListContinue4 },
      { "List Continue 5", MyBuiltinStyle.ListContinue5 },
      { "Message Header", MyBuiltinStyle.MessageHeader },
      { "Subtitle", MyBuiltinStyle.Subtitle },
      { "Salutation", MyBuiltinStyle.Salutation },
      { "Date", MyBuiltinStyle.Date },
      { "Body Text First Indent", MyBuiltinStyle.BodyTextFirstIndent },
      { "Body Text First Indent 2", MyBuiltinStyle.BodyTextFirstIndent2 },
      { "Note Heading", MyBuiltinStyle.NoteHeading },
      { "Body Text 2", MyBuiltinStyle.BodyText2 },
      { "Body Text 3", MyBuiltinStyle.BodyText3 },
      { "Body Text Indent 2", MyBuiltinStyle.BodyTextIndent2 },
      { "Body Text Indent 3", MyBuiltinStyle.BodyTextIndent3 },
      { "Block Text", MyBuiltinStyle.BlockText },
      { "Hyperlink", MyBuiltinStyle.Hyperlink },
      { "FollowedHyperlink", MyBuiltinStyle.FollowedHyperlink },
      { "Strong", MyBuiltinStyle.Strong },
      { "Emphasis", MyBuiltinStyle.Emphasis },
      { "Document Map", MyBuiltinStyle.DocumentMap },
      { "Plain Text", MyBuiltinStyle.PlainText },
      { "E-mail Signature", MyBuiltinStyle.EMailSignature },
      { "HTML Top of Form", MyBuiltinStyle.HTMLTopOfForm },
      { "HTML Bottom of Form", MyBuiltinStyle.HTMLBottomOfForm },
      { "Normal (Web)", MyBuiltinStyle.HtmlNormal },
      { "HTML Acronym", MyBuiltinStyle.HtmlAcronym },
      { "HTML Address", MyBuiltinStyle.HtmlAddress },
      { "HTML Cite", MyBuiltinStyle.HtmlCite },
      { "HTML Code", MyBuiltinStyle.HtmlCode },
      { "HTML Definition", MyBuiltinStyle.HtmlDefinition },
      { "HTML Keyboard", MyBuiltinStyle.HtmlKeyboard },
      { "HTML Preformatted", MyBuiltinStyle.HtmlPreformatted },
      { "HTML Sample", MyBuiltinStyle.HtmlSample },
      { "HTML Typewriter", MyBuiltinStyle.HtmlTypewriter },
      { "HTML Variable", MyBuiltinStyle.HtmlVariable },
      { "Normal Table", MyBuiltinStyle.NormalTable },
      { "annotation subject", MyBuiltinStyle.AnnotationSubject },
      { "No List", MyBuiltinStyle.NoList },
      { "Outline List 1", MyBuiltinStyle.OutlineList1 },
      { "Outline List 2", MyBuiltinStyle.OutlineList2 },
      { "Outline List 3", MyBuiltinStyle.OutlineList3 },
      { "Table Simple 1", MyBuiltinStyle.TableSimple1 },
      { "Table Simple 2", MyBuiltinStyle.TableSimple2 },
      { "Table Simple 3", MyBuiltinStyle.TableSimple3 },
      { "Table Classic 1", MyBuiltinStyle.TableClassic1 },
      { "Table Classic 2", MyBuiltinStyle.TableClassic2 },
      { "Table Classic 3", MyBuiltinStyle.TableClassic3 },
      { "Table Classic 4", MyBuiltinStyle.TableClassic4 },
      { "Table Colorful 1", MyBuiltinStyle.TableColorful1 },
      { "Table Colorful 2", MyBuiltinStyle.TableColorful2 },
      { "Table Colorful 3", MyBuiltinStyle.TableColorful3 },
      { "Table Columns 1", MyBuiltinStyle.TableColumns1 },
      { "Table Columns 2", MyBuiltinStyle.TableColumns2 },
      { "Table Columns 3", MyBuiltinStyle.TableColumns3 },
      { "Table Columns 4", MyBuiltinStyle.TableColumns4 },
      { "Table Columns 5", MyBuiltinStyle.TableColumns5 },
      { "Table Grid 1", MyBuiltinStyle.TableGrid1 },
      { "Table Grid 2", MyBuiltinStyle.TableGrid2 },
      { "Table Grid 3", MyBuiltinStyle.TableGrid3 },
      { "Table Grid 4", MyBuiltinStyle.TableGrid4 },
      { "Table Grid 5", MyBuiltinStyle.TableGrid5 },
      { "Table Grid 6", MyBuiltinStyle.TableGrid6 },
      { "Table Grid 7", MyBuiltinStyle.TableGrid7 },
      { "Table Grid 8", MyBuiltinStyle.TableGrid8 },
      { "Table List 1", MyBuiltinStyle.TableList1 },
      { "Table List 2", MyBuiltinStyle.TableList2 },
      { "Table List 3", MyBuiltinStyle.TableList3 },
      { "Table List 4", MyBuiltinStyle.TableList4 },
      { "Table List 5", MyBuiltinStyle.TableList5 },
      { "Table List 6", MyBuiltinStyle.TableList6 },
      { "Table List 7", MyBuiltinStyle.TableList7 },
      { "Table List 8", MyBuiltinStyle.TableList8 },
      { "Table 3D effects 1", MyBuiltinStyle.Table3DEffects1 },
      { "Table 3D effects 2", MyBuiltinStyle.Table3DEffects2 },
      { "Table 3D effects 3", MyBuiltinStyle.Table3DEffects3 },
      { "Table Contemporary", MyBuiltinStyle.TableContemporary },
      { "Table Elegant", MyBuiltinStyle.TableElegant },
      { "Table Professional", MyBuiltinStyle.TableProfessional },
      { "Table Subtle 1", MyBuiltinStyle.TableSubtle1 },
      { "Table Subtle 2", MyBuiltinStyle.TableSubtle2 },
      { "Table Web 1", MyBuiltinStyle.TableWeb1 },
      { "Table Web 2", MyBuiltinStyle.TableWeb2 },
      { "Table Web 3", MyBuiltinStyle.TableWeb3 },
      { "Balloon Text", MyBuiltinStyle.BalloonText },
      { "Table Grid", MyBuiltinStyle.TableGrid },
      { "Table Theme", MyBuiltinStyle.TableTheme },
      { "Placeholder Text", MyBuiltinStyle.PlaceholderText },
      { "No Spacing", MyBuiltinStyle.NoSpacing },
      { "Light Shading", MyBuiltinStyle.LightShading },
      { "Light List", MyBuiltinStyle.LightList },
      { "Light Grid", MyBuiltinStyle.LightGrid },
      { "Medium Shading 1", MyBuiltinStyle.MediumShading1 },
      { "Medium Shading 2", MyBuiltinStyle.MediumShading2 },
      { "Medium List 1", MyBuiltinStyle.MediumList1 },
      { "Medium List 2", MyBuiltinStyle.MediumList2 },
      { "Medium Grid 1", MyBuiltinStyle.MediumGrid1 },
      { "Medium Grid 2", MyBuiltinStyle.MediumGrid2 },
      { "Medium Grid 3", MyBuiltinStyle.MediumGrid3 },
      { "Dark List", MyBuiltinStyle.DarkList },
      { "Colorful Shading", MyBuiltinStyle.ColorfulShading },
      { "Colorful List", MyBuiltinStyle.ColorfulList },
      { "Colorful Grid", MyBuiltinStyle.ColorfulGrid },
      { "Light Shading Accent 1", MyBuiltinStyle.LightShadingAccent1 },
      { "Light List Accent 1", MyBuiltinStyle.LightListAccent1 },
      { "Light Grid Accent 1", MyBuiltinStyle.LightGridAccent1 },
      { "Medium Shading 1 Accent 1", MyBuiltinStyle.MediumShading1Accent1 },
      { "Medium Shading 2 Accent 1", MyBuiltinStyle.MediumShading2Accent1 },
      { "Medium List 1 Accent 1", MyBuiltinStyle.MediumList1Accent1 },
      { "Revision", MyBuiltinStyle.Revision },
      { "List Paragraph", MyBuiltinStyle.ListParagraph },
      { "Quote", MyBuiltinStyle.Quote },
      { "Intense Quote", MyBuiltinStyle.IntenseQuote },
      { "Medium List 2 Accent 1", MyBuiltinStyle.MediumList2Accent1 },
      { "Medium Grid 1 Accent 1", MyBuiltinStyle.MediumGrid1Accent1 },
      { "Medium Grid 2 Accent 1", MyBuiltinStyle.MediumGrid2Accent1 },
      { "Medium Grid 3 Accent 1", MyBuiltinStyle.MediumGrid3Accent1 },
      { "Dark List Accent 1", MyBuiltinStyle.DarkListAccent1 },
      { "Colorful Shading Accent 1", MyBuiltinStyle.ColorfulShadingAccent1 },
      { "Colorful List Accent 1", MyBuiltinStyle.ColorfulListAccent1 },
      { "Colorful Grid Accent 1", MyBuiltinStyle.ColorfulGridAccent1 },
      { "Light Shading Accent 2", MyBuiltinStyle.LightShadingAccent2 },
      { "Light List Accent 2", MyBuiltinStyle.LightListAccent2 },
      { "Light Grid Accent 2", MyBuiltinStyle.LightGridAccent2 },
      { "Medium Shading 1 Accent 2", MyBuiltinStyle.MediumShading1Accent2 },
      { "Medium Shading 2 Accent 2", MyBuiltinStyle.MediumShading2Accent2 },
      { "Medium List 1 Accent 2", MyBuiltinStyle.MediumList1Accent2 },
      { "Medium List 2 Accent 2", MyBuiltinStyle.MediumList2Accent2 },
      { "Medium Grid 1 Accent 2", MyBuiltinStyle.MediumGrid1Accent2 },
      { "Medium Grid 2 Accent 2", MyBuiltinStyle.MediumGrid2Accent2 },
      { "Medium Grid 3 Accent 2", MyBuiltinStyle.MediumGrid3Accent2 },
      { "Dark List Accent 2", MyBuiltinStyle.DarkListAccent2 },
      { "Colorful Shading Accent 2", MyBuiltinStyle.ColorfulShadingAccent2 },
      { "Colorful List Accent 2", MyBuiltinStyle.ColorfulListAccent2 },
      { "Colorful Grid Accent 2", MyBuiltinStyle.ColorfulGridAccent2 },
      { "Light Shading Accent 3", MyBuiltinStyle.LightShadingAccent3 },
      { "Light List Accent 3", MyBuiltinStyle.LightListAccent3 },
      { "Light Grid Accent 3", MyBuiltinStyle.LightGridAccent3 },
      { "Medium Shading 1 Accent 3", MyBuiltinStyle.MediumShading1Accent3 },
      { "Medium Shading 2 Accent 3", MyBuiltinStyle.MediumShading2Accent3 },
      { "Medium List 1 Accent 3", MyBuiltinStyle.MediumList1Accent3 },
      { "Medium List 2 Accent 3", MyBuiltinStyle.MediumList2Accent3 },
      { "Medium Grid 1 Accent 3", MyBuiltinStyle.MediumGrid1Accent3 },
      { "Medium Grid 2 Accent 3", MyBuiltinStyle.MediumGrid2Accent3 },
      { "Medium Grid 3 Accent 3", MyBuiltinStyle.MediumGrid3Accent3 },
      { "Dark List Accent 3", MyBuiltinStyle.DarkListAccent3 },
      { "Colorful Shading Accent 3", MyBuiltinStyle.ColorfulShadingAccent3 },
      { "Colorful List Accent 3", MyBuiltinStyle.ColorfulListAccent3 },
      { "Colorful Grid Accent 3", MyBuiltinStyle.ColorfulGridAccent3 },
      { "Light Shading Accent 4", MyBuiltinStyle.LightShadingAccent4 },
      { "Light List Accent 4", MyBuiltinStyle.LightListAccent4 },
      { "Light Grid Accent 4", MyBuiltinStyle.LightGridAccent4 },
      { "Medium Shading 1 Accent 4", MyBuiltinStyle.MediumShading1Accent4 },
      { "Medium Shading 2 Accent 4", MyBuiltinStyle.MediumShading2Accent4 },
      { "Medium List 1 Accent 4", MyBuiltinStyle.MediumList1Accent4 },
      { "Medium List 2 Accent 4", MyBuiltinStyle.MediumList2Accent4 },
      { "Medium Grid 1 Accent 4", MyBuiltinStyle.MediumGrid1Accent4 },
      { "Medium Grid 2 Accent 4", MyBuiltinStyle.MediumGrid2Accent4 },
      { "Medium Grid 3 Accent 4", MyBuiltinStyle.MediumGrid3Accent4 },
      { "Dark List Accent 4", MyBuiltinStyle.DarkListAccent4 },
      { "Colorful Shading Accent 4", MyBuiltinStyle.ColorfulShadingAccent4 },
      { "Colorful List Accent 4", MyBuiltinStyle.ColorfulListAccent4 },
      { "Colorful Grid Accent 4", MyBuiltinStyle.ColorfulGridAccent4 },
      { "Light Shading Accent 5", MyBuiltinStyle.LightShadingAccent5 },
      { "Light List Accent 5", MyBuiltinStyle.LightListAccent5 },
      { "Light Grid Accent 5", MyBuiltinStyle.LightGridAccent5 },
      { "Medium Shading 1 Accent 5", MyBuiltinStyle.MediumShading1Accent5 },
      { "Medium Shading 2 Accent 5", MyBuiltinStyle.MediumShading2Accent5 },
      { "Medium List 1 Accent 5", MyBuiltinStyle.MediumList1Accent5 },
      { "Medium List 2 Accent 5", MyBuiltinStyle.MediumList2Accent5 },
      { "Medium Grid 1 Accent 5", MyBuiltinStyle.MediumGrid1Accent5 },
      { "Medium Grid 2 Accent 5", MyBuiltinStyle.MediumGrid2Accent5 },
      { "Medium Grid 3 Accent 5", MyBuiltinStyle.MediumGrid3Accent5 },
      { "Dark List Accent 5", MyBuiltinStyle.DarkListAccent5 },
      { "Colorful Shading Accent 5", MyBuiltinStyle.ColorfulShadingAccent5 },
      { "Colorful List Accent 5", MyBuiltinStyle.ColorfulListAccent5 },
      { "Colorful Grid Accent 5", MyBuiltinStyle.ColorfulGridAccent5 },
      { "Light Shading Accent 6", MyBuiltinStyle.LightShadingAccent6 },
      { "Light List Accent 6", MyBuiltinStyle.LightListAccent6 },
      { "Light Grid Accent 6", MyBuiltinStyle.LightGridAccent6 },
      { "Medium Shading 1 Accent 6", MyBuiltinStyle.MediumShading1Accent6 },
      { "Medium Shading 2 Accent 6", MyBuiltinStyle.MediumShading2Accent6 },
      { "Medium List 1 Accent 6", MyBuiltinStyle.MediumList1Accent6 },
      { "Medium List 2 Accent 6", MyBuiltinStyle.MediumList2Accent6 },
      { "Medium Grid 1 Accent 6", MyBuiltinStyle.MediumGrid1Accent6 },
      { "Medium Grid 2 Accent 6", MyBuiltinStyle.MediumGrid2Accent6 },
      { "Medium Grid 3 Accent 6", MyBuiltinStyle.MediumGrid3Accent6 },
      { "Dark List Accent 6", MyBuiltinStyle.DarkListAccent6 },
      { "Colorful Shading Accent 6", MyBuiltinStyle.ColorfulShadingAccent6 },
      { "Colorful List Accent 6", MyBuiltinStyle.ColorfulListAccent6 },
      { "Colorful Grid Accent 6", MyBuiltinStyle.ColorfulGridAccent6 },
      { "Subtle Emphasis", MyBuiltinStyle.SubtleEmphasis },
      { "Intense Emphasis", MyBuiltinStyle.IntenseEmphasis },
      { "Subtle Reference", MyBuiltinStyle.SubtleReference },
      { "Intense Reference", MyBuiltinStyle.IntenseReference },
      { "Book Title", MyBuiltinStyle.BookTitle },
      { "Bibliography", MyBuiltinStyle.Bibliography },
      { "TOC Heading", MyBuiltinStyle.TocHeading },
      { "Plain Table 1", MyBuiltinStyle.PlainTable1 },
      { "Plain Table 2", MyBuiltinStyle.PlainTable2 },
      { "Plain Table 3", MyBuiltinStyle.PlainTable3 },
      { "Plain Table 4", MyBuiltinStyle.PlainTable4 },
      { "Plain Table 5", MyBuiltinStyle.PlainTable5 },
      { "Grid Table Light", MyBuiltinStyle.GridTableLight },
      { "Grid Table 1 Light", MyBuiltinStyle.GridTable1Light },
      { "Grid Table 2", MyBuiltinStyle.GridTable2 },
      { "Grid Table 3", MyBuiltinStyle.GridTable3 },
      { "Grid Table 4", MyBuiltinStyle.GridTable4 },
      { "Grid Table 5 Dark", MyBuiltinStyle.GridTable5Dark },
      { "Grid Table 6 Colorful", MyBuiltinStyle.GridTable6Colorful },
      { "Grid Table 7 Colorful", MyBuiltinStyle.GridTable7Colorful },
      { "Grid Table 1 Light Accent 1", MyBuiltinStyle.GridTable1LightAccent1 },
      { "Grid Table 2 Accent 1", MyBuiltinStyle.GridTable2Accent1 },
      { "Grid Table 3 Accent 1", MyBuiltinStyle.GridTable3Accent1 },
      { "Grid Table 4 Accent 1", MyBuiltinStyle.GridTable4Accent1 },
      { "Grid Table 5 Dark Accent 1", MyBuiltinStyle.GridTable5DarkAccent1 },
      { "Grid Table 6 Colorful Accent 1", MyBuiltinStyle.GridTable6ColorfulAccent1 },
      { "Grid Table 7 Colorful Accent 1", MyBuiltinStyle.GridTable7ColorfulAccent1 },
      { "Grid Table 1 Light Accent 2", MyBuiltinStyle.GridTable1LightAccent2 },
      { "Grid Table 2 Accent 2", MyBuiltinStyle.GridTable2Accent2 },
      { "Grid Table 3 Accent 2", MyBuiltinStyle.GridTable3Accent2 },
      { "Grid Table 4 Accent 2", MyBuiltinStyle.GridTable4Accent2 },
      { "Grid Table 5 Dark Accent 2", MyBuiltinStyle.GridTable5DarkAccent2 },
      { "Grid Table 6 Colorful Accent 2", MyBuiltinStyle.GridTable6ColorfulAccent2 },
      { "Grid Table 7 Colorful Accent 2", MyBuiltinStyle.GridTable7ColorfulAccent2 },
      { "Grid Table 1 Light Accent 3", MyBuiltinStyle.GridTable1LightAccent3 },
      { "Grid Table 2 Accent 3", MyBuiltinStyle.GridTable2Accent3 },
      { "Grid Table 3 Accent 3", MyBuiltinStyle.GridTable3Accent3 },
      { "Grid Table 4 Accent 3", MyBuiltinStyle.GridTable4Accent3 },
      { "Grid Table 5 Dark Accent 3", MyBuiltinStyle.GridTable5DarkAccent3 },
      { "Grid Table 6 Colorful Accent 3", MyBuiltinStyle.GridTable6ColorfulAccent3 },
      { "Grid Table 7 Colorful Accent 3", MyBuiltinStyle.GridTable7ColorfulAccent3 },
      { "Grid Table 1 Light Accent 4", MyBuiltinStyle.GridTable1LightAccent4 },
      { "Grid Table 2 Accent 4", MyBuiltinStyle.GridTable2Accent4 },
      { "Grid Table 3 Accent 4", MyBuiltinStyle.GridTable3Accent4 },
      { "Grid Table 4 Accent 4", MyBuiltinStyle.GridTable4Accent4 },
      { "Grid Table 5 Dark Accent 4", MyBuiltinStyle.GridTable5DarkAccent4 },
      { "Grid Table 6 Colorful Accent 4", MyBuiltinStyle.GridTable6ColorfulAccent4 },
      { "Grid Table 7 Colorful Accent 4", MyBuiltinStyle.GridTable7ColorfulAccent4 },
      { "Grid Table 1 Light Accent 5", MyBuiltinStyle.GridTable1LightAccent5 },
      { "Grid Table 2 Accent 5", MyBuiltinStyle.GridTable2Accent5 },
      { "Grid Table 3 Accent 5", MyBuiltinStyle.GridTable3Accent5 },
      { "Grid Table 4 Accent 5", MyBuiltinStyle.GridTable4Accent5 },
      { "Grid Table 5 Dark Accent 5", MyBuiltinStyle.GridTable5DarkAccent5 },
      { "Grid Table 6 Colorful Accent 5", MyBuiltinStyle.GridTable6ColorfulAccent5 },
      { "Grid Table 7 Colorful Accent 5", MyBuiltinStyle.GridTable7ColorfulAccent5 },
      { "Grid Table 1 Light Accent 6", MyBuiltinStyle.GridTable1LightAccent6 },
      { "Grid Table 2 Accent 6", MyBuiltinStyle.GridTable2Accent6 },
      { "Grid Table 3 Accent 6", MyBuiltinStyle.GridTable3Accent6 },
      { "Grid Table 4 Accent 6", MyBuiltinStyle.GridTable4Accent6 },
      { "Grid Table 5 Dark Accent 6", MyBuiltinStyle.GridTable5DarkAccent6 },
      { "Grid Table 6 Colorful Accent 6", MyBuiltinStyle.GridTable6ColorfulAccent6 },
      { "Grid Table 7 Colorful Accent 6", MyBuiltinStyle.GridTable7ColorfulAccent6 },
      { "List Table 1 Light", MyBuiltinStyle.ListTable1Light },
      { "List Table 2", MyBuiltinStyle.ListTable2 },
      { "List Table 3", MyBuiltinStyle.ListTable3 },
      { "List Table 4", MyBuiltinStyle.ListTable4 },
      { "List Table 5 Dark", MyBuiltinStyle.ListTable5Dark },
      { "List Table 6 Colorful", MyBuiltinStyle.ListTable6Colorful },
      { "List Table 7 Colorful", MyBuiltinStyle.ListTable7Colorful },
      { "List Table 1 Light Accent 1", MyBuiltinStyle.ListTable1LightAccent1 },
      { "List Table 2 Accent 1", MyBuiltinStyle.ListTable2Accent1 },
      { "List Table 3 Accent 1", MyBuiltinStyle.ListTable3Accent1 },
      { "List Table 4 Accent 1", MyBuiltinStyle.ListTable4Accent1 },
      { "List Table 5 Dark Accent 1", MyBuiltinStyle.ListTable5DarkAccent1 },
      { "List Table 6 Colorful Accent 1", MyBuiltinStyle.ListTable6ColorfulAccent1 },
      { "List Table 7 Colorful Accent 1", MyBuiltinStyle.ListTable7ColorfulAccent1 },
      { "List Table 1 Light Accent 2", MyBuiltinStyle.ListTable1LightAccent2 },
      { "List Table 2 Accent 2", MyBuiltinStyle.ListTable2Accent2 },
      { "List Table 3 Accent 2", MyBuiltinStyle.ListTable3Accent2 },
      { "List Table 4 Accent 2", MyBuiltinStyle.ListTable4Accent2 },
      { "List Table 5 Dark Accent 2", MyBuiltinStyle.ListTable5DarkAccent2 },
      { "List Table 6 Colorful Accent 2", MyBuiltinStyle.ListTable6ColorfulAccent2 },
      { "List Table 7 Colorful Accent 2", MyBuiltinStyle.ListTable7ColorfulAccent2 },
      { "List Table 1 Light Accent 3", MyBuiltinStyle.ListTable1LightAccent3 },
      { "List Table 2 Accent 3", MyBuiltinStyle.ListTable2Accent3 },
      { "List Table 3 Accent 3", MyBuiltinStyle.ListTable3Accent3 },
      { "List Table 4 Accent 3", MyBuiltinStyle.ListTable4Accent3 },
      { "List Table 5 Dark Accent 3", MyBuiltinStyle.ListTable5DarkAccent3 },
      { "List Table 6 Colorful Accent 3", MyBuiltinStyle.ListTable6ColorfulAccent3 },
      { "List Table 7 Colorful Accent 3", MyBuiltinStyle.ListTable7ColorfulAccent3 },
      { "List Table 1 Light Accent 4", MyBuiltinStyle.ListTable1LightAccent4 },
      { "List Table 2 Accent 4", MyBuiltinStyle.ListTable2Accent4 },
      { "List Table 3 Accent 4", MyBuiltinStyle.ListTable3Accent4 },
      { "List Table 4 Accent 4", MyBuiltinStyle.ListTable4Accent4 },
      { "List Table 5 Dark Accent 4", MyBuiltinStyle.ListTable5DarkAccent4 },
      { "List Table 6 Colorful Accent 4", MyBuiltinStyle.ListTable6ColorfulAccent4 },
      { "List Table 7 Colorful Accent 4", MyBuiltinStyle.ListTable7ColorfulAccent4 },
      { "List Table 1 Light Accent 5", MyBuiltinStyle.ListTable1LightAccent5 },
      { "List Table 2 Accent 5", MyBuiltinStyle.ListTable2Accent5 },
      { "List Table 3 Accent 5", MyBuiltinStyle.ListTable3Accent5 },
      { "List Table 4 Accent 5", MyBuiltinStyle.ListTable4Accent5 },
      { "List Table 5 Dark Accent 5", MyBuiltinStyle.ListTable5DarkAccent5 },
      { "List Table 6 Colorful Accent 5", MyBuiltinStyle.ListTable6ColorfulAccent5 },
      { "List Table 7 Colorful Accent 5", MyBuiltinStyle.ListTable7ColorfulAccent5 },
      { "List Table 1 Light Accent 6", MyBuiltinStyle.ListTable1LightAccent6 },
      { "List Table 2 Accent 6", MyBuiltinStyle.ListTable2Accent6 },
      { "List Table 3 Accent 6", MyBuiltinStyle.ListTable3Accent6 },
      { "List Table 4 Accent 6", MyBuiltinStyle.ListTable4Accent6 },
      { "List Table 5 Dark Accent 6", MyBuiltinStyle.ListTable5DarkAccent6 },
      { "List Table 6 Colorful Accent 6", MyBuiltinStyle.ListTable6ColorfulAccent6 },
      { "List Table 7 Colorful Accent 6", MyBuiltinStyle.ListTable7ColorfulAccent6 },
      { "Mention", MyBuiltinStyle.Mention },
      { "Smart Hyperlink", MyBuiltinStyle.SmartHyperlink },
      { "Hashtag", MyBuiltinStyle.Hashtag },
      { "Unresolved Mention", MyBuiltinStyle.UnresolvedMention },
      { "Smart Link", MyBuiltinStyle.SmartLink },

    };

    public Dictionary<MyBuiltinStyle, string> MyBuiltInStyleBuiltinNames = new()
    {
      { MyBuiltinStyle.Normal, "Normal" },
      { MyBuiltinStyle.Heading1, "heading 1" },
      { MyBuiltinStyle.Heading2, "heading 2" },
      { MyBuiltinStyle.Heading3, "heading 3" },
      { MyBuiltinStyle.Heading4, "heading 4" },
      { MyBuiltinStyle.Heading5, "heading 5" },
      { MyBuiltinStyle.Heading6, "heading 6" },
      { MyBuiltinStyle.Heading7, "heading 7" },
      { MyBuiltinStyle.Heading8, "heading 8" },
      { MyBuiltinStyle.Heading9, "heading 9" },
      { MyBuiltinStyle.Index1, "index 1" },
      { MyBuiltinStyle.Index2, "index 2" },
      { MyBuiltinStyle.Index3, "index 3" },
      { MyBuiltinStyle.Index4, "index 4" },
      { MyBuiltinStyle.Index5, "index 5" },
      { MyBuiltinStyle.Index6, "index 6" },
      { MyBuiltinStyle.Index7, "index 7" },
      { MyBuiltinStyle.Index8, "index 8" },
      { MyBuiltinStyle.Index9, "index 9" },
      { MyBuiltinStyle.Toc1, "toc 1" },
      { MyBuiltinStyle.Toc2, "toc 2" },
      { MyBuiltinStyle.Toc3, "toc 3" },
      { MyBuiltinStyle.Toc4, "toc 4" },
      { MyBuiltinStyle.Toc5, "toc 5" },
      { MyBuiltinStyle.Toc6, "toc 6" },
      { MyBuiltinStyle.Toc7, "toc 7" },
      { MyBuiltinStyle.Toc8, "toc 8" },
      { MyBuiltinStyle.Toc9, "toc 9" },
      { MyBuiltinStyle.NormalIndent, "Normal Indent" },
      { MyBuiltinStyle.FootnoteText, "footnote text" },
      { MyBuiltinStyle.AnnotationText, "annotation text" },
      { MyBuiltinStyle.Header, "header" },
      { MyBuiltinStyle.Footer, "footer" },
      { MyBuiltinStyle.IndexHeading, "index heading" },
      { MyBuiltinStyle.Caption, "caption" },
      { MyBuiltinStyle.TableOfFigures, "table of figures" },
      { MyBuiltinStyle.EnvelopeAddress, "envelope address" },
      { MyBuiltinStyle.EnvelopeReturn, "envelope return" },
      { MyBuiltinStyle.FootnoteReference, "footnote reference" },
      { MyBuiltinStyle.AnnotationReference, "annotation reference" },
      { MyBuiltinStyle.LineNumber, "line number" },
      { MyBuiltinStyle.PageNumber, "page number" },
      { MyBuiltinStyle.EndnoteReference, "endnote reference" },
      { MyBuiltinStyle.EndnoteText, "endnote text" },
      { MyBuiltinStyle.TableOfAuthorities, "table of authorities" },
      { MyBuiltinStyle.Macro, "macro" },
      { MyBuiltinStyle.ToaHeading, "toa heading" },
      { MyBuiltinStyle.List, "List" },
      { MyBuiltinStyle.ListBullet, "List Bullet" },
      { MyBuiltinStyle.ListNumber, "List Number" },
      { MyBuiltinStyle.List2, "List 2" },
      { MyBuiltinStyle.List3, "List 3" },
      { MyBuiltinStyle.List4, "List 4" },
      { MyBuiltinStyle.List5, "List 5" },
      { MyBuiltinStyle.ListBullet2, "List Bullet 2" },
      { MyBuiltinStyle.ListBullet3, "List Bullet 3" },
      { MyBuiltinStyle.ListBullet4, "List Bullet 4" },
      { MyBuiltinStyle.ListBullet5, "List Bullet 5" },
      { MyBuiltinStyle.ListNumber2, "List Number 2" },
      { MyBuiltinStyle.ListNumber3, "List Number 3" },
      { MyBuiltinStyle.ListNumber4, "List Number 4" },
      { MyBuiltinStyle.ListNumber5, "List Number 5" },
      { MyBuiltinStyle.Title, "Title" },
      { MyBuiltinStyle.Closing, "Closing" },
      { MyBuiltinStyle.Signature, "Signature" },
      { MyBuiltinStyle.DefaultParagraphFont, "Default Paragraph Font" },
      { MyBuiltinStyle.BodyText, "Body Text" },
      { MyBuiltinStyle.BodyTextIndent, "Body Text Indent" },
      { MyBuiltinStyle.ListContinue, "List Continue" },
      { MyBuiltinStyle.ListContinue2, "List Continue 2" },
      { MyBuiltinStyle.ListContinue3, "List Continue 3" },
      { MyBuiltinStyle.ListContinue4, "List Continue 4" },
      { MyBuiltinStyle.ListContinue5, "List Continue 5" },
      { MyBuiltinStyle.MessageHeader, "Message Header" },
      { MyBuiltinStyle.Subtitle, "Subtitle" },
      { MyBuiltinStyle.Salutation, "Salutation" },
      { MyBuiltinStyle.Date, "Date" },
      { MyBuiltinStyle.BodyTextFirstIndent, "Body Text First Indent" },
      { MyBuiltinStyle.BodyTextFirstIndent2, "Body Text First Indent 2" },
      { MyBuiltinStyle.NoteHeading, "Note Heading" },
      { MyBuiltinStyle.BodyText2, "Body Text 2" },
      { MyBuiltinStyle.BodyText3, "Body Text 3" },
      { MyBuiltinStyle.BodyTextIndent2, "Body Text Indent 2" },
      { MyBuiltinStyle.BodyTextIndent3, "Body Text Indent 3" },
      { MyBuiltinStyle.BlockText, "Block Text" },
      { MyBuiltinStyle.Hyperlink, "Hyperlink" },
      { MyBuiltinStyle.FollowedHyperlink, "FollowedHyperlink" },
      { MyBuiltinStyle.Strong, "Strong" },
      { MyBuiltinStyle.Emphasis, "Emphasis" },
      { MyBuiltinStyle.DocumentMap, "Document Map" },
      { MyBuiltinStyle.PlainText, "Plain Text" },
      { MyBuiltinStyle.EMailSignature, "E-mail Signature" },
      { MyBuiltinStyle.HTMLTopOfForm, "HTML Top of Form" },
      { MyBuiltinStyle.HTMLBottomOfForm, "HTML Bottom of Form" },
      { MyBuiltinStyle.HtmlNormal, "Normal (Web)" },
      { MyBuiltinStyle.HtmlAcronym, "HTML Acronym" },
      { MyBuiltinStyle.HtmlAddress, "HTML Address" },
      { MyBuiltinStyle.HtmlCite, "HTML Cite" },
      { MyBuiltinStyle.HtmlCode, "HTML Code" },
      { MyBuiltinStyle.HtmlDefinition, "HTML Definition" },
      { MyBuiltinStyle.HtmlKeyboard, "HTML Keyboard" },
      { MyBuiltinStyle.HtmlPreformatted, "HTML Preformatted" },
      { MyBuiltinStyle.HtmlSample, "HTML Sample" },
      { MyBuiltinStyle.HtmlTypewriter, "HTML Typewriter" },
      { MyBuiltinStyle.HtmlVariable, "HTML Variable" },
      { MyBuiltinStyle.NormalTable, "Normal Table" },
      { MyBuiltinStyle.AnnotationSubject, "annotation subject" },
      { MyBuiltinStyle.NoList, "No List" },
      { MyBuiltinStyle.OutlineList1, "Outline List 1" },
      { MyBuiltinStyle.OutlineList2, "Outline List 2" },
      { MyBuiltinStyle.OutlineList3, "Outline List 3" },
      { MyBuiltinStyle.TableSimple1, "Table Simple 1" },
      { MyBuiltinStyle.TableSimple2, "Table Simple 2" },
      { MyBuiltinStyle.TableSimple3, "Table Simple 3" },
      { MyBuiltinStyle.TableClassic1, "Table Classic 1" },
      { MyBuiltinStyle.TableClassic2, "Table Classic 2" },
      { MyBuiltinStyle.TableClassic3, "Table Classic 3" },
      { MyBuiltinStyle.TableClassic4, "Table Classic 4" },
      { MyBuiltinStyle.TableColorful1, "Table Colorful 1" },
      { MyBuiltinStyle.TableColorful2, "Table Colorful 2" },
      { MyBuiltinStyle.TableColorful3, "Table Colorful 3" },
      { MyBuiltinStyle.TableColumns1, "Table Columns 1" },
      { MyBuiltinStyle.TableColumns2, "Table Columns 2" },
      { MyBuiltinStyle.TableColumns3, "Table Columns 3" },
      { MyBuiltinStyle.TableColumns4, "Table Columns 4" },
      { MyBuiltinStyle.TableColumns5, "Table Columns 5" },
      { MyBuiltinStyle.TableGrid1, "Table Grid 1" },
      { MyBuiltinStyle.TableGrid2, "Table Grid 2" },
      { MyBuiltinStyle.TableGrid3, "Table Grid 3" },
      { MyBuiltinStyle.TableGrid4, "Table Grid 4" },
      { MyBuiltinStyle.TableGrid5, "Table Grid 5" },
      { MyBuiltinStyle.TableGrid6, "Table Grid 6" },
      { MyBuiltinStyle.TableGrid7, "Table Grid 7" },
      { MyBuiltinStyle.TableGrid8, "Table Grid 8" },
      { MyBuiltinStyle.TableList1, "Table List 1" },
      { MyBuiltinStyle.TableList2, "Table List 2" },
      { MyBuiltinStyle.TableList3, "Table List 3" },
      { MyBuiltinStyle.TableList4, "Table List 4" },
      { MyBuiltinStyle.TableList5, "Table List 5" },
      { MyBuiltinStyle.TableList6, "Table List 6" },
      { MyBuiltinStyle.TableList7, "Table List 7" },
      { MyBuiltinStyle.TableList8, "Table List 8" },
      { MyBuiltinStyle.Table3DEffects1, "Table 3D effects 1" },
      { MyBuiltinStyle.Table3DEffects2, "Table 3D effects 2" },
      { MyBuiltinStyle.Table3DEffects3, "Table 3D effects 3" },
      { MyBuiltinStyle.TableContemporary, "Table Contemporary" },
      { MyBuiltinStyle.TableElegant, "Table Elegant" },
      { MyBuiltinStyle.TableProfessional, "Table Professional" },
      { MyBuiltinStyle.TableSubtle1, "Table Subtle 1" },
      { MyBuiltinStyle.TableSubtle2, "Table Subtle 2" },
      { MyBuiltinStyle.TableWeb1, "Table Web 1" },
      { MyBuiltinStyle.TableWeb2, "Table Web 2" },
      { MyBuiltinStyle.TableWeb3, "Table Web 3" },
      { MyBuiltinStyle.BalloonText, "Balloon Text" },
      { MyBuiltinStyle.TableGrid, "Table Grid" },
      { MyBuiltinStyle.TableTheme, "Table Theme" },
      { MyBuiltinStyle.PlaceholderText, "Placeholder Text" },
      { MyBuiltinStyle.NoSpacing, "No Spacing" },
      { MyBuiltinStyle.LightShading, "Light Shading" },
      { MyBuiltinStyle.LightList, "Light List" },
      { MyBuiltinStyle.LightGrid, "Light Grid" },
      { MyBuiltinStyle.MediumShading1, "Medium Shading 1" },
      { MyBuiltinStyle.MediumShading2, "Medium Shading 2" },
      { MyBuiltinStyle.MediumList1, "Medium List 1" },
      { MyBuiltinStyle.MediumList2, "Medium List 2" },
      { MyBuiltinStyle.MediumGrid1, "Medium Grid 1" },
      { MyBuiltinStyle.MediumGrid2, "Medium Grid 2" },
      { MyBuiltinStyle.MediumGrid3, "Medium Grid 3" },
      { MyBuiltinStyle.DarkList, "Dark List" },
      { MyBuiltinStyle.ColorfulShading, "Colorful Shading" },
      { MyBuiltinStyle.ColorfulList, "Colorful List" },
      { MyBuiltinStyle.ColorfulGrid, "Colorful Grid" },
      { MyBuiltinStyle.LightShadingAccent1, "Light Shading Accent 1" },
      { MyBuiltinStyle.LightListAccent1, "Light List Accent 1" },
      { MyBuiltinStyle.LightGridAccent1, "Light Grid Accent 1" },
      { MyBuiltinStyle.MediumShading1Accent1, "Medium Shading 1 Accent 1" },
      { MyBuiltinStyle.MediumShading2Accent1, "Medium Shading 2 Accent 1" },
      { MyBuiltinStyle.MediumList1Accent1, "Medium List 1 Accent 1" },
      { MyBuiltinStyle.Revision, "Revision" },
      { MyBuiltinStyle.ListParagraph, "List Paragraph" },
      { MyBuiltinStyle.Quote, "Quote" },
      { MyBuiltinStyle.IntenseQuote, "Intense Quote" },
      { MyBuiltinStyle.MediumList2Accent1, "Medium List 2 Accent 1" },
      { MyBuiltinStyle.MediumGrid1Accent1, "Medium Grid 1 Accent 1" },
      { MyBuiltinStyle.MediumGrid2Accent1, "Medium Grid 2 Accent 1" },
      { MyBuiltinStyle.MediumGrid3Accent1, "Medium Grid 3 Accent 1" },
      { MyBuiltinStyle.DarkListAccent1, "Dark List Accent 1" },
      { MyBuiltinStyle.ColorfulShadingAccent1, "Colorful Shading Accent 1" },
      { MyBuiltinStyle.ColorfulListAccent1, "Colorful List Accent 1" },
      { MyBuiltinStyle.ColorfulGridAccent1, "Colorful Grid Accent 1" },
      { MyBuiltinStyle.LightShadingAccent2, "Light Shading Accent 2" },
      { MyBuiltinStyle.LightListAccent2, "Light List Accent 2" },
      { MyBuiltinStyle.LightGridAccent2, "Light Grid Accent 2" },
      { MyBuiltinStyle.MediumShading1Accent2, "Medium Shading 1 Accent 2" },
      { MyBuiltinStyle.MediumShading2Accent2, "Medium Shading 2 Accent 2" },
      { MyBuiltinStyle.MediumList1Accent2, "Medium List 1 Accent 2" },
      { MyBuiltinStyle.MediumList2Accent2, "Medium List 2 Accent 2" },
      { MyBuiltinStyle.MediumGrid1Accent2, "Medium Grid 1 Accent 2" },
      { MyBuiltinStyle.MediumGrid2Accent2, "Medium Grid 2 Accent 2" },
      { MyBuiltinStyle.MediumGrid3Accent2, "Medium Grid 3 Accent 2" },
      { MyBuiltinStyle.DarkListAccent2, "Dark List Accent 2" },
      { MyBuiltinStyle.ColorfulShadingAccent2, "Colorful Shading Accent 2" },
      { MyBuiltinStyle.ColorfulListAccent2, "Colorful List Accent 2" },
      { MyBuiltinStyle.ColorfulGridAccent2, "Colorful Grid Accent 2" },
      { MyBuiltinStyle.LightShadingAccent3, "Light Shading Accent 3" },
      { MyBuiltinStyle.LightListAccent3, "Light List Accent 3" },
      { MyBuiltinStyle.LightGridAccent3, "Light Grid Accent 3" },
      { MyBuiltinStyle.MediumShading1Accent3, "Medium Shading 1 Accent 3" },
      { MyBuiltinStyle.MediumShading2Accent3, "Medium Shading 2 Accent 3" },
      { MyBuiltinStyle.MediumList1Accent3, "Medium List 1 Accent 3" },
      { MyBuiltinStyle.MediumList2Accent3, "Medium List 2 Accent 3" },
      { MyBuiltinStyle.MediumGrid1Accent3, "Medium Grid 1 Accent 3" },
      { MyBuiltinStyle.MediumGrid2Accent3, "Medium Grid 2 Accent 3" },
      { MyBuiltinStyle.MediumGrid3Accent3, "Medium Grid 3 Accent 3" },
      { MyBuiltinStyle.DarkListAccent3, "Dark List Accent 3" },
      { MyBuiltinStyle.ColorfulShadingAccent3, "Colorful Shading Accent 3" },
      { MyBuiltinStyle.ColorfulListAccent3, "Colorful List Accent 3" },
      { MyBuiltinStyle.ColorfulGridAccent3, "Colorful Grid Accent 3" },
      { MyBuiltinStyle.LightShadingAccent4, "Light Shading Accent 4" },
      { MyBuiltinStyle.LightListAccent4, "Light List Accent 4" },
      { MyBuiltinStyle.LightGridAccent4, "Light Grid Accent 4" },
      { MyBuiltinStyle.MediumShading1Accent4, "Medium Shading 1 Accent 4" },
      { MyBuiltinStyle.MediumShading2Accent4, "Medium Shading 2 Accent 4" },
      { MyBuiltinStyle.MediumList1Accent4, "Medium List 1 Accent 4" },
      { MyBuiltinStyle.MediumList2Accent4, "Medium List 2 Accent 4" },
      { MyBuiltinStyle.MediumGrid1Accent4, "Medium Grid 1 Accent 4" },
      { MyBuiltinStyle.MediumGrid2Accent4, "Medium Grid 2 Accent 4" },
      { MyBuiltinStyle.MediumGrid3Accent4, "Medium Grid 3 Accent 4" },
      { MyBuiltinStyle.DarkListAccent4, "Dark List Accent 4" },
      { MyBuiltinStyle.ColorfulShadingAccent4, "Colorful Shading Accent 4" },
      { MyBuiltinStyle.ColorfulListAccent4, "Colorful List Accent 4" },
      { MyBuiltinStyle.ColorfulGridAccent4, "Colorful Grid Accent 4" },
      { MyBuiltinStyle.LightShadingAccent5, "Light Shading Accent 5" },
      { MyBuiltinStyle.LightListAccent5, "Light List Accent 5" },
      { MyBuiltinStyle.LightGridAccent5, "Light Grid Accent 5" },
      { MyBuiltinStyle.MediumShading1Accent5, "Medium Shading 1 Accent 5" },
      { MyBuiltinStyle.MediumShading2Accent5, "Medium Shading 2 Accent 5" },
      { MyBuiltinStyle.MediumList1Accent5, "Medium List 1 Accent 5" },
      { MyBuiltinStyle.MediumList2Accent5, "Medium List 2 Accent 5" },
      { MyBuiltinStyle.MediumGrid1Accent5, "Medium Grid 1 Accent 5" },
      { MyBuiltinStyle.MediumGrid2Accent5, "Medium Grid 2 Accent 5" },
      { MyBuiltinStyle.MediumGrid3Accent5, "Medium Grid 3 Accent 5" },
      { MyBuiltinStyle.DarkListAccent5, "Dark List Accent 5" },
      { MyBuiltinStyle.ColorfulShadingAccent5, "Colorful Shading Accent 5" },
      { MyBuiltinStyle.ColorfulListAccent5, "Colorful List Accent 5" },
      { MyBuiltinStyle.ColorfulGridAccent5, "Colorful Grid Accent 5" },
      { MyBuiltinStyle.LightShadingAccent6, "Light Shading Accent 6" },
      { MyBuiltinStyle.LightListAccent6, "Light List Accent 6" },
      { MyBuiltinStyle.LightGridAccent6, "Light Grid Accent 6" },
      { MyBuiltinStyle.MediumShading1Accent6, "Medium Shading 1 Accent 6" },
      { MyBuiltinStyle.MediumShading2Accent6, "Medium Shading 2 Accent 6" },
      { MyBuiltinStyle.MediumList1Accent6, "Medium List 1 Accent 6" },
      { MyBuiltinStyle.MediumList2Accent6, "Medium List 2 Accent 6" },
      { MyBuiltinStyle.MediumGrid1Accent6, "Medium Grid 1 Accent 6" },
      { MyBuiltinStyle.MediumGrid2Accent6, "Medium Grid 2 Accent 6" },
      { MyBuiltinStyle.MediumGrid3Accent6, "Medium Grid 3 Accent 6" },
      { MyBuiltinStyle.DarkListAccent6, "Dark List Accent 6" },
      { MyBuiltinStyle.ColorfulShadingAccent6, "Colorful Shading Accent 6" },
      { MyBuiltinStyle.ColorfulListAccent6, "Colorful List Accent 6" },
      { MyBuiltinStyle.ColorfulGridAccent6, "Colorful Grid Accent 6" },
      { MyBuiltinStyle.SubtleEmphasis, "Subtle Emphasis" },
      { MyBuiltinStyle.IntenseEmphasis, "Intense Emphasis" },
      { MyBuiltinStyle.SubtleReference, "Subtle Reference" },
      { MyBuiltinStyle.IntenseReference, "Intense Reference" },
      { MyBuiltinStyle.BookTitle, "Book Title" },
      { MyBuiltinStyle.Bibliography, "Bibliography" },
      { MyBuiltinStyle.TocHeading, "TOC Heading" },
      { MyBuiltinStyle.PlainTable1, "Plain Table 1" },
      { MyBuiltinStyle.PlainTable2, "Plain Table 2" },
      { MyBuiltinStyle.PlainTable3, "Plain Table 3" },
      { MyBuiltinStyle.PlainTable4, "Plain Table 4" },
      { MyBuiltinStyle.PlainTable5, "Plain Table 5" },
      { MyBuiltinStyle.GridTableLight, "Grid Table Light" },
      { MyBuiltinStyle.GridTable1Light, "Grid Table 1 Light" },
      { MyBuiltinStyle.GridTable2, "Grid Table 2" },
      { MyBuiltinStyle.GridTable3, "Grid Table 3" },
      { MyBuiltinStyle.GridTable4, "Grid Table 4" },
      { MyBuiltinStyle.GridTable5Dark, "Grid Table 5 Dark" },
      { MyBuiltinStyle.GridTable6Colorful, "Grid Table 6 Colorful" },
      { MyBuiltinStyle.GridTable7Colorful, "Grid Table 7 Colorful" },
      { MyBuiltinStyle.GridTable1LightAccent1, "Grid Table 1 Light Accent 1" },
      { MyBuiltinStyle.GridTable2Accent1, "Grid Table 2 Accent 1" },
      { MyBuiltinStyle.GridTable3Accent1, "Grid Table 3 Accent 1" },
      { MyBuiltinStyle.GridTable4Accent1, "Grid Table 4 Accent 1" },
      { MyBuiltinStyle.GridTable5DarkAccent1, "Grid Table 5 Dark Accent 1" },
      { MyBuiltinStyle.GridTable6ColorfulAccent1, "Grid Table 6 Colorful Accent 1" },
      { MyBuiltinStyle.GridTable7ColorfulAccent1, "Grid Table 7 Colorful Accent 1" },
      { MyBuiltinStyle.GridTable1LightAccent2, "Grid Table 1 Light Accent 2" },
      { MyBuiltinStyle.GridTable2Accent2, "Grid Table 2 Accent 2" },
      { MyBuiltinStyle.GridTable3Accent2, "Grid Table 3 Accent 2" },
      { MyBuiltinStyle.GridTable4Accent2, "Grid Table 4 Accent 2" },
      { MyBuiltinStyle.GridTable5DarkAccent2, "Grid Table 5 Dark Accent 2" },
      { MyBuiltinStyle.GridTable6ColorfulAccent2, "Grid Table 6 Colorful Accent 2" },
      { MyBuiltinStyle.GridTable7ColorfulAccent2, "Grid Table 7 Colorful Accent 2" },
      { MyBuiltinStyle.GridTable1LightAccent3, "Grid Table 1 Light Accent 3" },
      { MyBuiltinStyle.GridTable2Accent3, "Grid Table 2 Accent 3" },
      { MyBuiltinStyle.GridTable3Accent3, "Grid Table 3 Accent 3" },
      { MyBuiltinStyle.GridTable4Accent3, "Grid Table 4 Accent 3" },
      { MyBuiltinStyle.GridTable5DarkAccent3, "Grid Table 5 Dark Accent 3" },
      { MyBuiltinStyle.GridTable6ColorfulAccent3, "Grid Table 6 Colorful Accent 3" },
      { MyBuiltinStyle.GridTable7ColorfulAccent3, "Grid Table 7 Colorful Accent 3" },
      { MyBuiltinStyle.GridTable1LightAccent4, "Grid Table 1 Light Accent 4" },
      { MyBuiltinStyle.GridTable2Accent4, "Grid Table 2 Accent 4" },
      { MyBuiltinStyle.GridTable3Accent4, "Grid Table 3 Accent 4" },
      { MyBuiltinStyle.GridTable4Accent4, "Grid Table 4 Accent 4" },
      { MyBuiltinStyle.GridTable5DarkAccent4, "Grid Table 5 Dark Accent 4" },
      { MyBuiltinStyle.GridTable6ColorfulAccent4, "Grid Table 6 Colorful Accent 4" },
      { MyBuiltinStyle.GridTable7ColorfulAccent4, "Grid Table 7 Colorful Accent 4" },
      { MyBuiltinStyle.GridTable1LightAccent5, "Grid Table 1 Light Accent 5" },
      { MyBuiltinStyle.GridTable2Accent5, "Grid Table 2 Accent 5" },
      { MyBuiltinStyle.GridTable3Accent5, "Grid Table 3 Accent 5" },
      { MyBuiltinStyle.GridTable4Accent5, "Grid Table 4 Accent 5" },
      { MyBuiltinStyle.GridTable5DarkAccent5, "Grid Table 5 Dark Accent 5" },
      { MyBuiltinStyle.GridTable6ColorfulAccent5, "Grid Table 6 Colorful Accent 5" },
      { MyBuiltinStyle.GridTable7ColorfulAccent5, "Grid Table 7 Colorful Accent 5" },
      { MyBuiltinStyle.GridTable1LightAccent6, "Grid Table 1 Light Accent 6" },
      { MyBuiltinStyle.GridTable2Accent6, "Grid Table 2 Accent 6" },
      { MyBuiltinStyle.GridTable3Accent6, "Grid Table 3 Accent 6" },
      { MyBuiltinStyle.GridTable4Accent6, "Grid Table 4 Accent 6" },
      { MyBuiltinStyle.GridTable5DarkAccent6, "Grid Table 5 Dark Accent 6" },
      { MyBuiltinStyle.GridTable6ColorfulAccent6, "Grid Table 6 Colorful Accent 6" },
      { MyBuiltinStyle.GridTable7ColorfulAccent6, "Grid Table 7 Colorful Accent 6" },
      { MyBuiltinStyle.ListTable1Light, "List Table 1 Light" },
      { MyBuiltinStyle.ListTable2, "List Table 2" },
      { MyBuiltinStyle.ListTable3, "List Table 3" },
      { MyBuiltinStyle.ListTable4, "List Table 4" },
      { MyBuiltinStyle.ListTable5Dark, "List Table 5 Dark" },
      { MyBuiltinStyle.ListTable6Colorful, "List Table 6 Colorful" },
      { MyBuiltinStyle.ListTable7Colorful, "List Table 7 Colorful" },
      { MyBuiltinStyle.ListTable1LightAccent1, "List Table 1 Light Accent 1" },
      { MyBuiltinStyle.ListTable2Accent1, "List Table 2 Accent 1" },
      { MyBuiltinStyle.ListTable3Accent1, "List Table 3 Accent 1" },
      { MyBuiltinStyle.ListTable4Accent1, "List Table 4 Accent 1" },
      { MyBuiltinStyle.ListTable5DarkAccent1, "List Table 5 Dark Accent 1" },
      { MyBuiltinStyle.ListTable6ColorfulAccent1, "List Table 6 Colorful Accent 1" },
      { MyBuiltinStyle.ListTable7ColorfulAccent1, "List Table 7 Colorful Accent 1" },
      { MyBuiltinStyle.ListTable1LightAccent2, "List Table 1 Light Accent 2" },
      { MyBuiltinStyle.ListTable2Accent2, "List Table 2 Accent 2" },
      { MyBuiltinStyle.ListTable3Accent2, "List Table 3 Accent 2" },
      { MyBuiltinStyle.ListTable4Accent2, "List Table 4 Accent 2" },
      { MyBuiltinStyle.ListTable5DarkAccent2, "List Table 5 Dark Accent 2" },
      { MyBuiltinStyle.ListTable6ColorfulAccent2, "List Table 6 Colorful Accent 2" },
      { MyBuiltinStyle.ListTable7ColorfulAccent2, "List Table 7 Colorful Accent 2" },
      { MyBuiltinStyle.ListTable1LightAccent3, "List Table 1 Light Accent 3" },
      { MyBuiltinStyle.ListTable2Accent3, "List Table 2 Accent 3" },
      { MyBuiltinStyle.ListTable3Accent3, "List Table 3 Accent 3" },
      { MyBuiltinStyle.ListTable4Accent3, "List Table 4 Accent 3" },
      { MyBuiltinStyle.ListTable5DarkAccent3, "List Table 5 Dark Accent 3" },
      { MyBuiltinStyle.ListTable6ColorfulAccent3, "List Table 6 Colorful Accent 3" },
      { MyBuiltinStyle.ListTable7ColorfulAccent3, "List Table 7 Colorful Accent 3" },
      { MyBuiltinStyle.ListTable1LightAccent4, "List Table 1 Light Accent 4" },
      { MyBuiltinStyle.ListTable2Accent4, "List Table 2 Accent 4" },
      { MyBuiltinStyle.ListTable3Accent4, "List Table 3 Accent 4" },
      { MyBuiltinStyle.ListTable4Accent4, "List Table 4 Accent 4" },
      { MyBuiltinStyle.ListTable5DarkAccent4, "List Table 5 Dark Accent 4" },
      { MyBuiltinStyle.ListTable6ColorfulAccent4, "List Table 6 Colorful Accent 4" },
      { MyBuiltinStyle.ListTable7ColorfulAccent4, "List Table 7 Colorful Accent 4" },
      { MyBuiltinStyle.ListTable1LightAccent5, "List Table 1 Light Accent 5" },
      { MyBuiltinStyle.ListTable2Accent5, "List Table 2 Accent 5" },
      { MyBuiltinStyle.ListTable3Accent5, "List Table 3 Accent 5" },
      { MyBuiltinStyle.ListTable4Accent5, "List Table 4 Accent 5" },
      { MyBuiltinStyle.ListTable5DarkAccent5, "List Table 5 Dark Accent 5" },
      { MyBuiltinStyle.ListTable6ColorfulAccent5, "List Table 6 Colorful Accent 5" },
      { MyBuiltinStyle.ListTable7ColorfulAccent5, "List Table 7 Colorful Accent 5" },
      { MyBuiltinStyle.ListTable1LightAccent6, "List Table 1 Light Accent 6" },
      { MyBuiltinStyle.ListTable2Accent6, "List Table 2 Accent 6" },
      { MyBuiltinStyle.ListTable3Accent6, "List Table 3 Accent 6" },
      { MyBuiltinStyle.ListTable4Accent6, "List Table 4 Accent 6" },
      { MyBuiltinStyle.ListTable5DarkAccent6, "List Table 5 Dark Accent 6" },
      { MyBuiltinStyle.ListTable6ColorfulAccent6, "List Table 6 Colorful Accent 6" },
      { MyBuiltinStyle.ListTable7ColorfulAccent6, "List Table 7 Colorful Accent 6" },
      { MyBuiltinStyle.Mention, "Mention" },
      { MyBuiltinStyle.SmartHyperlink, "Smart Hyperlink" },
      { MyBuiltinStyle.Hashtag, "Hashtag" },
      { MyBuiltinStyle.UnresolvedMention, "Unresolved Mention" },
      { MyBuiltinStyle.SmartLink, "Smart Link" },

    };

    public Dictionary<string, MyBuiltinStyle> LocalNameMyBuiltinStyles = new();
    public Dictionary<MyBuiltinStyle, string> MyBuiltInStyleLocalNames = new();

    public static WdBuiltinStyle GetWdBuiltinStyle(MyBuiltinStyle value)
    {
      int val = -(int)Convert.ChangeType(value, typeof(int));
      return (WdBuiltinStyle)Enum.ToObject(typeof(WdBuiltinStyle), val);
    }

    public static MyBuiltinStyle GetMyBuiltinStyle(WdBuiltinStyle value)
    {
      int val = -(int)Convert.ChangeType(value, typeof(int));
      return (MyBuiltinStyle)Enum.ToObject(typeof(MyBuiltinStyle), val);
    }

    public bool TryLocalNameToBuiltinName(string localName, out string? builtInName)
    {
      if (LocalNameMyBuiltinStyles.TryGetValue(localName, out var styleNumber))
      {
        return MyBuiltInStyleBuiltinNames.TryGetValue(styleNumber, out builtInName);

      }
      builtInName = null;
      return false;
    }

    public Word.Document ActiveDocument { get; private set; }

    public StyleTools(Word.Document activeDocument)
    {
      ActiveDocument = activeDocument;
      foreach (MyBuiltinStyle styleNumber in System.Enum.GetValues(typeof(MyBuiltinStyle)))
      {
        var wdStyleNumber = GetWdBuiltinStyle(styleNumber);
        var style = GetStyle(ActiveDocument, wdStyleNumber);
        LocalNameMyBuiltinStyles.Add(style.NameLocal, styleNumber);
        MyBuiltInStyleLocalNames.Add(styleNumber, style.NameLocal);
      }
    }

    public Style GetStyle(WdBuiltinStyle styleNumber)
    {
      var document = ActiveDocument;
      return GetStyle(document, styleNumber);
    }

    public Style GetStyle(Document document, WdBuiltinStyle styleNumber)
    {
      return document.Styles[styleNumber];
    }

    public Style? GetStyle(string styleName)
    {
      var document = ActiveDocument;
      return GetStyle(document, styleName);
    }

    public Style? GetStyle(Document document, string styleName)
    {
      return document.Styles[styleName];
    }

    public void SetStyle(Range range, Style style)
    {
      range.set_Style(style);
    }

    public void SetStyle(Range range, WdBuiltinStyle styleNumber)
    {
      range.set_Style(styleNumber);
    }

    public void SetStyle(Range range, string styleName)
    {
      range.set_Style(styleName);
    }

    public void SetStyle(Paragraph para, Style style)
    {
      para.set_Style(style);
    }

    public void SetStyle(Paragraph para, WdBuiltinStyle styleNumber)
    {
      para.set_Style(styleNumber);
    }

    public void SetStyle(Paragraph para, string styleName)
    {
      para.set_Style(styleName);
    }

    public void SetStyle(Table table, Style style)
    {
      table.set_Style(style);
    }

    public void SetStyle(Table table, WdBuiltinStyle styleNumber)
    {
      table.set_Style(styleNumber);
    }

    public void SetStyle(Table table, string styleName)
    {
      table.set_Style(styleName);
    }

    public Style GetStyle(Range range)
    {
      return (Style)range.get_Style();
    }

    public Style GetStyle(Paragraph para)
    {
      return (Style)para.get_Style();
    }

    public Style GetStyle(Table table)
    {
      return (Style)table.get_Style();
    }

    public bool Is(Style style, string styleName)
    {
      return style.NameLocal == styleName;
    }

    public bool Is(Style style, MyBuiltinStyle styleNumber)
    {
      return LocalNameMyBuiltinStyles.TryGetValue(style.NameLocal, out var number) && number == styleNumber;
    }

  }
}
