namespace Qhta.MVVM
{
  /// <summary>
  /// Abstract VisibleViewModel for a list. Declares <see cref="ParentViewModel"/> property.
  /// </summary>
  public abstract class ListViewModel : VisibleViewModel, IOrientable, IVisible
  {
    /// <summary>
    /// Default constructor.
    /// </summary>
    public ListViewModel() { }

    /// <summary>
    /// Constructor with a parent ViewModel.
    /// </summary>
    /// <param name="parentViewModel"></param>
    public ListViewModel(IViewModel parentViewModel)
    {
      ParentViewModel = parentViewModel;
    }

    /// <summary>
    /// Parent ViewModel
    /// </summary>
    public IViewModel? ParentViewModel { get; protected set; }


    /// <summary>
    /// Enumerable items.
    /// </summary>
    /// <returns></returns>
    public abstract IEnumerable<object> GetItems();

    /// <summary>
    /// Orientation: horizontal or vertical.
    /// </summary>
    [DataGridColumn(IsAutoGenerated = false)]
    public OrientationType Orientation
    {
      get { return _Orientation; }
      set
      {
        if (_Orientation!=value)
        {
          _Orientation=value;
          NotifyPropertyChanged(nameof(Orientation));
        }
      }
    }
    private OrientationType _Orientation;

    //public string SortedBy
    //{
    //  get { return _SortedBy; }
    //  set
    //  {
    //    if (_SortedBy!=value)
    //    {
    //      _SortedBy=value;
    //      NotifyPropertyChanged(nameof(SortedBy));
    //    }
    //  }
    //}
    //private string _SortedBy;

    //public virtual void FindFirstItem(object pattern, IEnumerable<string> propNames) { }

    //public virtual void FindNextItem() { }

    //public virtual void FindFirstInvalidItem() { }

    //public virtual void FindNextInvalidItem() { }

    //public abstract IEnumerable<object> Items { get; }
  }
}
