using System.ComponentModel;
using Qhta.ObservableObjects;

namespace Qhta.MVVM
{
  /// <summary>
  /// Base class of view model.
  /// </summary>
  public class ViewModel : ObservableObject, INotifyPropertyChanged, IViewModel
  {
    /// <summary>
    /// A method to notify that a property has changed.
    /// </summary>
    /// <param name="propertyName"></param>
    public new void NotifyPropertyChanged(string propertyName)
    {
      base.NotifyPropertyChanged(propertyName);
    }

    /// <summary>
    /// Specifies if the data of view model is valid.
    /// </summary>
    [DataGridColumn(IsAutoGenerated = false)]
    public virtual bool? IsValid { get; set; }

  }
}
