namespace Qhta.MVVM
{
  /// <summary>
  /// Base class of view model.
  /// </summary>
  public class ViewModel : ObservableObject, INotifyPropertyChanged, IViewModel, IValidated
  {
    /// <summary>
    /// A method to notify that a property has changed.
    /// </summary>
    /// <param name="propertyName"></param>
    public new void NotifyPropertyChanged(string propertyName)
    {
      base.NotifyPropertyChanged(propertyName);
    }

    /// <summary>
    /// Specifies if the data of view model is valid.
    /// </summary>
    [DataGridColumn(IsAutoGenerated = false)]
    public virtual bool? IsValid 
    { 
      get => _IsValid;
      set
      {
        if (value != _IsValid)
        {
          _IsValid = value;
          NotifyPropertyChanged(nameof(IsValid));
        }
      }
    }

    private bool? _IsValid;
  }
}
