namespace Qhta.RegularExpressions
{
  public enum RegExTag
  {
    LiteralChar,
    LiteralString,
    CharSet,
    CharRange,
    CharSetControlChar,
    EscapedChar,
    AnchorControl,
    DotChar,
    CharClass,
    ControlCharSeq,
    OctalSeq,
    HexadecimalSeq,
    UnicodeSeq,
    UnicodeCategorySeq,
    Quantifier,
    Number,
    Separator,
    AltChar,
    Subexpression,
    GroupControlChar,
    NameQuoteChar,
    GroupName,
    NamedGroup,
    BalancingGroup,
    NonCapturingGroup,
    BackRef,
  }
}
