//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qhta.WPF.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qhta.WPF.Utils.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string AddFilter {
            get {
                return ResourceManager.GetString("AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection cannot be filtered..
        /// </summary>
        public static string CantFilterThisCollection {
            get {
                return ResourceManager.GetString("CantFilterThisCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection cannot be filtered by this field..
        /// </summary>
        public static string CantFilterThisCollectionByThisField {
            get {
                return ResourceManager.GetString("CantFilterThisCollectionByThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert text to value of {0} type..
        /// </summary>
        public static string CantParseCompareValue_0 {
            get {
                return ResourceManager.GetString("CantParseCompareValue_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace filter.
        /// </summary>
        public static string ChangeFilter {
            get {
                return ResourceManager.GetString("ChangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        public static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions and options.
        /// </summary>
        public static string FunctionsAndOptions {
            get {
                return ResourceManager.GetString("FunctionsAndOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case.
        /// </summary>
        public static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        public static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal.
        /// </summary>
        public static string IsEqual {
            get {
                return ResourceManager.GetString("IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is false.
        /// </summary>
        public static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater.
        /// </summary>
        public static string IsGreater {
            get {
                return ResourceManager.GetString("IsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less.
        /// </summary>
        public static string IsLess {
            get {
                return ResourceManager.GetString("IsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is true.
        /// </summary>
        public static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not contains.
        /// </summary>
        public static string NotContains {
            get {
                return ResourceManager.GetString("NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not empty.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ends with.
        /// </summary>
        public static string NotEndsWith {
            get {
                return ResourceManager.GetString("NotEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal.
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not greater.
        /// </summary>
        public static string NotGreater {
            get {
                return ResourceManager.GetString("NotGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not less.
        /// </summary>
        public static string NotLess {
            get {
                return ResourceManager.GetString("NotLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not starts with.
        /// </summary>
        public static string NotStartsWith {
            get {
                return ResourceManager.GetString("NotStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get numeric value from supplied text..
        /// </summary>
        public static string NumFilter_parse_error {
            get {
                return ResourceManager.GetString("NumFilter_parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to compare is not declared..
        /// </summary>
        public static string UndeclaredCompareValue {
            get {
                return ResourceManager.GetString("UndeclaredCompareValue", resourceCulture);
            }
        }
    }
}
