using System.Security.Permissions;

namespace Qhta.WPF.Utils;

/// <summary>
/// Utility class that helps to autogenerate <see cref="DataGridContentBoundColumn"/>.
/// It uses DataGridColumn attributes assigned to properties.
/// </summary>
public class DataGridColumnCreator
{
  /// <summary>
  /// Initializing contructor
  /// </summary>
  public DataGridColumnCreator(Control dataGrid, Type sourceItemsType, Type itemType)
  {
    _Control = dataGrid;
    SourceItemsType = sourceItemsType;
    ItemType = itemType;
    ItemProperties = itemType.GetProperties().ToList();
  }

  /// <summary>
  /// Assigned data grid to create columns.
  /// </summary>
  public DataGrid? DataGrid => _Control as DataGrid;

  private Control? _Control;

  /// <summary>
  /// Type of the source collection.
  /// </summary>
  public Type SourceItemsType
  {
    get;
    private set;
  }

  /// <summary>
  /// ItemType that can be presetted.
  /// </summary>
  public Type ItemType
  {
    get;
    private set;
  }

  /// <summary>
  /// Should creator add filter button to each column header.
  /// </summary>
  public bool? IsFilterButtonVisible
  { get; set; }

  /// <summary>
  /// Public properties declared in ItemType
  /// </summary>
  public ICollection<PropertyInfo> ItemProperties
  { get; private set; } = new Collection<PropertyInfo>();

  /// <summary>
  /// Creates <see cref="DataGridContentBoundColumn"/> for ItemsSource thas have DataGridColumnAttribute (defined in Qhta.MVVM)
  /// </summary>
  /// <param name="sender"></param>
  /// <param name="args"></param>
  public void GenerateColumn(object sender, DataGridAutoGeneratingColumnEventArgs args)
  {
    var itemsControl = sender as ItemsControl;
    if (itemsControl != null)
    {
      var prop = ItemProperties.FirstOrDefault(item => item.Name == args.PropertyName);
      if (prop != null)
      {
        var dataGridColumnAttr = prop.GetCustomAttribute<DataGridColumnAttribute>();
        if (dataGridColumnAttr != null && dataGridColumnAttr.IsAutoGenerated)
        {
          var column = args.Column;
          BindingBase? binding = column.GetBinding();
          if (binding != null)
          {
            var columnViewInfo = new ColumnViewInfo()
            {
              Binding = binding,
              CanUserReorder = dataGridColumnAttr.CanUserReorder ?? DataGrid?.CanUserReorderColumns ?? true,
              CanUserResize = dataGridColumnAttr.CanUserResize ?? DataGrid?.CanUserResizeColumns ?? true,
              CanUserSort = dataGridColumnAttr.CanUserSort ?? DataGrid?.CanUserSortColumns ?? true,
              ClipboardContentPath = dataGridColumnAttr.ClipboardContentPath,
              DisplayIndex = dataGridColumnAttr.DisplayIndex,
              Header = dataGridColumnAttr.Header ?? column.Header,
              HeaderStringFormat = dataGridColumnAttr.HeaderStringFormat ?? column.HeaderStringFormat,
              HeaderTemplate = args.Column.HeaderTemplate,
              IsReadOnly = dataGridColumnAttr.IsReadOnly,
              MaxWidth = dataGridColumnAttr.MaxWidth,
              MinWidth = dataGridColumnAttr.MinWidth,
              SortDirection = dataGridColumnAttr.SortDirection,
              SortMemberPath = dataGridColumnAttr.SortMemberPath,
              Visibility = (Visibility)dataGridColumnAttr.Visibility,
              Width = dataGridColumnAttr.Width,
              PropertyInfo = prop,
            };
            if (dataGridColumnAttr.HeaderTemplateResourceKey != null)
            {
              columnViewInfo.HeaderTemplate = (DataTemplate)itemsControl.FindResource(dataGridColumnAttr.HeaderTemplateResourceKey);
              columnViewInfo.Header = null;
            }
            else if (dataGridColumnAttr.HeaderResourceKey != null)
            {
              columnViewInfo.Header = GetResourceString(dataGridColumnAttr.HeaderResourceKey);
            }

            if (dataGridColumnAttr.HeaderTooltipResourceKey != null)
            {
              columnViewInfo.HeaderTooltip = GetResourceString(dataGridColumnAttr.HeaderTooltipResourceKey);
            }
            else if (dataGridColumnAttr.HeaderTooltip != null)
            {
              columnViewInfo.HeaderTooltip = dataGridColumnAttr.HeaderTooltip;
            }

            if (dataGridColumnAttr.HiddenHeaderResourceKey != null)
              columnViewInfo.HiddenHeader = GetResourceString(dataGridColumnAttr.HiddenHeaderResourceKey);
            else if (dataGridColumnAttr.HiddenHeader != null)
              columnViewInfo.HiddenHeader = GetResourceString(dataGridColumnAttr.HiddenHeader);

            columnViewInfo.ShowFilterButton = dataGridColumnAttr.ShowFilterButton
              ?? CollectionViewBehavior.GetShowFilterButton(DataGrid) ?? IsFilterButtonVisible ?? false;

            DataTemplate? dataTemplate = null;
            if (dataGridColumnAttr.DataTemplateResourceKey != null)
              dataTemplate = (DataTemplate)itemsControl.FindResource(dataGridColumnAttr.DataTemplateResourceKey);
            DataTemplate? dataEditingTemplate = null;
            if (dataGridColumnAttr.DataEditingTemplateResourceKey != null)
              dataEditingTemplate = (DataTemplate)itemsControl.FindResource(dataGridColumnAttr.DataEditingTemplateResourceKey);
            
            if (dataTemplate != null)
              column = args.Column = CreateColumn(columnViewInfo, dataTemplate, dataEditingTemplate);
            else
              FormatColumn(column, columnViewInfo);
            CollectionViewBehavior.SetColumnViewInfo(column, columnViewInfo);
          }
          return;
        }
      }
    }
    args.Cancel = true;
  }

  private static string? GetResourceString(string staticResourceKey)
  {
    var k = staticResourceKey.LastIndexOf('.');
    if (k < 0)
      throw new InvalidOperationException($"HeaderResourceKey must be in the format \"typename.propName\"");
    var fullClassName = staticResourceKey.Substring(0, k);
    var className = fullClassName;
    var propName = staticResourceKey.Substring(k + 1);
    Assembly assembly;
    k = className.LastIndexOf('.');
    if (k > 0)
    {
      var ns = className.Substring(0, k);
      className = className.Substring(k + 1);
      assembly = Assembly.Load(ns);
    }
    else
      assembly = Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();

    var ResourceManager = new global::System.Resources.ResourceManager(fullClassName, assembly);
    var resourceCulture = System.Globalization.CultureInfo.CurrentUICulture;
    var str = ResourceManager.GetString(propName, resourceCulture);
    return str;
  }

  private static BindingBase CreateStaticResourceBinding(string staticResourceKey)
  {
    var k = staticResourceKey.LastIndexOf('.');
    if (k < 0)
      throw new InvalidOperationException($"HeaderResourceKey must be in the format \"typename.propName\"");
    var className = staticResourceKey.Substring(0, k);
    var propName = staticResourceKey.Substring(k + 1);
    Assembly assembly;
    k = className.LastIndexOf('.');
    if (k > 0)
    {
      var ns = className.Substring(0, k);
      className = className.Substring(k + 1);
      assembly = Assembly.Load(ns);
    }
    else
      assembly = Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();
    var staticResourceClass = assembly.GetType(className);
    if (staticResourceClass == null)
      throw new InvalidOperationException($"Type {className} not found");
    var staticResourceProperty = staticResourceClass.GetProperty(propName, BindingFlags.Public | BindingFlags.Static);
    if (staticResourceProperty == null)
      throw new InvalidOperationException($"Property {propName} in type {className} not found");
    var binding = new Binding()
    {
      Source = staticResourceClass,
      Path = new PropertyPath(staticResourceProperty),
    };
    return binding;
  }

  private static DataTemplate CreateTemplate(Type viewModelType, Type viewType)
  {
    const string xamlTemplate = "<DataTemplate DataType=\"{{x:Type vm:{0}}}\"><v:{1} /></DataTemplate>";
    var xaml = String.Format(xamlTemplate, viewModelType.Name, viewType.Name, viewModelType.Namespace, viewType.Namespace);

    var context = new ParserContext();

    context.XamlTypeMapper = new XamlTypeMapper(new string[0]);
    context.XamlTypeMapper.AddMappingProcessingInstruction("vm", viewModelType.Namespace, viewModelType.Assembly.FullName);
    context.XamlTypeMapper.AddMappingProcessingInstruction("v", viewType.Namespace, viewType.Assembly.FullName);

    context.XmlnsDictionary.Add("", "http://schemas.microsoft.com/winfx/2006/xaml/presentation");
    context.XmlnsDictionary.Add("x", "http://schemas.microsoft.com/winfx/2006/xaml");
    context.XmlnsDictionary.Add("vm", "vm");
    context.XmlnsDictionary.Add("v", "v");

    var template = (DataTemplate)XamlReader.Parse(xaml, context);
    return template;
  }

  private static ContextMenu CreateHeaderContextMenu()
  {
    var contextMenu = new ContextMenu();
    return contextMenu;
  }
  private static DataGridContentBoundColumn CreateColumn(ColumnViewInfo columnViewInfo, DataTemplate contentTemplate,
    DataTemplate? contentEditingTemplate = null)
  {
    var newColumn = new DataGridContentBoundColumn();
    var aBinding = columnViewInfo.Binding as Binding;
    newColumn.Binding = columnViewInfo.Binding;
    newColumn.ContentTemplate = contentTemplate;
    if (contentEditingTemplate != null)
      newColumn.ContentEditingTemplate = contentEditingTemplate;
    newColumn.Header = columnViewInfo.Header;
    if (columnViewInfo.HeaderTooltip != null)
      CollectionViewBehavior.SetHeaderTooltip(newColumn, columnViewInfo.HeaderTooltip);

    FormatColumn(newColumn, columnViewInfo);
    return newColumn;
  }

  private static void FormatColumn(DataGridColumn column, ColumnViewInfo columnViewInfo)
  {
    if (columnViewInfo.HeaderTemplate != null)
      column.HeaderTemplate = columnViewInfo.HeaderTemplate;
    else if (columnViewInfo.Header != null)
      column.Header = columnViewInfo.Header;
    if (columnViewInfo.HeaderStringFormat != null)
      column.HeaderStringFormat = columnViewInfo.HeaderStringFormat;
    if (columnViewInfo.HeaderTooltip != null)
      CollectionViewBehavior.SetHeaderTooltip(column, columnViewInfo.HeaderTooltip);
    var b = columnViewInfo.IsReadOnly;
    if (b == true)
      column.IsReadOnly = (bool)b;
    column.MaxWidth = columnViewInfo.MaxWidth;
    column.MinWidth = columnViewInfo.MinWidth;
    var d = columnViewInfo.Width;
    if (!double.IsNaN(d))
      column.Width = (double)d;
    column.CanUserReorder = columnViewInfo.CanUserReorder;
    column.CanUserResize = columnViewInfo.CanUserResize;
    column.CanUserSort = columnViewInfo.CanUserSort;
    column.SortMemberPath = columnViewInfo.SortMemberPath;
    column.SortDirection = columnViewInfo.SortDirection;
    if (columnViewInfo.HiddenHeader != null)
      CollectionViewBehavior.SetHiddenHeader(column, columnViewInfo.HiddenHeader);
    CollectionViewBehavior.SetShowFilterButton(column, columnViewInfo.ShowFilterButton);


    if (!String.IsNullOrEmpty(columnViewInfo.ClipboardContentPath))
    {
      column.ClipboardContentBinding =
          new Binding
          {
            Path = new PropertyPath(columnViewInfo.ClipboardContentPath),
          };
      column.CopyingCellClipboardContent += Col_CopyingCellClipboardContent;
    }

    var s = columnViewInfo.ClipboardContentPath;
    if (!String.IsNullOrEmpty(s))
      column.ClipboardContentBinding = new Binding(s);

    var n = columnViewInfo.DisplayIndex;
    if (n >= 0)
      column.DisplayIndex = n;
    n = (int)Convert.ChangeType(columnViewInfo.Visibility, typeof(int));
    column.Visibility = (System.Windows.Visibility)Enum.ToObject(typeof(System.Windows.Visibility), n);

  }

  private static void Col_CopyingCellClipboardContent(object? sender, DataGridCellClipboardEventArgs e)
  {
    var column = sender as DataGridContentBoundColumn;
    if (column != null)
    {
      var obj = e.Item;
      if (obj != null)
      {
        var binding = (column.ClipboardContentBinding as Binding);
        if (binding != null)
        {
          string boundProperty = binding.Path.Path;
          object? value = GetPropertyWithPath(obj, boundProperty);
          if (value != null)
          {
            var propertyValue = value.ToString();
            e.Content = propertyValue;
          }
        }
      }
    }
  }

  private static object? GetPropertyWithPath(object obj, string aPath)
  {
    var k = aPath.IndexOf(".");
    if (k > 0)
    {
      var propName = aPath.Substring(0, k);
      aPath = aPath.Substring(k + 1);
      PropertyInfo? pi = obj.GetType().GetProperty(propName);
      if (pi != null)
      {
        object? value = pi.GetValue(obj);
        if (value != null)
        {
          var propertyValue = GetPropertyWithPath(value, aPath);
          return propertyValue;
        }
      }
    }
    else
    {
      PropertyInfo? pi = obj.GetType().GetProperty(aPath);
      if (pi != null)
      {
        object? value = pi.GetValue(obj);
        if (value != null)
        {
          var propertyValue = value.ToString();
          return propertyValue;
        }
      }
    }
    return null;
  }
}

